name: simplecloud-api
version: "1.0"
main: app.simplecloud.api.provider.paper.PaperApiProvider
loader: app.simplecloud.api.provider.paper.PaperLoader
bootstrapper: app.simplecloud.api.provider.paper.PaperBootstrap
api-version: "1.21"
folia-supported: true