/*
SimpleCloud Controller API

API for SimpleCloud Controller

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplecloud

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)

type NetworksAPI interface {

	/*
		V0NetworksDelete Delete a network and all its resources

		Delete a network and cascade delete all associated resources (servers, groups, blueprints, etc.)

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return ApiV0NetworksDeleteRequest
	*/
	V0NetworksDelete(ctx context.Context) ApiV0NetworksDeleteRequest

	// V0NetworksDeleteExecute executes the request
	//  @return ModelsDeleteNetworkResponse
	V0NetworksDeleteExecute(r ApiV0NetworksDeleteRequest) (*ModelsDeleteNetworkResponse, *http.Response, error)

	/*
		V0NetworksPasswordsDelete Delete network password

		Delete a network password from the authenticated network

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return ApiV0NetworksPasswordsDeleteRequest
	*/
	V0NetworksPasswordsDelete(ctx context.Context) ApiV0NetworksPasswordsDeleteRequest

	// V0NetworksPasswordsDeleteExecute executes the request
	//  @return ModelsDeleteNetworkPasswordResponse
	V0NetworksPasswordsDeleteExecute(r ApiV0NetworksPasswordsDeleteRequest) (*ModelsDeleteNetworkPasswordResponse, *http.Response, error)

	/*
		V0NetworksPasswordsGet List network passwords

		List all network passwords for the authenticated network

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return ApiV0NetworksPasswordsGetRequest
	*/
	V0NetworksPasswordsGet(ctx context.Context) ApiV0NetworksPasswordsGetRequest

	// V0NetworksPasswordsGetExecute executes the request
	//  @return ModelsListNetworkPasswordsResponse
	V0NetworksPasswordsGetExecute(r ApiV0NetworksPasswordsGetRequest) (*ModelsListNetworkPasswordsResponse, *http.Response, error)

	/*
		V0NetworksPasswordsPost Create network password

		Create a new network password for the authenticated network

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return ApiV0NetworksPasswordsPostRequest
	*/
	V0NetworksPasswordsPost(ctx context.Context) ApiV0NetworksPasswordsPostRequest

	// V0NetworksPasswordsPostExecute executes the request
	//  @return ModelsCreateNetworkPasswordResponse
	V0NetworksPasswordsPostExecute(r ApiV0NetworksPasswordsPostRequest) (*ModelsCreateNetworkPasswordResponse, *http.Response, error)

	/*
		V0NetworksPatch Update a network

		Update the authenticated network

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return ApiV0NetworksPatchRequest
	*/
	V0NetworksPatch(ctx context.Context) ApiV0NetworksPatchRequest

	// V0NetworksPatchExecute executes the request
	//  @return ModelsUpdateNetworkResponse
	V0NetworksPatchExecute(r ApiV0NetworksPatchRequest) (*ModelsUpdateNetworkResponse, *http.Response, error)

	/*
		V0NetworksRegisterPost Register a new network

		Register a new network and generate credentials

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return ApiV0NetworksRegisterPostRequest
	*/
	V0NetworksRegisterPost(ctx context.Context) ApiV0NetworksRegisterPostRequest

	// V0NetworksRegisterPostExecute executes the request
	//  @return ModelsRegisterNetworkResponse
	V0NetworksRegisterPostExecute(r ApiV0NetworksRegisterPostRequest) (*ModelsRegisterNetworkResponse, *http.Response, error)

	/*
		V0NetworksVerifyPost Verify network credentials

		Verify if the provided network credentials are valid

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return ApiV0NetworksVerifyPostRequest
	*/
	V0NetworksVerifyPost(ctx context.Context) ApiV0NetworksVerifyPostRequest

	// V0NetworksVerifyPostExecute executes the request
	//  @return ModelsVerifyNetworkResponse
	V0NetworksVerifyPostExecute(r ApiV0NetworksVerifyPostRequest) (*ModelsVerifyNetworkResponse, *http.Response, error)
}

// NetworksAPIService NetworksAPI service
type NetworksAPIService service

type ApiV0NetworksDeleteRequest struct {
	ctx                context.Context
	ApiService         NetworksAPI
	xNetworkID         *string
	xNetworkCredential *string
}

// Network ID
func (r ApiV0NetworksDeleteRequest) XNetworkID(xNetworkID string) ApiV0NetworksDeleteRequest {
	r.xNetworkID = &xNetworkID
	return r
}

// Network Credential (network password or JWT)
func (r ApiV0NetworksDeleteRequest) XNetworkCredential(xNetworkCredential string) ApiV0NetworksDeleteRequest {
	r.xNetworkCredential = &xNetworkCredential
	return r
}

func (r ApiV0NetworksDeleteRequest) Execute() (*ModelsDeleteNetworkResponse, *http.Response, error) {
	return r.ApiService.V0NetworksDeleteExecute(r)
}

/*
V0NetworksDelete Delete a network and all its resources

Delete a network and cascade delete all associated resources (servers, groups, blueprints, etc.)

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiV0NetworksDeleteRequest
*/
func (a *NetworksAPIService) V0NetworksDelete(ctx context.Context) ApiV0NetworksDeleteRequest {
	return ApiV0NetworksDeleteRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return ModelsDeleteNetworkResponse
func (a *NetworksAPIService) V0NetworksDeleteExecute(r ApiV0NetworksDeleteRequest) (*ModelsDeleteNetworkResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodDelete
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *ModelsDeleteNetworkResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "NetworksAPIService.V0NetworksDelete")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v0/networks"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.xNetworkID == nil {
		return localVarReturnValue, nil, reportError("xNetworkID is required and must be specified")
	}
	if r.xNetworkCredential == nil {
		return localVarReturnValue, nil, reportError("xNetworkCredential is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Network-ID", r.xNetworkID, "simple", "")
	parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Network-Credential", r.xNetworkCredential, "simple", "")
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ModelsErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ModelsErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v ModelsErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v ModelsErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiV0NetworksPasswordsDeleteRequest struct {
	ctx                context.Context
	ApiService         NetworksAPI
	xNetworkID         *string
	xNetworkCredential *string
	passwordId         *string
	body               *map[string]interface{}
}

// Network ID
func (r ApiV0NetworksPasswordsDeleteRequest) XNetworkID(xNetworkID string) ApiV0NetworksPasswordsDeleteRequest {
	r.xNetworkID = &xNetworkID
	return r
}

// Network Credential (network password or JWT)
func (r ApiV0NetworksPasswordsDeleteRequest) XNetworkCredential(xNetworkCredential string) ApiV0NetworksPasswordsDeleteRequest {
	r.xNetworkCredential = &xNetworkCredential
	return r
}

// Password ID
func (r ApiV0NetworksPasswordsDeleteRequest) PasswordId(passwordId string) ApiV0NetworksPasswordsDeleteRequest {
	r.passwordId = &passwordId
	return r
}

func (r ApiV0NetworksPasswordsDeleteRequest) Body(body map[string]interface{}) ApiV0NetworksPasswordsDeleteRequest {
	r.body = &body
	return r
}

func (r ApiV0NetworksPasswordsDeleteRequest) Execute() (*ModelsDeleteNetworkPasswordResponse, *http.Response, error) {
	return r.ApiService.V0NetworksPasswordsDeleteExecute(r)
}

/*
V0NetworksPasswordsDelete Delete network password

Delete a network password from the authenticated network

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiV0NetworksPasswordsDeleteRequest
*/
func (a *NetworksAPIService) V0NetworksPasswordsDelete(ctx context.Context) ApiV0NetworksPasswordsDeleteRequest {
	return ApiV0NetworksPasswordsDeleteRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return ModelsDeleteNetworkPasswordResponse
func (a *NetworksAPIService) V0NetworksPasswordsDeleteExecute(r ApiV0NetworksPasswordsDeleteRequest) (*ModelsDeleteNetworkPasswordResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodDelete
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *ModelsDeleteNetworkPasswordResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "NetworksAPIService.V0NetworksPasswordsDelete")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v0/networks/passwords"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.xNetworkID == nil {
		return localVarReturnValue, nil, reportError("xNetworkID is required and must be specified")
	}
	if r.xNetworkCredential == nil {
		return localVarReturnValue, nil, reportError("xNetworkCredential is required and must be specified")
	}
	if r.passwordId == nil {
		return localVarReturnValue, nil, reportError("passwordId is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "password_id", r.passwordId, "form", "")
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Network-ID", r.xNetworkID, "simple", "")
	parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Network-Credential", r.xNetworkCredential, "simple", "")
	// body params
	localVarPostBody = r.body
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ModelsErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ModelsErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v ModelsErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v ModelsErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiV0NetworksPasswordsGetRequest struct {
	ctx                context.Context
	ApiService         NetworksAPI
	xNetworkID         *string
	xNetworkCredential *string
	body               *map[string]interface{}
}

// Network ID
func (r ApiV0NetworksPasswordsGetRequest) XNetworkID(xNetworkID string) ApiV0NetworksPasswordsGetRequest {
	r.xNetworkID = &xNetworkID
	return r
}

// Network Credential (network password or JWT)
func (r ApiV0NetworksPasswordsGetRequest) XNetworkCredential(xNetworkCredential string) ApiV0NetworksPasswordsGetRequest {
	r.xNetworkCredential = &xNetworkCredential
	return r
}

func (r ApiV0NetworksPasswordsGetRequest) Body(body map[string]interface{}) ApiV0NetworksPasswordsGetRequest {
	r.body = &body
	return r
}

func (r ApiV0NetworksPasswordsGetRequest) Execute() (*ModelsListNetworkPasswordsResponse, *http.Response, error) {
	return r.ApiService.V0NetworksPasswordsGetExecute(r)
}

/*
V0NetworksPasswordsGet List network passwords

List all network passwords for the authenticated network

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiV0NetworksPasswordsGetRequest
*/
func (a *NetworksAPIService) V0NetworksPasswordsGet(ctx context.Context) ApiV0NetworksPasswordsGetRequest {
	return ApiV0NetworksPasswordsGetRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return ModelsListNetworkPasswordsResponse
func (a *NetworksAPIService) V0NetworksPasswordsGetExecute(r ApiV0NetworksPasswordsGetRequest) (*ModelsListNetworkPasswordsResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *ModelsListNetworkPasswordsResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "NetworksAPIService.V0NetworksPasswordsGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v0/networks/passwords"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.xNetworkID == nil {
		return localVarReturnValue, nil, reportError("xNetworkID is required and must be specified")
	}
	if r.xNetworkCredential == nil {
		return localVarReturnValue, nil, reportError("xNetworkCredential is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Network-ID", r.xNetworkID, "simple", "")
	parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Network-Credential", r.xNetworkCredential, "simple", "")
	// body params
	localVarPostBody = r.body
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ModelsErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ModelsErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v ModelsErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v ModelsErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiV0NetworksPasswordsPostRequest struct {
	ctx                                context.Context
	ApiService                         NetworksAPI
	xNetworkID                         *string
	xNetworkCredential                 *string
	modelsCreateNetworkPasswordRequest *ModelsCreateNetworkPasswordRequest
}

// Network ID
func (r ApiV0NetworksPasswordsPostRequest) XNetworkID(xNetworkID string) ApiV0NetworksPasswordsPostRequest {
	r.xNetworkID = &xNetworkID
	return r
}

// Network Credential (network password or JWT)
func (r ApiV0NetworksPasswordsPostRequest) XNetworkCredential(xNetworkCredential string) ApiV0NetworksPasswordsPostRequest {
	r.xNetworkCredential = &xNetworkCredential
	return r
}

// Network password details
func (r ApiV0NetworksPasswordsPostRequest) ModelsCreateNetworkPasswordRequest(modelsCreateNetworkPasswordRequest ModelsCreateNetworkPasswordRequest) ApiV0NetworksPasswordsPostRequest {
	r.modelsCreateNetworkPasswordRequest = &modelsCreateNetworkPasswordRequest
	return r
}

func (r ApiV0NetworksPasswordsPostRequest) Execute() (*ModelsCreateNetworkPasswordResponse, *http.Response, error) {
	return r.ApiService.V0NetworksPasswordsPostExecute(r)
}

/*
V0NetworksPasswordsPost Create network password

Create a new network password for the authenticated network

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiV0NetworksPasswordsPostRequest
*/
func (a *NetworksAPIService) V0NetworksPasswordsPost(ctx context.Context) ApiV0NetworksPasswordsPostRequest {
	return ApiV0NetworksPasswordsPostRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return ModelsCreateNetworkPasswordResponse
func (a *NetworksAPIService) V0NetworksPasswordsPostExecute(r ApiV0NetworksPasswordsPostRequest) (*ModelsCreateNetworkPasswordResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *ModelsCreateNetworkPasswordResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "NetworksAPIService.V0NetworksPasswordsPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v0/networks/passwords"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.xNetworkID == nil {
		return localVarReturnValue, nil, reportError("xNetworkID is required and must be specified")
	}
	if r.xNetworkCredential == nil {
		return localVarReturnValue, nil, reportError("xNetworkCredential is required and must be specified")
	}
	if r.modelsCreateNetworkPasswordRequest == nil {
		return localVarReturnValue, nil, reportError("modelsCreateNetworkPasswordRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Network-ID", r.xNetworkID, "simple", "")
	parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Network-Credential", r.xNetworkCredential, "simple", "")
	// body params
	localVarPostBody = r.modelsCreateNetworkPasswordRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ModelsErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ModelsErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v ModelsErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v ModelsErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiV0NetworksPatchRequest struct {
	ctx                        context.Context
	ApiService                 NetworksAPI
	xNetworkID                 *string
	xNetworkCredential         *string
	modelsUpdateNetworkRequest *ModelsUpdateNetworkRequest
}

// Network ID
func (r ApiV0NetworksPatchRequest) XNetworkID(xNetworkID string) ApiV0NetworksPatchRequest {
	r.xNetworkID = &xNetworkID
	return r
}

// Network Credential (network password or JWT)
func (r ApiV0NetworksPatchRequest) XNetworkCredential(xNetworkCredential string) ApiV0NetworksPatchRequest {
	r.xNetworkCredential = &xNetworkCredential
	return r
}

// Updated network details
func (r ApiV0NetworksPatchRequest) ModelsUpdateNetworkRequest(modelsUpdateNetworkRequest ModelsUpdateNetworkRequest) ApiV0NetworksPatchRequest {
	r.modelsUpdateNetworkRequest = &modelsUpdateNetworkRequest
	return r
}

func (r ApiV0NetworksPatchRequest) Execute() (*ModelsUpdateNetworkResponse, *http.Response, error) {
	return r.ApiService.V0NetworksPatchExecute(r)
}

/*
V0NetworksPatch Update a network

Update the authenticated network

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiV0NetworksPatchRequest
*/
func (a *NetworksAPIService) V0NetworksPatch(ctx context.Context) ApiV0NetworksPatchRequest {
	return ApiV0NetworksPatchRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return ModelsUpdateNetworkResponse
func (a *NetworksAPIService) V0NetworksPatchExecute(r ApiV0NetworksPatchRequest) (*ModelsUpdateNetworkResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPatch
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *ModelsUpdateNetworkResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "NetworksAPIService.V0NetworksPatch")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v0/networks"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.xNetworkID == nil {
		return localVarReturnValue, nil, reportError("xNetworkID is required and must be specified")
	}
	if r.xNetworkCredential == nil {
		return localVarReturnValue, nil, reportError("xNetworkCredential is required and must be specified")
	}
	if r.modelsUpdateNetworkRequest == nil {
		return localVarReturnValue, nil, reportError("modelsUpdateNetworkRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Network-ID", r.xNetworkID, "simple", "")
	parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Network-Credential", r.xNetworkCredential, "simple", "")
	// body params
	localVarPostBody = r.modelsUpdateNetworkRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ModelsErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ModelsErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v ModelsErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v ModelsErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v ModelsErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiV0NetworksRegisterPostRequest struct {
	ctx                          context.Context
	ApiService                   NetworksAPI
	modelsRegisterNetworkRequest *ModelsRegisterNetworkRequest
}

// Optional network details
func (r ApiV0NetworksRegisterPostRequest) ModelsRegisterNetworkRequest(modelsRegisterNetworkRequest ModelsRegisterNetworkRequest) ApiV0NetworksRegisterPostRequest {
	r.modelsRegisterNetworkRequest = &modelsRegisterNetworkRequest
	return r
}

func (r ApiV0NetworksRegisterPostRequest) Execute() (*ModelsRegisterNetworkResponse, *http.Response, error) {
	return r.ApiService.V0NetworksRegisterPostExecute(r)
}

/*
V0NetworksRegisterPost Register a new network

Register a new network and generate credentials

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiV0NetworksRegisterPostRequest
*/
func (a *NetworksAPIService) V0NetworksRegisterPost(ctx context.Context) ApiV0NetworksRegisterPostRequest {
	return ApiV0NetworksRegisterPostRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return ModelsRegisterNetworkResponse
func (a *NetworksAPIService) V0NetworksRegisterPostExecute(r ApiV0NetworksRegisterPostRequest) (*ModelsRegisterNetworkResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *ModelsRegisterNetworkResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "NetworksAPIService.V0NetworksRegisterPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v0/networks/register"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.modelsRegisterNetworkRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiV0NetworksVerifyPostRequest struct {
	ctx                        context.Context
	ApiService                 NetworksAPI
	modelsVerifyNetworkRequest *ModelsVerifyNetworkRequest
}

// Network credentials
func (r ApiV0NetworksVerifyPostRequest) ModelsVerifyNetworkRequest(modelsVerifyNetworkRequest ModelsVerifyNetworkRequest) ApiV0NetworksVerifyPostRequest {
	r.modelsVerifyNetworkRequest = &modelsVerifyNetworkRequest
	return r
}

func (r ApiV0NetworksVerifyPostRequest) Execute() (*ModelsVerifyNetworkResponse, *http.Response, error) {
	return r.ApiService.V0NetworksVerifyPostExecute(r)
}

/*
V0NetworksVerifyPost Verify network credentials

Verify if the provided network credentials are valid

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiV0NetworksVerifyPostRequest
*/
func (a *NetworksAPIService) V0NetworksVerifyPost(ctx context.Context) ApiV0NetworksVerifyPostRequest {
	return ApiV0NetworksVerifyPostRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return ModelsVerifyNetworkResponse
func (a *NetworksAPIService) V0NetworksVerifyPostExecute(r ApiV0NetworksVerifyPostRequest) (*ModelsVerifyNetworkResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *ModelsVerifyNetworkResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "NetworksAPIService.V0NetworksVerifyPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v0/networks/verify"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.modelsVerifyNetworkRequest == nil {
		return localVarReturnValue, nil, reportError("modelsVerifyNetworkRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.modelsVerifyNetworkRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ModelsVerifyNetworkResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ModelsVerifyNetworkResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v ModelsVerifyNetworkResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
