/*
SimpleCloud Controller API

API for SimpleCloud Controller

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplecloud

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)

type BlueprintsAPI interface {

	/*
		V0BlueprintsDelete Delete a blueprint

		Delete an existing blueprint

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return ApiV0BlueprintsDeleteRequest
	*/
	V0BlueprintsDelete(ctx context.Context) ApiV0BlueprintsDeleteRequest

	// V0BlueprintsDeleteExecute executes the request
	//  @return ModelsDeleteBlueprintResponse
	V0BlueprintsDeleteExecute(r ApiV0BlueprintsDeleteRequest) (*ModelsDeleteBlueprintResponse, *http.Response, error)

	/*
		V0BlueprintsGet List blueprints

		Get a list of blueprints for a network

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return ApiV0BlueprintsGetRequest
	*/
	V0BlueprintsGet(ctx context.Context) ApiV0BlueprintsGetRequest

	// V0BlueprintsGetExecute executes the request
	//  @return ModelsListBlueprintsResponse
	V0BlueprintsGetExecute(r ApiV0BlueprintsGetRequest) (*ModelsListBlueprintsResponse, *http.Response, error)

	/*
		V0BlueprintsPatch Partially update a blueprint

		Partially update an existing blueprint

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return ApiV0BlueprintsPatchRequest
	*/
	V0BlueprintsPatch(ctx context.Context) ApiV0BlueprintsPatchRequest

	// V0BlueprintsPatchExecute executes the request
	//  @return ModelsUpdateBlueprintResponse
	V0BlueprintsPatchExecute(r ApiV0BlueprintsPatchRequest) (*ModelsUpdateBlueprintResponse, *http.Response, error)

	/*
		V0BlueprintsPost Create a new blueprint

		Create a new blueprint for a network

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return ApiV0BlueprintsPostRequest
	*/
	V0BlueprintsPost(ctx context.Context) ApiV0BlueprintsPostRequest

	// V0BlueprintsPostExecute executes the request
	//  @return ModelsCreateBlueprintResponse
	V0BlueprintsPostExecute(r ApiV0BlueprintsPostRequest) (*ModelsCreateBlueprintResponse, *http.Response, error)

	/*
		V0BlueprintsPut Update a blueprint

		Update an existing blueprint

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return ApiV0BlueprintsPutRequest
	*/
	V0BlueprintsPut(ctx context.Context) ApiV0BlueprintsPutRequest

	// V0BlueprintsPutExecute executes the request
	//  @return ModelsUpdateBlueprintResponse
	V0BlueprintsPutExecute(r ApiV0BlueprintsPutRequest) (*ModelsUpdateBlueprintResponse, *http.Response, error)
}

// BlueprintsAPIService BlueprintsAPI service
type BlueprintsAPIService service

type ApiV0BlueprintsDeleteRequest struct {
	ctx                context.Context
	ApiService         BlueprintsAPI
	xNetworkID         *string
	xNetworkCredential *string
	blueprintId        *string
}

// Network ID
func (r ApiV0BlueprintsDeleteRequest) XNetworkID(xNetworkID string) ApiV0BlueprintsDeleteRequest {
	r.xNetworkID = &xNetworkID
	return r
}

// Network Credential (network password or JWT)
func (r ApiV0BlueprintsDeleteRequest) XNetworkCredential(xNetworkCredential string) ApiV0BlueprintsDeleteRequest {
	r.xNetworkCredential = &xNetworkCredential
	return r
}

// Blueprint ID
func (r ApiV0BlueprintsDeleteRequest) BlueprintId(blueprintId string) ApiV0BlueprintsDeleteRequest {
	r.blueprintId = &blueprintId
	return r
}

func (r ApiV0BlueprintsDeleteRequest) Execute() (*ModelsDeleteBlueprintResponse, *http.Response, error) {
	return r.ApiService.V0BlueprintsDeleteExecute(r)
}

/*
V0BlueprintsDelete Delete a blueprint

Delete an existing blueprint

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiV0BlueprintsDeleteRequest
*/
func (a *BlueprintsAPIService) V0BlueprintsDelete(ctx context.Context) ApiV0BlueprintsDeleteRequest {
	return ApiV0BlueprintsDeleteRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return ModelsDeleteBlueprintResponse
func (a *BlueprintsAPIService) V0BlueprintsDeleteExecute(r ApiV0BlueprintsDeleteRequest) (*ModelsDeleteBlueprintResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodDelete
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *ModelsDeleteBlueprintResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "BlueprintsAPIService.V0BlueprintsDelete")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v0/blueprints"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.xNetworkID == nil {
		return localVarReturnValue, nil, reportError("xNetworkID is required and must be specified")
	}
	if r.xNetworkCredential == nil {
		return localVarReturnValue, nil, reportError("xNetworkCredential is required and must be specified")
	}
	if r.blueprintId == nil {
		return localVarReturnValue, nil, reportError("blueprintId is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "blueprint_id", r.blueprintId, "form", "")
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Network-ID", r.xNetworkID, "simple", "")
	parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Network-Credential", r.xNetworkCredential, "simple", "")
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ModelsErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ModelsErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v ModelsErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v ModelsErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiV0BlueprintsGetRequest struct {
	ctx                context.Context
	ApiService         BlueprintsAPI
	xNetworkID         *string
	xNetworkCredential *string
}

// Network ID
func (r ApiV0BlueprintsGetRequest) XNetworkID(xNetworkID string) ApiV0BlueprintsGetRequest {
	r.xNetworkID = &xNetworkID
	return r
}

// Network Credential (network password or JWT)
func (r ApiV0BlueprintsGetRequest) XNetworkCredential(xNetworkCredential string) ApiV0BlueprintsGetRequest {
	r.xNetworkCredential = &xNetworkCredential
	return r
}

func (r ApiV0BlueprintsGetRequest) Execute() (*ModelsListBlueprintsResponse, *http.Response, error) {
	return r.ApiService.V0BlueprintsGetExecute(r)
}

/*
V0BlueprintsGet List blueprints

Get a list of blueprints for a network

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiV0BlueprintsGetRequest
*/
func (a *BlueprintsAPIService) V0BlueprintsGet(ctx context.Context) ApiV0BlueprintsGetRequest {
	return ApiV0BlueprintsGetRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return ModelsListBlueprintsResponse
func (a *BlueprintsAPIService) V0BlueprintsGetExecute(r ApiV0BlueprintsGetRequest) (*ModelsListBlueprintsResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *ModelsListBlueprintsResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "BlueprintsAPIService.V0BlueprintsGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v0/blueprints"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.xNetworkID == nil {
		return localVarReturnValue, nil, reportError("xNetworkID is required and must be specified")
	}
	if r.xNetworkCredential == nil {
		return localVarReturnValue, nil, reportError("xNetworkCredential is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Network-ID", r.xNetworkID, "simple", "")
	parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Network-Credential", r.xNetworkCredential, "simple", "")
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ModelsErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v ModelsErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiV0BlueprintsPatchRequest struct {
	ctx                         context.Context
	ApiService                  BlueprintsAPI
	xNetworkID                  *string
	xNetworkCredential          *string
	blueprintId                 *string
	modelsPatchBlueprintRequest *ModelsPatchBlueprintRequest
}

// Network ID
func (r ApiV0BlueprintsPatchRequest) XNetworkID(xNetworkID string) ApiV0BlueprintsPatchRequest {
	r.xNetworkID = &xNetworkID
	return r
}

// Network Credential (network password or JWT)
func (r ApiV0BlueprintsPatchRequest) XNetworkCredential(xNetworkCredential string) ApiV0BlueprintsPatchRequest {
	r.xNetworkCredential = &xNetworkCredential
	return r
}

// Blueprint ID
func (r ApiV0BlueprintsPatchRequest) BlueprintId(blueprintId string) ApiV0BlueprintsPatchRequest {
	r.blueprintId = &blueprintId
	return r
}

// Blueprint fields to update
func (r ApiV0BlueprintsPatchRequest) ModelsPatchBlueprintRequest(modelsPatchBlueprintRequest ModelsPatchBlueprintRequest) ApiV0BlueprintsPatchRequest {
	r.modelsPatchBlueprintRequest = &modelsPatchBlueprintRequest
	return r
}

func (r ApiV0BlueprintsPatchRequest) Execute() (*ModelsUpdateBlueprintResponse, *http.Response, error) {
	return r.ApiService.V0BlueprintsPatchExecute(r)
}

/*
V0BlueprintsPatch Partially update a blueprint

Partially update an existing blueprint

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiV0BlueprintsPatchRequest
*/
func (a *BlueprintsAPIService) V0BlueprintsPatch(ctx context.Context) ApiV0BlueprintsPatchRequest {
	return ApiV0BlueprintsPatchRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return ModelsUpdateBlueprintResponse
func (a *BlueprintsAPIService) V0BlueprintsPatchExecute(r ApiV0BlueprintsPatchRequest) (*ModelsUpdateBlueprintResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPatch
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *ModelsUpdateBlueprintResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "BlueprintsAPIService.V0BlueprintsPatch")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v0/blueprints"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.xNetworkID == nil {
		return localVarReturnValue, nil, reportError("xNetworkID is required and must be specified")
	}
	if r.xNetworkCredential == nil {
		return localVarReturnValue, nil, reportError("xNetworkCredential is required and must be specified")
	}
	if r.blueprintId == nil {
		return localVarReturnValue, nil, reportError("blueprintId is required and must be specified")
	}
	if r.modelsPatchBlueprintRequest == nil {
		return localVarReturnValue, nil, reportError("modelsPatchBlueprintRequest is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "blueprint_id", r.blueprintId, "form", "")
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Network-ID", r.xNetworkID, "simple", "")
	parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Network-Credential", r.xNetworkCredential, "simple", "")
	// body params
	localVarPostBody = r.modelsPatchBlueprintRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ModelsErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ModelsErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v ModelsErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v ModelsErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiV0BlueprintsPostRequest struct {
	ctx                          context.Context
	ApiService                   BlueprintsAPI
	xNetworkID                   *string
	xNetworkCredential           *string
	modelsCreateBlueprintRequest *ModelsCreateBlueprintRequest
}

// Network ID
func (r ApiV0BlueprintsPostRequest) XNetworkID(xNetworkID string) ApiV0BlueprintsPostRequest {
	r.xNetworkID = &xNetworkID
	return r
}

// Network Credential (network password or JWT)
func (r ApiV0BlueprintsPostRequest) XNetworkCredential(xNetworkCredential string) ApiV0BlueprintsPostRequest {
	r.xNetworkCredential = &xNetworkCredential
	return r
}

// Blueprint details
func (r ApiV0BlueprintsPostRequest) ModelsCreateBlueprintRequest(modelsCreateBlueprintRequest ModelsCreateBlueprintRequest) ApiV0BlueprintsPostRequest {
	r.modelsCreateBlueprintRequest = &modelsCreateBlueprintRequest
	return r
}

func (r ApiV0BlueprintsPostRequest) Execute() (*ModelsCreateBlueprintResponse, *http.Response, error) {
	return r.ApiService.V0BlueprintsPostExecute(r)
}

/*
V0BlueprintsPost Create a new blueprint

Create a new blueprint for a network

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiV0BlueprintsPostRequest
*/
func (a *BlueprintsAPIService) V0BlueprintsPost(ctx context.Context) ApiV0BlueprintsPostRequest {
	return ApiV0BlueprintsPostRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return ModelsCreateBlueprintResponse
func (a *BlueprintsAPIService) V0BlueprintsPostExecute(r ApiV0BlueprintsPostRequest) (*ModelsCreateBlueprintResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *ModelsCreateBlueprintResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "BlueprintsAPIService.V0BlueprintsPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v0/blueprints"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.xNetworkID == nil {
		return localVarReturnValue, nil, reportError("xNetworkID is required and must be specified")
	}
	if r.xNetworkCredential == nil {
		return localVarReturnValue, nil, reportError("xNetworkCredential is required and must be specified")
	}
	if r.modelsCreateBlueprintRequest == nil {
		return localVarReturnValue, nil, reportError("modelsCreateBlueprintRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Network-ID", r.xNetworkID, "simple", "")
	parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Network-Credential", r.xNetworkCredential, "simple", "")
	// body params
	localVarPostBody = r.modelsCreateBlueprintRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ModelsErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ModelsErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v ModelsErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiV0BlueprintsPutRequest struct {
	ctx                          context.Context
	ApiService                   BlueprintsAPI
	xNetworkID                   *string
	xNetworkCredential           *string
	blueprintId                  *string
	modelsUpdateBlueprintRequest *ModelsUpdateBlueprintRequest
}

// Network ID
func (r ApiV0BlueprintsPutRequest) XNetworkID(xNetworkID string) ApiV0BlueprintsPutRequest {
	r.xNetworkID = &xNetworkID
	return r
}

// Network Credential (network password or JWT)
func (r ApiV0BlueprintsPutRequest) XNetworkCredential(xNetworkCredential string) ApiV0BlueprintsPutRequest {
	r.xNetworkCredential = &xNetworkCredential
	return r
}

// Blueprint ID
func (r ApiV0BlueprintsPutRequest) BlueprintId(blueprintId string) ApiV0BlueprintsPutRequest {
	r.blueprintId = &blueprintId
	return r
}

// Blueprint details
func (r ApiV0BlueprintsPutRequest) ModelsUpdateBlueprintRequest(modelsUpdateBlueprintRequest ModelsUpdateBlueprintRequest) ApiV0BlueprintsPutRequest {
	r.modelsUpdateBlueprintRequest = &modelsUpdateBlueprintRequest
	return r
}

func (r ApiV0BlueprintsPutRequest) Execute() (*ModelsUpdateBlueprintResponse, *http.Response, error) {
	return r.ApiService.V0BlueprintsPutExecute(r)
}

/*
V0BlueprintsPut Update a blueprint

Update an existing blueprint

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiV0BlueprintsPutRequest
*/
func (a *BlueprintsAPIService) V0BlueprintsPut(ctx context.Context) ApiV0BlueprintsPutRequest {
	return ApiV0BlueprintsPutRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return ModelsUpdateBlueprintResponse
func (a *BlueprintsAPIService) V0BlueprintsPutExecute(r ApiV0BlueprintsPutRequest) (*ModelsUpdateBlueprintResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPut
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *ModelsUpdateBlueprintResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "BlueprintsAPIService.V0BlueprintsPut")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v0/blueprints"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.xNetworkID == nil {
		return localVarReturnValue, nil, reportError("xNetworkID is required and must be specified")
	}
	if r.xNetworkCredential == nil {
		return localVarReturnValue, nil, reportError("xNetworkCredential is required and must be specified")
	}
	if r.blueprintId == nil {
		return localVarReturnValue, nil, reportError("blueprintId is required and must be specified")
	}
	if r.modelsUpdateBlueprintRequest == nil {
		return localVarReturnValue, nil, reportError("modelsUpdateBlueprintRequest is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "blueprint_id", r.blueprintId, "form", "")
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Network-ID", r.xNetworkID, "simple", "")
	parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Network-Credential", r.xNetworkCredential, "simple", "")
	// body params
	localVarPostBody = r.modelsUpdateBlueprintRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ModelsErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ModelsErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v ModelsErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v ModelsErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
