/*
SimpleCloud Controller API

API for SimpleCloud Controller

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplecloud

import (
	"encoding/json"
)

// checks if the ModelsCreateBlueprintResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsCreateBlueprintResponse{}

// ModelsCreateBlueprintResponse Response for creating a new blueprint
type ModelsCreateBlueprintResponse struct {
	BlueprintId      *string              `json:"blueprint_id,omitempty"`
	Configurator     *string              `json:"configurator,omitempty"`
	CreatedAt        *string              `json:"created_at,omitempty"`
	MinecraftVersion *string              `json:"minecraft_version,omitempty"`
	Name             *string              `json:"name,omitempty"`
	RuntimeConfig    *ModelsRuntimeConfig `json:"runtime_config,omitempty"`
	ServerSoftware   *string              `json:"server_software,omitempty"`
	ServerUrl        *string              `json:"server_url,omitempty"`
	SoftwareVersion  *string              `json:"software_version,omitempty"`
	UpdatedAt        *string              `json:"updated_at,omitempty"`
	WorkflowSteps    []string             `json:"workflow_steps,omitempty"`
}

// NewModelsCreateBlueprintResponse instantiates a new ModelsCreateBlueprintResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsCreateBlueprintResponse() *ModelsCreateBlueprintResponse {
	this := ModelsCreateBlueprintResponse{}
	return &this
}

// NewModelsCreateBlueprintResponseWithDefaults instantiates a new ModelsCreateBlueprintResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsCreateBlueprintResponseWithDefaults() *ModelsCreateBlueprintResponse {
	this := ModelsCreateBlueprintResponse{}
	return &this
}

// GetBlueprintId returns the BlueprintId field value if set, zero value otherwise.
func (o *ModelsCreateBlueprintResponse) GetBlueprintId() string {
	if o == nil || IsNil(o.BlueprintId) {
		var ret string
		return ret
	}
	return *o.BlueprintId
}

// GetBlueprintIdOk returns a tuple with the BlueprintId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsCreateBlueprintResponse) GetBlueprintIdOk() (*string, bool) {
	if o == nil || IsNil(o.BlueprintId) {
		return nil, false
	}
	return o.BlueprintId, true
}

// HasBlueprintId returns a boolean if a field has been set.
func (o *ModelsCreateBlueprintResponse) HasBlueprintId() bool {
	if o != nil && !IsNil(o.BlueprintId) {
		return true
	}

	return false
}

// SetBlueprintId gets a reference to the given string and assigns it to the BlueprintId field.
func (o *ModelsCreateBlueprintResponse) SetBlueprintId(v string) {
	o.BlueprintId = &v
}

// GetConfigurator returns the Configurator field value if set, zero value otherwise.
func (o *ModelsCreateBlueprintResponse) GetConfigurator() string {
	if o == nil || IsNil(o.Configurator) {
		var ret string
		return ret
	}
	return *o.Configurator
}

// GetConfiguratorOk returns a tuple with the Configurator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsCreateBlueprintResponse) GetConfiguratorOk() (*string, bool) {
	if o == nil || IsNil(o.Configurator) {
		return nil, false
	}
	return o.Configurator, true
}

// HasConfigurator returns a boolean if a field has been set.
func (o *ModelsCreateBlueprintResponse) HasConfigurator() bool {
	if o != nil && !IsNil(o.Configurator) {
		return true
	}

	return false
}

// SetConfigurator gets a reference to the given string and assigns it to the Configurator field.
func (o *ModelsCreateBlueprintResponse) SetConfigurator(v string) {
	o.Configurator = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ModelsCreateBlueprintResponse) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsCreateBlueprintResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ModelsCreateBlueprintResponse) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *ModelsCreateBlueprintResponse) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetMinecraftVersion returns the MinecraftVersion field value if set, zero value otherwise.
func (o *ModelsCreateBlueprintResponse) GetMinecraftVersion() string {
	if o == nil || IsNil(o.MinecraftVersion) {
		var ret string
		return ret
	}
	return *o.MinecraftVersion
}

// GetMinecraftVersionOk returns a tuple with the MinecraftVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsCreateBlueprintResponse) GetMinecraftVersionOk() (*string, bool) {
	if o == nil || IsNil(o.MinecraftVersion) {
		return nil, false
	}
	return o.MinecraftVersion, true
}

// HasMinecraftVersion returns a boolean if a field has been set.
func (o *ModelsCreateBlueprintResponse) HasMinecraftVersion() bool {
	if o != nil && !IsNil(o.MinecraftVersion) {
		return true
	}

	return false
}

// SetMinecraftVersion gets a reference to the given string and assigns it to the MinecraftVersion field.
func (o *ModelsCreateBlueprintResponse) SetMinecraftVersion(v string) {
	o.MinecraftVersion = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ModelsCreateBlueprintResponse) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsCreateBlueprintResponse) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ModelsCreateBlueprintResponse) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ModelsCreateBlueprintResponse) SetName(v string) {
	o.Name = &v
}

// GetRuntimeConfig returns the RuntimeConfig field value if set, zero value otherwise.
func (o *ModelsCreateBlueprintResponse) GetRuntimeConfig() ModelsRuntimeConfig {
	if o == nil || IsNil(o.RuntimeConfig) {
		var ret ModelsRuntimeConfig
		return ret
	}
	return *o.RuntimeConfig
}

// GetRuntimeConfigOk returns a tuple with the RuntimeConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsCreateBlueprintResponse) GetRuntimeConfigOk() (*ModelsRuntimeConfig, bool) {
	if o == nil || IsNil(o.RuntimeConfig) {
		return nil, false
	}
	return o.RuntimeConfig, true
}

// HasRuntimeConfig returns a boolean if a field has been set.
func (o *ModelsCreateBlueprintResponse) HasRuntimeConfig() bool {
	if o != nil && !IsNil(o.RuntimeConfig) {
		return true
	}

	return false
}

// SetRuntimeConfig gets a reference to the given ModelsRuntimeConfig and assigns it to the RuntimeConfig field.
func (o *ModelsCreateBlueprintResponse) SetRuntimeConfig(v ModelsRuntimeConfig) {
	o.RuntimeConfig = &v
}

// GetServerSoftware returns the ServerSoftware field value if set, zero value otherwise.
func (o *ModelsCreateBlueprintResponse) GetServerSoftware() string {
	if o == nil || IsNil(o.ServerSoftware) {
		var ret string
		return ret
	}
	return *o.ServerSoftware
}

// GetServerSoftwareOk returns a tuple with the ServerSoftware field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsCreateBlueprintResponse) GetServerSoftwareOk() (*string, bool) {
	if o == nil || IsNil(o.ServerSoftware) {
		return nil, false
	}
	return o.ServerSoftware, true
}

// HasServerSoftware returns a boolean if a field has been set.
func (o *ModelsCreateBlueprintResponse) HasServerSoftware() bool {
	if o != nil && !IsNil(o.ServerSoftware) {
		return true
	}

	return false
}

// SetServerSoftware gets a reference to the given string and assigns it to the ServerSoftware field.
func (o *ModelsCreateBlueprintResponse) SetServerSoftware(v string) {
	o.ServerSoftware = &v
}

// GetServerUrl returns the ServerUrl field value if set, zero value otherwise.
func (o *ModelsCreateBlueprintResponse) GetServerUrl() string {
	if o == nil || IsNil(o.ServerUrl) {
		var ret string
		return ret
	}
	return *o.ServerUrl
}

// GetServerUrlOk returns a tuple with the ServerUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsCreateBlueprintResponse) GetServerUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ServerUrl) {
		return nil, false
	}
	return o.ServerUrl, true
}

// HasServerUrl returns a boolean if a field has been set.
func (o *ModelsCreateBlueprintResponse) HasServerUrl() bool {
	if o != nil && !IsNil(o.ServerUrl) {
		return true
	}

	return false
}

// SetServerUrl gets a reference to the given string and assigns it to the ServerUrl field.
func (o *ModelsCreateBlueprintResponse) SetServerUrl(v string) {
	o.ServerUrl = &v
}

// GetSoftwareVersion returns the SoftwareVersion field value if set, zero value otherwise.
func (o *ModelsCreateBlueprintResponse) GetSoftwareVersion() string {
	if o == nil || IsNil(o.SoftwareVersion) {
		var ret string
		return ret
	}
	return *o.SoftwareVersion
}

// GetSoftwareVersionOk returns a tuple with the SoftwareVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsCreateBlueprintResponse) GetSoftwareVersionOk() (*string, bool) {
	if o == nil || IsNil(o.SoftwareVersion) {
		return nil, false
	}
	return o.SoftwareVersion, true
}

// HasSoftwareVersion returns a boolean if a field has been set.
func (o *ModelsCreateBlueprintResponse) HasSoftwareVersion() bool {
	if o != nil && !IsNil(o.SoftwareVersion) {
		return true
	}

	return false
}

// SetSoftwareVersion gets a reference to the given string and assigns it to the SoftwareVersion field.
func (o *ModelsCreateBlueprintResponse) SetSoftwareVersion(v string) {
	o.SoftwareVersion = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *ModelsCreateBlueprintResponse) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsCreateBlueprintResponse) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *ModelsCreateBlueprintResponse) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *ModelsCreateBlueprintResponse) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetWorkflowSteps returns the WorkflowSteps field value if set, zero value otherwise.
func (o *ModelsCreateBlueprintResponse) GetWorkflowSteps() []string {
	if o == nil || IsNil(o.WorkflowSteps) {
		var ret []string
		return ret
	}
	return o.WorkflowSteps
}

// GetWorkflowStepsOk returns a tuple with the WorkflowSteps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsCreateBlueprintResponse) GetWorkflowStepsOk() ([]string, bool) {
	if o == nil || IsNil(o.WorkflowSteps) {
		return nil, false
	}
	return o.WorkflowSteps, true
}

// HasWorkflowSteps returns a boolean if a field has been set.
func (o *ModelsCreateBlueprintResponse) HasWorkflowSteps() bool {
	if o != nil && !IsNil(o.WorkflowSteps) {
		return true
	}

	return false
}

// SetWorkflowSteps gets a reference to the given []string and assigns it to the WorkflowSteps field.
func (o *ModelsCreateBlueprintResponse) SetWorkflowSteps(v []string) {
	o.WorkflowSteps = v
}

func (o ModelsCreateBlueprintResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsCreateBlueprintResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BlueprintId) {
		toSerialize["blueprint_id"] = o.BlueprintId
	}
	if !IsNil(o.Configurator) {
		toSerialize["configurator"] = o.Configurator
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.MinecraftVersion) {
		toSerialize["minecraft_version"] = o.MinecraftVersion
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.RuntimeConfig) {
		toSerialize["runtime_config"] = o.RuntimeConfig
	}
	if !IsNil(o.ServerSoftware) {
		toSerialize["server_software"] = o.ServerSoftware
	}
	if !IsNil(o.ServerUrl) {
		toSerialize["server_url"] = o.ServerUrl
	}
	if !IsNil(o.SoftwareVersion) {
		toSerialize["software_version"] = o.SoftwareVersion
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.WorkflowSteps) {
		toSerialize["workflow_steps"] = o.WorkflowSteps
	}
	return toSerialize, nil
}

type NullableModelsCreateBlueprintResponse struct {
	value *ModelsCreateBlueprintResponse
	isSet bool
}

func (v NullableModelsCreateBlueprintResponse) Get() *ModelsCreateBlueprintResponse {
	return v.value
}

func (v *NullableModelsCreateBlueprintResponse) Set(val *ModelsCreateBlueprintResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsCreateBlueprintResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsCreateBlueprintResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsCreateBlueprintResponse(val *ModelsCreateBlueprintResponse) *NullableModelsCreateBlueprintResponse {
	return &NullableModelsCreateBlueprintResponse{value: val, isSet: true}
}

func (v NullableModelsCreateBlueprintResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsCreateBlueprintResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
