/*
SimpleCloud Controller API

API for SimpleCloud Controller

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplecloud

import (
	"encoding/json"
)

// checks if the ModelsResolveServerhostGatewayRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsResolveServerhostGatewayRequest{}

// ModelsResolveServerhostGatewayRequest struct for ModelsResolveServerhostGatewayRequest
type ModelsResolveServerhostGatewayRequest struct {
	ServerhostId *string `json:"serverhost_id,omitempty"`
	Slug         *string `json:"slug,omitempty"`
}

// NewModelsResolveServerhostGatewayRequest instantiates a new ModelsResolveServerhostGatewayRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsResolveServerhostGatewayRequest() *ModelsResolveServerhostGatewayRequest {
	this := ModelsResolveServerhostGatewayRequest{}
	return &this
}

// NewModelsResolveServerhostGatewayRequestWithDefaults instantiates a new ModelsResolveServerhostGatewayRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsResolveServerhostGatewayRequestWithDefaults() *ModelsResolveServerhostGatewayRequest {
	this := ModelsResolveServerhostGatewayRequest{}
	return &this
}

// GetServerhostId returns the ServerhostId field value if set, zero value otherwise.
func (o *ModelsResolveServerhostGatewayRequest) GetServerhostId() string {
	if o == nil || IsNil(o.ServerhostId) {
		var ret string
		return ret
	}
	return *o.ServerhostId
}

// GetServerhostIdOk returns a tuple with the ServerhostId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsResolveServerhostGatewayRequest) GetServerhostIdOk() (*string, bool) {
	if o == nil || IsNil(o.ServerhostId) {
		return nil, false
	}
	return o.ServerhostId, true
}

// HasServerhostId returns a boolean if a field has been set.
func (o *ModelsResolveServerhostGatewayRequest) HasServerhostId() bool {
	if o != nil && !IsNil(o.ServerhostId) {
		return true
	}

	return false
}

// SetServerhostId gets a reference to the given string and assigns it to the ServerhostId field.
func (o *ModelsResolveServerhostGatewayRequest) SetServerhostId(v string) {
	o.ServerhostId = &v
}

// GetSlug returns the Slug field value if set, zero value otherwise.
func (o *ModelsResolveServerhostGatewayRequest) GetSlug() string {
	if o == nil || IsNil(o.Slug) {
		var ret string
		return ret
	}
	return *o.Slug
}

// GetSlugOk returns a tuple with the Slug field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsResolveServerhostGatewayRequest) GetSlugOk() (*string, bool) {
	if o == nil || IsNil(o.Slug) {
		return nil, false
	}
	return o.Slug, true
}

// HasSlug returns a boolean if a field has been set.
func (o *ModelsResolveServerhostGatewayRequest) HasSlug() bool {
	if o != nil && !IsNil(o.Slug) {
		return true
	}

	return false
}

// SetSlug gets a reference to the given string and assigns it to the Slug field.
func (o *ModelsResolveServerhostGatewayRequest) SetSlug(v string) {
	o.Slug = &v
}

func (o ModelsResolveServerhostGatewayRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsResolveServerhostGatewayRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ServerhostId) {
		toSerialize["serverhost_id"] = o.ServerhostId
	}
	if !IsNil(o.Slug) {
		toSerialize["slug"] = o.Slug
	}
	return toSerialize, nil
}

type NullableModelsResolveServerhostGatewayRequest struct {
	value *ModelsResolveServerhostGatewayRequest
	isSet bool
}

func (v NullableModelsResolveServerhostGatewayRequest) Get() *ModelsResolveServerhostGatewayRequest {
	return v.value
}

func (v *NullableModelsResolveServerhostGatewayRequest) Set(val *ModelsResolveServerhostGatewayRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsResolveServerhostGatewayRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsResolveServerhostGatewayRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsResolveServerhostGatewayRequest(val *ModelsResolveServerhostGatewayRequest) *NullableModelsResolveServerhostGatewayRequest {
	return &NullableModelsResolveServerhostGatewayRequest{value: val, isSet: true}
}

func (v NullableModelsResolveServerhostGatewayRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsResolveServerhostGatewayRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
