/*
SimpleCloud Controller API

API for SimpleCloud Controller

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplecloud

import (
	"encoding/json"
)

// checks if the ModelsPluginResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsPluginResponse{}

// ModelsPluginResponse struct for ModelsPluginResponse
type ModelsPluginResponse struct {
	CreatedAt   *string `json:"created_at,omitempty"`
	Id          *string `json:"id,omitempty"`
	McNetworkId *string `json:"mc_network_id,omitempty"`
	Name        *string `json:"name,omitempty"`
	SourceType  *string `json:"source_type,omitempty"`
	SourceValue *string `json:"source_value,omitempty"`
	UpdatedAt   *string `json:"updated_at,omitempty"`
}

// NewModelsPluginResponse instantiates a new ModelsPluginResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsPluginResponse() *ModelsPluginResponse {
	this := ModelsPluginResponse{}
	return &this
}

// NewModelsPluginResponseWithDefaults instantiates a new ModelsPluginResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsPluginResponseWithDefaults() *ModelsPluginResponse {
	this := ModelsPluginResponse{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ModelsPluginResponse) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsPluginResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ModelsPluginResponse) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *ModelsPluginResponse) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ModelsPluginResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsPluginResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ModelsPluginResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ModelsPluginResponse) SetId(v string) {
	o.Id = &v
}

// GetMcNetworkId returns the McNetworkId field value if set, zero value otherwise.
func (o *ModelsPluginResponse) GetMcNetworkId() string {
	if o == nil || IsNil(o.McNetworkId) {
		var ret string
		return ret
	}
	return *o.McNetworkId
}

// GetMcNetworkIdOk returns a tuple with the McNetworkId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsPluginResponse) GetMcNetworkIdOk() (*string, bool) {
	if o == nil || IsNil(o.McNetworkId) {
		return nil, false
	}
	return o.McNetworkId, true
}

// HasMcNetworkId returns a boolean if a field has been set.
func (o *ModelsPluginResponse) HasMcNetworkId() bool {
	if o != nil && !IsNil(o.McNetworkId) {
		return true
	}

	return false
}

// SetMcNetworkId gets a reference to the given string and assigns it to the McNetworkId field.
func (o *ModelsPluginResponse) SetMcNetworkId(v string) {
	o.McNetworkId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ModelsPluginResponse) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsPluginResponse) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ModelsPluginResponse) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ModelsPluginResponse) SetName(v string) {
	o.Name = &v
}

// GetSourceType returns the SourceType field value if set, zero value otherwise.
func (o *ModelsPluginResponse) GetSourceType() string {
	if o == nil || IsNil(o.SourceType) {
		var ret string
		return ret
	}
	return *o.SourceType
}

// GetSourceTypeOk returns a tuple with the SourceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsPluginResponse) GetSourceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.SourceType) {
		return nil, false
	}
	return o.SourceType, true
}

// HasSourceType returns a boolean if a field has been set.
func (o *ModelsPluginResponse) HasSourceType() bool {
	if o != nil && !IsNil(o.SourceType) {
		return true
	}

	return false
}

// SetSourceType gets a reference to the given string and assigns it to the SourceType field.
func (o *ModelsPluginResponse) SetSourceType(v string) {
	o.SourceType = &v
}

// GetSourceValue returns the SourceValue field value if set, zero value otherwise.
func (o *ModelsPluginResponse) GetSourceValue() string {
	if o == nil || IsNil(o.SourceValue) {
		var ret string
		return ret
	}
	return *o.SourceValue
}

// GetSourceValueOk returns a tuple with the SourceValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsPluginResponse) GetSourceValueOk() (*string, bool) {
	if o == nil || IsNil(o.SourceValue) {
		return nil, false
	}
	return o.SourceValue, true
}

// HasSourceValue returns a boolean if a field has been set.
func (o *ModelsPluginResponse) HasSourceValue() bool {
	if o != nil && !IsNil(o.SourceValue) {
		return true
	}

	return false
}

// SetSourceValue gets a reference to the given string and assigns it to the SourceValue field.
func (o *ModelsPluginResponse) SetSourceValue(v string) {
	o.SourceValue = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *ModelsPluginResponse) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsPluginResponse) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *ModelsPluginResponse) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *ModelsPluginResponse) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

func (o ModelsPluginResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsPluginResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.McNetworkId) {
		toSerialize["mc_network_id"] = o.McNetworkId
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.SourceType) {
		toSerialize["source_type"] = o.SourceType
	}
	if !IsNil(o.SourceValue) {
		toSerialize["source_value"] = o.SourceValue
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableModelsPluginResponse struct {
	value *ModelsPluginResponse
	isSet bool
}

func (v NullableModelsPluginResponse) Get() *ModelsPluginResponse {
	return v.value
}

func (v *NullableModelsPluginResponse) Set(val *ModelsPluginResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsPluginResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsPluginResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsPluginResponse(val *ModelsPluginResponse) *NullableModelsPluginResponse {
	return &NullableModelsPluginResponse{value: val, isSet: true}
}

func (v NullableModelsPluginResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsPluginResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
