/*
SimpleCloud Controller API

API for SimpleCloud Controller

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplecloud

import (
	"encoding/json"
)

// checks if the ModelsDeletePluginAssignmentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsDeletePluginAssignmentResponse{}

// ModelsDeletePluginAssignmentResponse struct for ModelsDeletePluginAssignmentResponse
type ModelsDeletePluginAssignmentResponse struct {
	AssignmentId *string `json:"assignment_id,omitempty"`
	Message      *string `json:"message,omitempty"`
}

// NewModelsDeletePluginAssignmentResponse instantiates a new ModelsDeletePluginAssignmentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsDeletePluginAssignmentResponse() *ModelsDeletePluginAssignmentResponse {
	this := ModelsDeletePluginAssignmentResponse{}
	return &this
}

// NewModelsDeletePluginAssignmentResponseWithDefaults instantiates a new ModelsDeletePluginAssignmentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsDeletePluginAssignmentResponseWithDefaults() *ModelsDeletePluginAssignmentResponse {
	this := ModelsDeletePluginAssignmentResponse{}
	return &this
}

// GetAssignmentId returns the AssignmentId field value if set, zero value otherwise.
func (o *ModelsDeletePluginAssignmentResponse) GetAssignmentId() string {
	if o == nil || IsNil(o.AssignmentId) {
		var ret string
		return ret
	}
	return *o.AssignmentId
}

// GetAssignmentIdOk returns a tuple with the AssignmentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsDeletePluginAssignmentResponse) GetAssignmentIdOk() (*string, bool) {
	if o == nil || IsNil(o.AssignmentId) {
		return nil, false
	}
	return o.AssignmentId, true
}

// HasAssignmentId returns a boolean if a field has been set.
func (o *ModelsDeletePluginAssignmentResponse) HasAssignmentId() bool {
	if o != nil && !IsNil(o.AssignmentId) {
		return true
	}

	return false
}

// SetAssignmentId gets a reference to the given string and assigns it to the AssignmentId field.
func (o *ModelsDeletePluginAssignmentResponse) SetAssignmentId(v string) {
	o.AssignmentId = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ModelsDeletePluginAssignmentResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsDeletePluginAssignmentResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ModelsDeletePluginAssignmentResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ModelsDeletePluginAssignmentResponse) SetMessage(v string) {
	o.Message = &v
}

func (o ModelsDeletePluginAssignmentResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsDeletePluginAssignmentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AssignmentId) {
		toSerialize["assignment_id"] = o.AssignmentId
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableModelsDeletePluginAssignmentResponse struct {
	value *ModelsDeletePluginAssignmentResponse
	isSet bool
}

func (v NullableModelsDeletePluginAssignmentResponse) Get() *ModelsDeletePluginAssignmentResponse {
	return v.value
}

func (v *NullableModelsDeletePluginAssignmentResponse) Set(val *ModelsDeletePluginAssignmentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsDeletePluginAssignmentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsDeletePluginAssignmentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsDeletePluginAssignmentResponse(val *ModelsDeletePluginAssignmentResponse) *NullableModelsDeletePluginAssignmentResponse {
	return &NullableModelsDeletePluginAssignmentResponse{value: val, isSet: true}
}

func (v NullableModelsDeletePluginAssignmentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsDeletePluginAssignmentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
