/*
SimpleCloud Controller API

API for SimpleCloud Controller

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplecloud

import (
	"encoding/json"
)

// checks if the ModelsExecutePersistentServerWorkflowResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsExecutePersistentServerWorkflowResponse{}

// ModelsExecutePersistentServerWorkflowResponse Response for executing a manual workflow on all eligible servers of a persistent server.
type ModelsExecutePersistentServerWorkflowResponse struct {
	FailedServers      []ModelsExecuteManualWorkflowFailure `json:"failed_servers,omitempty"`
	Message            *string                              `json:"message,omitempty"`
	PersistentServerId *string                              `json:"persistent_server_id,omitempty"`
	SkippedServerIds   []string                             `json:"skipped_server_ids,omitempty"`
	SucceededServerIds []string                             `json:"succeeded_server_ids,omitempty"`
	TotalServers       *int32                               `json:"total_servers,omitempty"`
	WorkflowId         *string                              `json:"workflow_id,omitempty"`
}

// NewModelsExecutePersistentServerWorkflowResponse instantiates a new ModelsExecutePersistentServerWorkflowResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsExecutePersistentServerWorkflowResponse() *ModelsExecutePersistentServerWorkflowResponse {
	this := ModelsExecutePersistentServerWorkflowResponse{}
	return &this
}

// NewModelsExecutePersistentServerWorkflowResponseWithDefaults instantiates a new ModelsExecutePersistentServerWorkflowResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsExecutePersistentServerWorkflowResponseWithDefaults() *ModelsExecutePersistentServerWorkflowResponse {
	this := ModelsExecutePersistentServerWorkflowResponse{}
	return &this
}

// GetFailedServers returns the FailedServers field value if set, zero value otherwise.
func (o *ModelsExecutePersistentServerWorkflowResponse) GetFailedServers() []ModelsExecuteManualWorkflowFailure {
	if o == nil || IsNil(o.FailedServers) {
		var ret []ModelsExecuteManualWorkflowFailure
		return ret
	}
	return o.FailedServers
}

// GetFailedServersOk returns a tuple with the FailedServers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsExecutePersistentServerWorkflowResponse) GetFailedServersOk() ([]ModelsExecuteManualWorkflowFailure, bool) {
	if o == nil || IsNil(o.FailedServers) {
		return nil, false
	}
	return o.FailedServers, true
}

// HasFailedServers returns a boolean if a field has been set.
func (o *ModelsExecutePersistentServerWorkflowResponse) HasFailedServers() bool {
	if o != nil && !IsNil(o.FailedServers) {
		return true
	}

	return false
}

// SetFailedServers gets a reference to the given []ModelsExecuteManualWorkflowFailure and assigns it to the FailedServers field.
func (o *ModelsExecutePersistentServerWorkflowResponse) SetFailedServers(v []ModelsExecuteManualWorkflowFailure) {
	o.FailedServers = v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ModelsExecutePersistentServerWorkflowResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsExecutePersistentServerWorkflowResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ModelsExecutePersistentServerWorkflowResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ModelsExecutePersistentServerWorkflowResponse) SetMessage(v string) {
	o.Message = &v
}

// GetPersistentServerId returns the PersistentServerId field value if set, zero value otherwise.
func (o *ModelsExecutePersistentServerWorkflowResponse) GetPersistentServerId() string {
	if o == nil || IsNil(o.PersistentServerId) {
		var ret string
		return ret
	}
	return *o.PersistentServerId
}

// GetPersistentServerIdOk returns a tuple with the PersistentServerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsExecutePersistentServerWorkflowResponse) GetPersistentServerIdOk() (*string, bool) {
	if o == nil || IsNil(o.PersistentServerId) {
		return nil, false
	}
	return o.PersistentServerId, true
}

// HasPersistentServerId returns a boolean if a field has been set.
func (o *ModelsExecutePersistentServerWorkflowResponse) HasPersistentServerId() bool {
	if o != nil && !IsNil(o.PersistentServerId) {
		return true
	}

	return false
}

// SetPersistentServerId gets a reference to the given string and assigns it to the PersistentServerId field.
func (o *ModelsExecutePersistentServerWorkflowResponse) SetPersistentServerId(v string) {
	o.PersistentServerId = &v
}

// GetSkippedServerIds returns the SkippedServerIds field value if set, zero value otherwise.
func (o *ModelsExecutePersistentServerWorkflowResponse) GetSkippedServerIds() []string {
	if o == nil || IsNil(o.SkippedServerIds) {
		var ret []string
		return ret
	}
	return o.SkippedServerIds
}

// GetSkippedServerIdsOk returns a tuple with the SkippedServerIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsExecutePersistentServerWorkflowResponse) GetSkippedServerIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.SkippedServerIds) {
		return nil, false
	}
	return o.SkippedServerIds, true
}

// HasSkippedServerIds returns a boolean if a field has been set.
func (o *ModelsExecutePersistentServerWorkflowResponse) HasSkippedServerIds() bool {
	if o != nil && !IsNil(o.SkippedServerIds) {
		return true
	}

	return false
}

// SetSkippedServerIds gets a reference to the given []string and assigns it to the SkippedServerIds field.
func (o *ModelsExecutePersistentServerWorkflowResponse) SetSkippedServerIds(v []string) {
	o.SkippedServerIds = v
}

// GetSucceededServerIds returns the SucceededServerIds field value if set, zero value otherwise.
func (o *ModelsExecutePersistentServerWorkflowResponse) GetSucceededServerIds() []string {
	if o == nil || IsNil(o.SucceededServerIds) {
		var ret []string
		return ret
	}
	return o.SucceededServerIds
}

// GetSucceededServerIdsOk returns a tuple with the SucceededServerIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsExecutePersistentServerWorkflowResponse) GetSucceededServerIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.SucceededServerIds) {
		return nil, false
	}
	return o.SucceededServerIds, true
}

// HasSucceededServerIds returns a boolean if a field has been set.
func (o *ModelsExecutePersistentServerWorkflowResponse) HasSucceededServerIds() bool {
	if o != nil && !IsNil(o.SucceededServerIds) {
		return true
	}

	return false
}

// SetSucceededServerIds gets a reference to the given []string and assigns it to the SucceededServerIds field.
func (o *ModelsExecutePersistentServerWorkflowResponse) SetSucceededServerIds(v []string) {
	o.SucceededServerIds = v
}

// GetTotalServers returns the TotalServers field value if set, zero value otherwise.
func (o *ModelsExecutePersistentServerWorkflowResponse) GetTotalServers() int32 {
	if o == nil || IsNil(o.TotalServers) {
		var ret int32
		return ret
	}
	return *o.TotalServers
}

// GetTotalServersOk returns a tuple with the TotalServers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsExecutePersistentServerWorkflowResponse) GetTotalServersOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalServers) {
		return nil, false
	}
	return o.TotalServers, true
}

// HasTotalServers returns a boolean if a field has been set.
func (o *ModelsExecutePersistentServerWorkflowResponse) HasTotalServers() bool {
	if o != nil && !IsNil(o.TotalServers) {
		return true
	}

	return false
}

// SetTotalServers gets a reference to the given int32 and assigns it to the TotalServers field.
func (o *ModelsExecutePersistentServerWorkflowResponse) SetTotalServers(v int32) {
	o.TotalServers = &v
}

// GetWorkflowId returns the WorkflowId field value if set, zero value otherwise.
func (o *ModelsExecutePersistentServerWorkflowResponse) GetWorkflowId() string {
	if o == nil || IsNil(o.WorkflowId) {
		var ret string
		return ret
	}
	return *o.WorkflowId
}

// GetWorkflowIdOk returns a tuple with the WorkflowId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsExecutePersistentServerWorkflowResponse) GetWorkflowIdOk() (*string, bool) {
	if o == nil || IsNil(o.WorkflowId) {
		return nil, false
	}
	return o.WorkflowId, true
}

// HasWorkflowId returns a boolean if a field has been set.
func (o *ModelsExecutePersistentServerWorkflowResponse) HasWorkflowId() bool {
	if o != nil && !IsNil(o.WorkflowId) {
		return true
	}

	return false
}

// SetWorkflowId gets a reference to the given string and assigns it to the WorkflowId field.
func (o *ModelsExecutePersistentServerWorkflowResponse) SetWorkflowId(v string) {
	o.WorkflowId = &v
}

func (o ModelsExecutePersistentServerWorkflowResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsExecutePersistentServerWorkflowResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FailedServers) {
		toSerialize["failed_servers"] = o.FailedServers
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.PersistentServerId) {
		toSerialize["persistent_server_id"] = o.PersistentServerId
	}
	if !IsNil(o.SkippedServerIds) {
		toSerialize["skipped_server_ids"] = o.SkippedServerIds
	}
	if !IsNil(o.SucceededServerIds) {
		toSerialize["succeeded_server_ids"] = o.SucceededServerIds
	}
	if !IsNil(o.TotalServers) {
		toSerialize["total_servers"] = o.TotalServers
	}
	if !IsNil(o.WorkflowId) {
		toSerialize["workflow_id"] = o.WorkflowId
	}
	return toSerialize, nil
}

type NullableModelsExecutePersistentServerWorkflowResponse struct {
	value *ModelsExecutePersistentServerWorkflowResponse
	isSet bool
}

func (v NullableModelsExecutePersistentServerWorkflowResponse) Get() *ModelsExecutePersistentServerWorkflowResponse {
	return v.value
}

func (v *NullableModelsExecutePersistentServerWorkflowResponse) Set(val *ModelsExecutePersistentServerWorkflowResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsExecutePersistentServerWorkflowResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsExecutePersistentServerWorkflowResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsExecutePersistentServerWorkflowResponse(val *ModelsExecutePersistentServerWorkflowResponse) *NullableModelsExecutePersistentServerWorkflowResponse {
	return &NullableModelsExecutePersistentServerWorkflowResponse{value: val, isSet: true}
}

func (v NullableModelsExecutePersistentServerWorkflowResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsExecutePersistentServerWorkflowResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
