/*
SimpleCloud Controller API

API for SimpleCloud Controller

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplecloud

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ModelsUpdatePluginRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsUpdatePluginRequest{}

// ModelsUpdatePluginRequest struct for ModelsUpdatePluginRequest
type ModelsUpdatePluginRequest struct {
	Name        string `json:"name"`
	SourceType  string `json:"source_type"`
	SourceValue string `json:"source_value"`
}

type _ModelsUpdatePluginRequest ModelsUpdatePluginRequest

// NewModelsUpdatePluginRequest instantiates a new ModelsUpdatePluginRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsUpdatePluginRequest(name string, sourceType string, sourceValue string) *ModelsUpdatePluginRequest {
	this := ModelsUpdatePluginRequest{}
	this.Name = name
	this.SourceType = sourceType
	this.SourceValue = sourceValue
	return &this
}

// NewModelsUpdatePluginRequestWithDefaults instantiates a new ModelsUpdatePluginRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsUpdatePluginRequestWithDefaults() *ModelsUpdatePluginRequest {
	this := ModelsUpdatePluginRequest{}
	return &this
}

// GetName returns the Name field value
func (o *ModelsUpdatePluginRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ModelsUpdatePluginRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ModelsUpdatePluginRequest) SetName(v string) {
	o.Name = v
}

// GetSourceType returns the SourceType field value
func (o *ModelsUpdatePluginRequest) GetSourceType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceType
}

// GetSourceTypeOk returns a tuple with the SourceType field value
// and a boolean to check if the value has been set.
func (o *ModelsUpdatePluginRequest) GetSourceTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceType, true
}

// SetSourceType sets field value
func (o *ModelsUpdatePluginRequest) SetSourceType(v string) {
	o.SourceType = v
}

// GetSourceValue returns the SourceValue field value
func (o *ModelsUpdatePluginRequest) GetSourceValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceValue
}

// GetSourceValueOk returns a tuple with the SourceValue field value
// and a boolean to check if the value has been set.
func (o *ModelsUpdatePluginRequest) GetSourceValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceValue, true
}

// SetSourceValue sets field value
func (o *ModelsUpdatePluginRequest) SetSourceValue(v string) {
	o.SourceValue = v
}

func (o ModelsUpdatePluginRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsUpdatePluginRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["source_type"] = o.SourceType
	toSerialize["source_value"] = o.SourceValue
	return toSerialize, nil
}

func (o *ModelsUpdatePluginRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"source_type",
		"source_value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varModelsUpdatePluginRequest := _ModelsUpdatePluginRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varModelsUpdatePluginRequest)

	if err != nil {
		return err
	}

	*o = ModelsUpdatePluginRequest(varModelsUpdatePluginRequest)

	return err
}

type NullableModelsUpdatePluginRequest struct {
	value *ModelsUpdatePluginRequest
	isSet bool
}

func (v NullableModelsUpdatePluginRequest) Get() *ModelsUpdatePluginRequest {
	return v.value
}

func (v *NullableModelsUpdatePluginRequest) Set(val *ModelsUpdatePluginRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsUpdatePluginRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsUpdatePluginRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsUpdatePluginRequest(val *ModelsUpdatePluginRequest) *NullableModelsUpdatePluginRequest {
	return &NullableModelsUpdatePluginRequest{value: val, isSet: true}
}

func (v NullableModelsUpdatePluginRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsUpdatePluginRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
