/*
SimpleCloud Controller API

API for SimpleCloud Controller

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplecloud

import (
	"encoding/json"
)

// checks if the ModelsUpdateClientSettingsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsUpdateClientSettingsResponse{}

// ModelsUpdateClientSettingsResponse Response for updating client settings
type ModelsUpdateClientSettingsResponse struct {
	Message  *string                             `json:"message,omitempty"`
	Settings *ModelsPlayerClientSettingsResponse `json:"settings,omitempty"`
	Success  *bool                               `json:"success,omitempty"`
}

// NewModelsUpdateClientSettingsResponse instantiates a new ModelsUpdateClientSettingsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsUpdateClientSettingsResponse() *ModelsUpdateClientSettingsResponse {
	this := ModelsUpdateClientSettingsResponse{}
	return &this
}

// NewModelsUpdateClientSettingsResponseWithDefaults instantiates a new ModelsUpdateClientSettingsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsUpdateClientSettingsResponseWithDefaults() *ModelsUpdateClientSettingsResponse {
	this := ModelsUpdateClientSettingsResponse{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ModelsUpdateClientSettingsResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsUpdateClientSettingsResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ModelsUpdateClientSettingsResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ModelsUpdateClientSettingsResponse) SetMessage(v string) {
	o.Message = &v
}

// GetSettings returns the Settings field value if set, zero value otherwise.
func (o *ModelsUpdateClientSettingsResponse) GetSettings() ModelsPlayerClientSettingsResponse {
	if o == nil || IsNil(o.Settings) {
		var ret ModelsPlayerClientSettingsResponse
		return ret
	}
	return *o.Settings
}

// GetSettingsOk returns a tuple with the Settings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsUpdateClientSettingsResponse) GetSettingsOk() (*ModelsPlayerClientSettingsResponse, bool) {
	if o == nil || IsNil(o.Settings) {
		return nil, false
	}
	return o.Settings, true
}

// HasSettings returns a boolean if a field has been set.
func (o *ModelsUpdateClientSettingsResponse) HasSettings() bool {
	if o != nil && !IsNil(o.Settings) {
		return true
	}

	return false
}

// SetSettings gets a reference to the given ModelsPlayerClientSettingsResponse and assigns it to the Settings field.
func (o *ModelsUpdateClientSettingsResponse) SetSettings(v ModelsPlayerClientSettingsResponse) {
	o.Settings = &v
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *ModelsUpdateClientSettingsResponse) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsUpdateClientSettingsResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *ModelsUpdateClientSettingsResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *ModelsUpdateClientSettingsResponse) SetSuccess(v bool) {
	o.Success = &v
}

func (o ModelsUpdateClientSettingsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsUpdateClientSettingsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Settings) {
		toSerialize["settings"] = o.Settings
	}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	return toSerialize, nil
}

type NullableModelsUpdateClientSettingsResponse struct {
	value *ModelsUpdateClientSettingsResponse
	isSet bool
}

func (v NullableModelsUpdateClientSettingsResponse) Get() *ModelsUpdateClientSettingsResponse {
	return v.value
}

func (v *NullableModelsUpdateClientSettingsResponse) Set(val *ModelsUpdateClientSettingsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsUpdateClientSettingsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsUpdateClientSettingsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsUpdateClientSettingsResponse(val *ModelsUpdateClientSettingsResponse) *NullableModelsUpdateClientSettingsResponse {
	return &NullableModelsUpdateClientSettingsResponse{value: val, isSet: true}
}

func (v NullableModelsUpdateClientSettingsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsUpdateClientSettingsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
