/*
SimpleCloud Controller API

API for SimpleCloud Controller

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplecloud

import (
	"encoding/json"
)

// checks if the ModelsDeactivateServerhostResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsDeactivateServerhostResponse{}

// ModelsDeactivateServerhostResponse Response for serverhost deactivation operation
type ModelsDeactivateServerhostResponse struct {
	Deactivated   *bool   `json:"deactivated,omitempty"`
	DeactivatedAt *string `json:"deactivated_at,omitempty"`
	HostName      *string `json:"host_name,omitempty"`
	Message       *string `json:"message,omitempty"`
	ServerhostId  *string `json:"serverhost_id,omitempty"`
}

// NewModelsDeactivateServerhostResponse instantiates a new ModelsDeactivateServerhostResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsDeactivateServerhostResponse() *ModelsDeactivateServerhostResponse {
	this := ModelsDeactivateServerhostResponse{}
	return &this
}

// NewModelsDeactivateServerhostResponseWithDefaults instantiates a new ModelsDeactivateServerhostResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsDeactivateServerhostResponseWithDefaults() *ModelsDeactivateServerhostResponse {
	this := ModelsDeactivateServerhostResponse{}
	return &this
}

// GetDeactivated returns the Deactivated field value if set, zero value otherwise.
func (o *ModelsDeactivateServerhostResponse) GetDeactivated() bool {
	if o == nil || IsNil(o.Deactivated) {
		var ret bool
		return ret
	}
	return *o.Deactivated
}

// GetDeactivatedOk returns a tuple with the Deactivated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsDeactivateServerhostResponse) GetDeactivatedOk() (*bool, bool) {
	if o == nil || IsNil(o.Deactivated) {
		return nil, false
	}
	return o.Deactivated, true
}

// HasDeactivated returns a boolean if a field has been set.
func (o *ModelsDeactivateServerhostResponse) HasDeactivated() bool {
	if o != nil && !IsNil(o.Deactivated) {
		return true
	}

	return false
}

// SetDeactivated gets a reference to the given bool and assigns it to the Deactivated field.
func (o *ModelsDeactivateServerhostResponse) SetDeactivated(v bool) {
	o.Deactivated = &v
}

// GetDeactivatedAt returns the DeactivatedAt field value if set, zero value otherwise.
func (o *ModelsDeactivateServerhostResponse) GetDeactivatedAt() string {
	if o == nil || IsNil(o.DeactivatedAt) {
		var ret string
		return ret
	}
	return *o.DeactivatedAt
}

// GetDeactivatedAtOk returns a tuple with the DeactivatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsDeactivateServerhostResponse) GetDeactivatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.DeactivatedAt) {
		return nil, false
	}
	return o.DeactivatedAt, true
}

// HasDeactivatedAt returns a boolean if a field has been set.
func (o *ModelsDeactivateServerhostResponse) HasDeactivatedAt() bool {
	if o != nil && !IsNil(o.DeactivatedAt) {
		return true
	}

	return false
}

// SetDeactivatedAt gets a reference to the given string and assigns it to the DeactivatedAt field.
func (o *ModelsDeactivateServerhostResponse) SetDeactivatedAt(v string) {
	o.DeactivatedAt = &v
}

// GetHostName returns the HostName field value if set, zero value otherwise.
func (o *ModelsDeactivateServerhostResponse) GetHostName() string {
	if o == nil || IsNil(o.HostName) {
		var ret string
		return ret
	}
	return *o.HostName
}

// GetHostNameOk returns a tuple with the HostName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsDeactivateServerhostResponse) GetHostNameOk() (*string, bool) {
	if o == nil || IsNil(o.HostName) {
		return nil, false
	}
	return o.HostName, true
}

// HasHostName returns a boolean if a field has been set.
func (o *ModelsDeactivateServerhostResponse) HasHostName() bool {
	if o != nil && !IsNil(o.HostName) {
		return true
	}

	return false
}

// SetHostName gets a reference to the given string and assigns it to the HostName field.
func (o *ModelsDeactivateServerhostResponse) SetHostName(v string) {
	o.HostName = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ModelsDeactivateServerhostResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsDeactivateServerhostResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ModelsDeactivateServerhostResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ModelsDeactivateServerhostResponse) SetMessage(v string) {
	o.Message = &v
}

// GetServerhostId returns the ServerhostId field value if set, zero value otherwise.
func (o *ModelsDeactivateServerhostResponse) GetServerhostId() string {
	if o == nil || IsNil(o.ServerhostId) {
		var ret string
		return ret
	}
	return *o.ServerhostId
}

// GetServerhostIdOk returns a tuple with the ServerhostId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsDeactivateServerhostResponse) GetServerhostIdOk() (*string, bool) {
	if o == nil || IsNil(o.ServerhostId) {
		return nil, false
	}
	return o.ServerhostId, true
}

// HasServerhostId returns a boolean if a field has been set.
func (o *ModelsDeactivateServerhostResponse) HasServerhostId() bool {
	if o != nil && !IsNil(o.ServerhostId) {
		return true
	}

	return false
}

// SetServerhostId gets a reference to the given string and assigns it to the ServerhostId field.
func (o *ModelsDeactivateServerhostResponse) SetServerhostId(v string) {
	o.ServerhostId = &v
}

func (o ModelsDeactivateServerhostResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsDeactivateServerhostResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Deactivated) {
		toSerialize["deactivated"] = o.Deactivated
	}
	if !IsNil(o.DeactivatedAt) {
		toSerialize["deactivated_at"] = o.DeactivatedAt
	}
	if !IsNil(o.HostName) {
		toSerialize["host_name"] = o.HostName
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.ServerhostId) {
		toSerialize["serverhost_id"] = o.ServerhostId
	}
	return toSerialize, nil
}

type NullableModelsDeactivateServerhostResponse struct {
	value *ModelsDeactivateServerhostResponse
	isSet bool
}

func (v NullableModelsDeactivateServerhostResponse) Get() *ModelsDeactivateServerhostResponse {
	return v.value
}

func (v *NullableModelsDeactivateServerhostResponse) Set(val *ModelsDeactivateServerhostResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsDeactivateServerhostResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsDeactivateServerhostResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsDeactivateServerhostResponse(val *ModelsDeactivateServerhostResponse) *NullableModelsDeactivateServerhostResponse {
	return &NullableModelsDeactivateServerhostResponse{value: val, isSet: true}
}

func (v NullableModelsDeactivateServerhostResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsDeactivateServerhostResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
