/*
SimpleCloud Controller API

API for SimpleCloud Controller

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplecloud

import (
	"encoding/json"
)

// checks if the ModelsUpdateServerGroupRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsUpdateServerGroupRequest{}

// ModelsUpdateServerGroupRequest Request to update an existing server group
type ModelsUpdateServerGroupRequest struct {
	Active     *bool                   `json:"active,omitempty"`
	Deployment *ModelsDeploymentConfig `json:"deployment,omitempty"`
	MaxMemory  *int32                  `json:"max_memory,omitempty"`
	MaxPlayers *int32                  `json:"max_players,omitempty"`
	MinMemory  *int32                  `json:"min_memory,omitempty"`
	Name       *string                 `json:"name,omitempty"`
	Priority   *int32                  `json:"priority,omitempty"`
	Properties map[string]interface{}  `json:"properties,omitempty"`
	Scaling    *ModelsScalingConfig    `json:"scaling,omitempty"`
	Source     *ModelsSourceConfig     `json:"source,omitempty"`
	Tags       []string                `json:"tags,omitempty"`
	Type       *string                 `json:"type,omitempty"`
	Workflows  *ModelsWorkflowsConfig  `json:"workflows,omitempty"`
}

// NewModelsUpdateServerGroupRequest instantiates a new ModelsUpdateServerGroupRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsUpdateServerGroupRequest() *ModelsUpdateServerGroupRequest {
	this := ModelsUpdateServerGroupRequest{}
	return &this
}

// NewModelsUpdateServerGroupRequestWithDefaults instantiates a new ModelsUpdateServerGroupRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsUpdateServerGroupRequestWithDefaults() *ModelsUpdateServerGroupRequest {
	this := ModelsUpdateServerGroupRequest{}
	return &this
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *ModelsUpdateServerGroupRequest) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsUpdateServerGroupRequest) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *ModelsUpdateServerGroupRequest) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *ModelsUpdateServerGroupRequest) SetActive(v bool) {
	o.Active = &v
}

// GetDeployment returns the Deployment field value if set, zero value otherwise.
func (o *ModelsUpdateServerGroupRequest) GetDeployment() ModelsDeploymentConfig {
	if o == nil || IsNil(o.Deployment) {
		var ret ModelsDeploymentConfig
		return ret
	}
	return *o.Deployment
}

// GetDeploymentOk returns a tuple with the Deployment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsUpdateServerGroupRequest) GetDeploymentOk() (*ModelsDeploymentConfig, bool) {
	if o == nil || IsNil(o.Deployment) {
		return nil, false
	}
	return o.Deployment, true
}

// HasDeployment returns a boolean if a field has been set.
func (o *ModelsUpdateServerGroupRequest) HasDeployment() bool {
	if o != nil && !IsNil(o.Deployment) {
		return true
	}

	return false
}

// SetDeployment gets a reference to the given ModelsDeploymentConfig and assigns it to the Deployment field.
func (o *ModelsUpdateServerGroupRequest) SetDeployment(v ModelsDeploymentConfig) {
	o.Deployment = &v
}

// GetMaxMemory returns the MaxMemory field value if set, zero value otherwise.
func (o *ModelsUpdateServerGroupRequest) GetMaxMemory() int32 {
	if o == nil || IsNil(o.MaxMemory) {
		var ret int32
		return ret
	}
	return *o.MaxMemory
}

// GetMaxMemoryOk returns a tuple with the MaxMemory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsUpdateServerGroupRequest) GetMaxMemoryOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxMemory) {
		return nil, false
	}
	return o.MaxMemory, true
}

// HasMaxMemory returns a boolean if a field has been set.
func (o *ModelsUpdateServerGroupRequest) HasMaxMemory() bool {
	if o != nil && !IsNil(o.MaxMemory) {
		return true
	}

	return false
}

// SetMaxMemory gets a reference to the given int32 and assigns it to the MaxMemory field.
func (o *ModelsUpdateServerGroupRequest) SetMaxMemory(v int32) {
	o.MaxMemory = &v
}

// GetMaxPlayers returns the MaxPlayers field value if set, zero value otherwise.
func (o *ModelsUpdateServerGroupRequest) GetMaxPlayers() int32 {
	if o == nil || IsNil(o.MaxPlayers) {
		var ret int32
		return ret
	}
	return *o.MaxPlayers
}

// GetMaxPlayersOk returns a tuple with the MaxPlayers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsUpdateServerGroupRequest) GetMaxPlayersOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxPlayers) {
		return nil, false
	}
	return o.MaxPlayers, true
}

// HasMaxPlayers returns a boolean if a field has been set.
func (o *ModelsUpdateServerGroupRequest) HasMaxPlayers() bool {
	if o != nil && !IsNil(o.MaxPlayers) {
		return true
	}

	return false
}

// SetMaxPlayers gets a reference to the given int32 and assigns it to the MaxPlayers field.
func (o *ModelsUpdateServerGroupRequest) SetMaxPlayers(v int32) {
	o.MaxPlayers = &v
}

// GetMinMemory returns the MinMemory field value if set, zero value otherwise.
func (o *ModelsUpdateServerGroupRequest) GetMinMemory() int32 {
	if o == nil || IsNil(o.MinMemory) {
		var ret int32
		return ret
	}
	return *o.MinMemory
}

// GetMinMemoryOk returns a tuple with the MinMemory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsUpdateServerGroupRequest) GetMinMemoryOk() (*int32, bool) {
	if o == nil || IsNil(o.MinMemory) {
		return nil, false
	}
	return o.MinMemory, true
}

// HasMinMemory returns a boolean if a field has been set.
func (o *ModelsUpdateServerGroupRequest) HasMinMemory() bool {
	if o != nil && !IsNil(o.MinMemory) {
		return true
	}

	return false
}

// SetMinMemory gets a reference to the given int32 and assigns it to the MinMemory field.
func (o *ModelsUpdateServerGroupRequest) SetMinMemory(v int32) {
	o.MinMemory = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ModelsUpdateServerGroupRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsUpdateServerGroupRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ModelsUpdateServerGroupRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ModelsUpdateServerGroupRequest) SetName(v string) {
	o.Name = &v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *ModelsUpdateServerGroupRequest) GetPriority() int32 {
	if o == nil || IsNil(o.Priority) {
		var ret int32
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsUpdateServerGroupRequest) GetPriorityOk() (*int32, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *ModelsUpdateServerGroupRequest) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given int32 and assigns it to the Priority field.
func (o *ModelsUpdateServerGroupRequest) SetPriority(v int32) {
	o.Priority = &v
}

// GetProperties returns the Properties field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelsUpdateServerGroupRequest) GetProperties() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelsUpdateServerGroupRequest) GetPropertiesOk() (*map[string]interface{}, bool) {
	if o == nil || IsNil(o.Properties) {
		return nil, false
	}
	return &o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *ModelsUpdateServerGroupRequest) HasProperties() bool {
	if o != nil && !IsNil(o.Properties) {
		return true
	}

	return false
}

// SetProperties gets a reference to the given map[string]interface{} and assigns it to the Properties field.
func (o *ModelsUpdateServerGroupRequest) SetProperties(v map[string]interface{}) {
	o.Properties = v
}

// GetScaling returns the Scaling field value if set, zero value otherwise.
func (o *ModelsUpdateServerGroupRequest) GetScaling() ModelsScalingConfig {
	if o == nil || IsNil(o.Scaling) {
		var ret ModelsScalingConfig
		return ret
	}
	return *o.Scaling
}

// GetScalingOk returns a tuple with the Scaling field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsUpdateServerGroupRequest) GetScalingOk() (*ModelsScalingConfig, bool) {
	if o == nil || IsNil(o.Scaling) {
		return nil, false
	}
	return o.Scaling, true
}

// HasScaling returns a boolean if a field has been set.
func (o *ModelsUpdateServerGroupRequest) HasScaling() bool {
	if o != nil && !IsNil(o.Scaling) {
		return true
	}

	return false
}

// SetScaling gets a reference to the given ModelsScalingConfig and assigns it to the Scaling field.
func (o *ModelsUpdateServerGroupRequest) SetScaling(v ModelsScalingConfig) {
	o.Scaling = &v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *ModelsUpdateServerGroupRequest) GetSource() ModelsSourceConfig {
	if o == nil || IsNil(o.Source) {
		var ret ModelsSourceConfig
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsUpdateServerGroupRequest) GetSourceOk() (*ModelsSourceConfig, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *ModelsUpdateServerGroupRequest) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given ModelsSourceConfig and assigns it to the Source field.
func (o *ModelsUpdateServerGroupRequest) SetSource(v ModelsSourceConfig) {
	o.Source = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *ModelsUpdateServerGroupRequest) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsUpdateServerGroupRequest) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *ModelsUpdateServerGroupRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *ModelsUpdateServerGroupRequest) SetTags(v []string) {
	o.Tags = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ModelsUpdateServerGroupRequest) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsUpdateServerGroupRequest) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ModelsUpdateServerGroupRequest) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ModelsUpdateServerGroupRequest) SetType(v string) {
	o.Type = &v
}

// GetWorkflows returns the Workflows field value if set, zero value otherwise.
func (o *ModelsUpdateServerGroupRequest) GetWorkflows() ModelsWorkflowsConfig {
	if o == nil || IsNil(o.Workflows) {
		var ret ModelsWorkflowsConfig
		return ret
	}
	return *o.Workflows
}

// GetWorkflowsOk returns a tuple with the Workflows field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsUpdateServerGroupRequest) GetWorkflowsOk() (*ModelsWorkflowsConfig, bool) {
	if o == nil || IsNil(o.Workflows) {
		return nil, false
	}
	return o.Workflows, true
}

// HasWorkflows returns a boolean if a field has been set.
func (o *ModelsUpdateServerGroupRequest) HasWorkflows() bool {
	if o != nil && !IsNil(o.Workflows) {
		return true
	}

	return false
}

// SetWorkflows gets a reference to the given ModelsWorkflowsConfig and assigns it to the Workflows field.
func (o *ModelsUpdateServerGroupRequest) SetWorkflows(v ModelsWorkflowsConfig) {
	o.Workflows = &v
}

func (o ModelsUpdateServerGroupRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsUpdateServerGroupRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	if !IsNil(o.Deployment) {
		toSerialize["deployment"] = o.Deployment
	}
	if !IsNil(o.MaxMemory) {
		toSerialize["max_memory"] = o.MaxMemory
	}
	if !IsNil(o.MaxPlayers) {
		toSerialize["max_players"] = o.MaxPlayers
	}
	if !IsNil(o.MinMemory) {
		toSerialize["min_memory"] = o.MinMemory
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}
	if o.Properties != nil {
		toSerialize["properties"] = o.Properties
	}
	if !IsNil(o.Scaling) {
		toSerialize["scaling"] = o.Scaling
	}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Workflows) {
		toSerialize["workflows"] = o.Workflows
	}
	return toSerialize, nil
}

type NullableModelsUpdateServerGroupRequest struct {
	value *ModelsUpdateServerGroupRequest
	isSet bool
}

func (v NullableModelsUpdateServerGroupRequest) Get() *ModelsUpdateServerGroupRequest {
	return v.value
}

func (v *NullableModelsUpdateServerGroupRequest) Set(val *ModelsUpdateServerGroupRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsUpdateServerGroupRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsUpdateServerGroupRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsUpdateServerGroupRequest(val *ModelsUpdateServerGroupRequest) *NullableModelsUpdateServerGroupRequest {
	return &NullableModelsUpdateServerGroupRequest{value: val, isSet: true}
}

func (v NullableModelsUpdateServerGroupRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsUpdateServerGroupRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
