/*
SimpleCloud Controller API

API for SimpleCloud Controller

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplecloud

import (
	"encoding/json"
)

// checks if the ModelsUpdateNetworkResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsUpdateNetworkResponse{}

// ModelsUpdateNetworkResponse Response for updating a network
type ModelsUpdateNetworkResponse struct {
	Message     *string `json:"message,omitempty"`
	NetworkId   *string `json:"network_id,omitempty"`
	NetworkName *string `json:"network_name,omitempty"`
}

// NewModelsUpdateNetworkResponse instantiates a new ModelsUpdateNetworkResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsUpdateNetworkResponse() *ModelsUpdateNetworkResponse {
	this := ModelsUpdateNetworkResponse{}
	return &this
}

// NewModelsUpdateNetworkResponseWithDefaults instantiates a new ModelsUpdateNetworkResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsUpdateNetworkResponseWithDefaults() *ModelsUpdateNetworkResponse {
	this := ModelsUpdateNetworkResponse{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ModelsUpdateNetworkResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsUpdateNetworkResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ModelsUpdateNetworkResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ModelsUpdateNetworkResponse) SetMessage(v string) {
	o.Message = &v
}

// GetNetworkId returns the NetworkId field value if set, zero value otherwise.
func (o *ModelsUpdateNetworkResponse) GetNetworkId() string {
	if o == nil || IsNil(o.NetworkId) {
		var ret string
		return ret
	}
	return *o.NetworkId
}

// GetNetworkIdOk returns a tuple with the NetworkId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsUpdateNetworkResponse) GetNetworkIdOk() (*string, bool) {
	if o == nil || IsNil(o.NetworkId) {
		return nil, false
	}
	return o.NetworkId, true
}

// HasNetworkId returns a boolean if a field has been set.
func (o *ModelsUpdateNetworkResponse) HasNetworkId() bool {
	if o != nil && !IsNil(o.NetworkId) {
		return true
	}

	return false
}

// SetNetworkId gets a reference to the given string and assigns it to the NetworkId field.
func (o *ModelsUpdateNetworkResponse) SetNetworkId(v string) {
	o.NetworkId = &v
}

// GetNetworkName returns the NetworkName field value if set, zero value otherwise.
func (o *ModelsUpdateNetworkResponse) GetNetworkName() string {
	if o == nil || IsNil(o.NetworkName) {
		var ret string
		return ret
	}
	return *o.NetworkName
}

// GetNetworkNameOk returns a tuple with the NetworkName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsUpdateNetworkResponse) GetNetworkNameOk() (*string, bool) {
	if o == nil || IsNil(o.NetworkName) {
		return nil, false
	}
	return o.NetworkName, true
}

// HasNetworkName returns a boolean if a field has been set.
func (o *ModelsUpdateNetworkResponse) HasNetworkName() bool {
	if o != nil && !IsNil(o.NetworkName) {
		return true
	}

	return false
}

// SetNetworkName gets a reference to the given string and assigns it to the NetworkName field.
func (o *ModelsUpdateNetworkResponse) SetNetworkName(v string) {
	o.NetworkName = &v
}

func (o ModelsUpdateNetworkResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsUpdateNetworkResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.NetworkId) {
		toSerialize["network_id"] = o.NetworkId
	}
	if !IsNil(o.NetworkName) {
		toSerialize["network_name"] = o.NetworkName
	}
	return toSerialize, nil
}

type NullableModelsUpdateNetworkResponse struct {
	value *ModelsUpdateNetworkResponse
	isSet bool
}

func (v NullableModelsUpdateNetworkResponse) Get() *ModelsUpdateNetworkResponse {
	return v.value
}

func (v *NullableModelsUpdateNetworkResponse) Set(val *ModelsUpdateNetworkResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsUpdateNetworkResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsUpdateNetworkResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsUpdateNetworkResponse(val *ModelsUpdateNetworkResponse) *NullableModelsUpdateNetworkResponse {
	return &NullableModelsUpdateNetworkResponse{value: val, isSet: true}
}

func (v NullableModelsUpdateNetworkResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsUpdateNetworkResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
