/*
SimpleCloud Controller API

API for SimpleCloud Controller

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplecloud

import (
	"encoding/json"
)

// checks if the ModelsDeletePlayerPropertiesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsDeletePlayerPropertiesRequest{}

// ModelsDeletePlayerPropertiesRequest Request to delete player property keys
type ModelsDeletePlayerPropertiesRequest struct {
	Keys []string `json:"keys,omitempty"`
}

// NewModelsDeletePlayerPropertiesRequest instantiates a new ModelsDeletePlayerPropertiesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsDeletePlayerPropertiesRequest() *ModelsDeletePlayerPropertiesRequest {
	this := ModelsDeletePlayerPropertiesRequest{}
	return &this
}

// NewModelsDeletePlayerPropertiesRequestWithDefaults instantiates a new ModelsDeletePlayerPropertiesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsDeletePlayerPropertiesRequestWithDefaults() *ModelsDeletePlayerPropertiesRequest {
	this := ModelsDeletePlayerPropertiesRequest{}
	return &this
}

// GetKeys returns the Keys field value if set, zero value otherwise.
func (o *ModelsDeletePlayerPropertiesRequest) GetKeys() []string {
	if o == nil || IsNil(o.Keys) {
		var ret []string
		return ret
	}
	return o.Keys
}

// GetKeysOk returns a tuple with the Keys field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsDeletePlayerPropertiesRequest) GetKeysOk() ([]string, bool) {
	if o == nil || IsNil(o.Keys) {
		return nil, false
	}
	return o.Keys, true
}

// HasKeys returns a boolean if a field has been set.
func (o *ModelsDeletePlayerPropertiesRequest) HasKeys() bool {
	if o != nil && !IsNil(o.Keys) {
		return true
	}

	return false
}

// SetKeys gets a reference to the given []string and assigns it to the Keys field.
func (o *ModelsDeletePlayerPropertiesRequest) SetKeys(v []string) {
	o.Keys = v
}

func (o ModelsDeletePlayerPropertiesRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsDeletePlayerPropertiesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Keys) {
		toSerialize["keys"] = o.Keys
	}
	return toSerialize, nil
}

type NullableModelsDeletePlayerPropertiesRequest struct {
	value *ModelsDeletePlayerPropertiesRequest
	isSet bool
}

func (v NullableModelsDeletePlayerPropertiesRequest) Get() *ModelsDeletePlayerPropertiesRequest {
	return v.value
}

func (v *NullableModelsDeletePlayerPropertiesRequest) Set(val *ModelsDeletePlayerPropertiesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsDeletePlayerPropertiesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsDeletePlayerPropertiesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsDeletePlayerPropertiesRequest(val *ModelsDeletePlayerPropertiesRequest) *NullableModelsDeletePlayerPropertiesRequest {
	return &NullableModelsDeletePlayerPropertiesRequest{value: val, isSet: true}
}

func (v NullableModelsDeletePlayerPropertiesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsDeletePlayerPropertiesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
