/*
SimpleCloud Controller API

API for SimpleCloud Controller

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplecloud

import (
	"encoding/json"
)

// checks if the ModelsListSecretsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsListSecretsResponse{}

// ModelsListSecretsResponse Response for listing stored network secrets
type ModelsListSecretsResponse struct {
	Count   *int32                `json:"count,omitempty"`
	Secrets []ModelsSecretSummary `json:"secrets,omitempty"`
}

// NewModelsListSecretsResponse instantiates a new ModelsListSecretsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsListSecretsResponse() *ModelsListSecretsResponse {
	this := ModelsListSecretsResponse{}
	return &this
}

// NewModelsListSecretsResponseWithDefaults instantiates a new ModelsListSecretsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsListSecretsResponseWithDefaults() *ModelsListSecretsResponse {
	this := ModelsListSecretsResponse{}
	return &this
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *ModelsListSecretsResponse) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsListSecretsResponse) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *ModelsListSecretsResponse) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *ModelsListSecretsResponse) SetCount(v int32) {
	o.Count = &v
}

// GetSecrets returns the Secrets field value if set, zero value otherwise.
func (o *ModelsListSecretsResponse) GetSecrets() []ModelsSecretSummary {
	if o == nil || IsNil(o.Secrets) {
		var ret []ModelsSecretSummary
		return ret
	}
	return o.Secrets
}

// GetSecretsOk returns a tuple with the Secrets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsListSecretsResponse) GetSecretsOk() ([]ModelsSecretSummary, bool) {
	if o == nil || IsNil(o.Secrets) {
		return nil, false
	}
	return o.Secrets, true
}

// HasSecrets returns a boolean if a field has been set.
func (o *ModelsListSecretsResponse) HasSecrets() bool {
	if o != nil && !IsNil(o.Secrets) {
		return true
	}

	return false
}

// SetSecrets gets a reference to the given []ModelsSecretSummary and assigns it to the Secrets field.
func (o *ModelsListSecretsResponse) SetSecrets(v []ModelsSecretSummary) {
	o.Secrets = v
}

func (o ModelsListSecretsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsListSecretsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !IsNil(o.Secrets) {
		toSerialize["secrets"] = o.Secrets
	}
	return toSerialize, nil
}

type NullableModelsListSecretsResponse struct {
	value *ModelsListSecretsResponse
	isSet bool
}

func (v NullableModelsListSecretsResponse) Get() *ModelsListSecretsResponse {
	return v.value
}

func (v *NullableModelsListSecretsResponse) Set(val *ModelsListSecretsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsListSecretsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsListSecretsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsListSecretsResponse(val *ModelsListSecretsResponse) *NullableModelsListSecretsResponse {
	return &NullableModelsListSecretsResponse{value: val, isSet: true}
}

func (v NullableModelsListSecretsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsListSecretsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
