/*
SimpleCloud Controller API

API for SimpleCloud Controller

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplecloud

import (
	"encoding/json"
)

// checks if the ModelsVerifyNetworkRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsVerifyNetworkRequest{}

// ModelsVerifyNetworkRequest Request for network verification
type ModelsVerifyNetworkRequest struct {
	NetworkId       *string `json:"network_id,omitempty"`
	NetworkPassword *string `json:"network_password,omitempty"`
	// Deprecated: use network_password.
	NetworkSecret *string `json:"network_secret,omitempty"`
}

// NewModelsVerifyNetworkRequest instantiates a new ModelsVerifyNetworkRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsVerifyNetworkRequest() *ModelsVerifyNetworkRequest {
	this := ModelsVerifyNetworkRequest{}
	return &this
}

// NewModelsVerifyNetworkRequestWithDefaults instantiates a new ModelsVerifyNetworkRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsVerifyNetworkRequestWithDefaults() *ModelsVerifyNetworkRequest {
	this := ModelsVerifyNetworkRequest{}
	return &this
}

// GetNetworkId returns the NetworkId field value if set, zero value otherwise.
func (o *ModelsVerifyNetworkRequest) GetNetworkId() string {
	if o == nil || IsNil(o.NetworkId) {
		var ret string
		return ret
	}
	return *o.NetworkId
}

// GetNetworkIdOk returns a tuple with the NetworkId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsVerifyNetworkRequest) GetNetworkIdOk() (*string, bool) {
	if o == nil || IsNil(o.NetworkId) {
		return nil, false
	}
	return o.NetworkId, true
}

// HasNetworkId returns a boolean if a field has been set.
func (o *ModelsVerifyNetworkRequest) HasNetworkId() bool {
	if o != nil && !IsNil(o.NetworkId) {
		return true
	}

	return false
}

// SetNetworkId gets a reference to the given string and assigns it to the NetworkId field.
func (o *ModelsVerifyNetworkRequest) SetNetworkId(v string) {
	o.NetworkId = &v
}

// GetNetworkPassword returns the NetworkPassword field value if set, zero value otherwise.
func (o *ModelsVerifyNetworkRequest) GetNetworkPassword() string {
	if o == nil || IsNil(o.NetworkPassword) {
		var ret string
		return ret
	}
	return *o.NetworkPassword
}

// GetNetworkPasswordOk returns a tuple with the NetworkPassword field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsVerifyNetworkRequest) GetNetworkPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.NetworkPassword) {
		return nil, false
	}
	return o.NetworkPassword, true
}

// HasNetworkPassword returns a boolean if a field has been set.
func (o *ModelsVerifyNetworkRequest) HasNetworkPassword() bool {
	if o != nil && !IsNil(o.NetworkPassword) {
		return true
	}

	return false
}

// SetNetworkPassword gets a reference to the given string and assigns it to the NetworkPassword field.
func (o *ModelsVerifyNetworkRequest) SetNetworkPassword(v string) {
	o.NetworkPassword = &v
}

// GetNetworkSecret returns the NetworkSecret field value if set, zero value otherwise.
func (o *ModelsVerifyNetworkRequest) GetNetworkSecret() string {
	if o == nil || IsNil(o.NetworkSecret) {
		var ret string
		return ret
	}
	return *o.NetworkSecret
}

// GetNetworkSecretOk returns a tuple with the NetworkSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsVerifyNetworkRequest) GetNetworkSecretOk() (*string, bool) {
	if o == nil || IsNil(o.NetworkSecret) {
		return nil, false
	}
	return o.NetworkSecret, true
}

// HasNetworkSecret returns a boolean if a field has been set.
func (o *ModelsVerifyNetworkRequest) HasNetworkSecret() bool {
	if o != nil && !IsNil(o.NetworkSecret) {
		return true
	}

	return false
}

// SetNetworkSecret gets a reference to the given string and assigns it to the NetworkSecret field.
func (o *ModelsVerifyNetworkRequest) SetNetworkSecret(v string) {
	o.NetworkSecret = &v
}

func (o ModelsVerifyNetworkRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsVerifyNetworkRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NetworkId) {
		toSerialize["network_id"] = o.NetworkId
	}
	if !IsNil(o.NetworkPassword) {
		toSerialize["network_password"] = o.NetworkPassword
	}
	if !IsNil(o.NetworkSecret) {
		toSerialize["network_secret"] = o.NetworkSecret
	}
	return toSerialize, nil
}

type NullableModelsVerifyNetworkRequest struct {
	value *ModelsVerifyNetworkRequest
	isSet bool
}

func (v NullableModelsVerifyNetworkRequest) Get() *ModelsVerifyNetworkRequest {
	return v.value
}

func (v *NullableModelsVerifyNetworkRequest) Set(val *ModelsVerifyNetworkRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsVerifyNetworkRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsVerifyNetworkRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsVerifyNetworkRequest(val *ModelsVerifyNetworkRequest) *NullableModelsVerifyNetworkRequest {
	return &NullableModelsVerifyNetworkRequest{value: val, isSet: true}
}

func (v NullableModelsVerifyNetworkRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsVerifyNetworkRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
