/*
SimpleCloud Controller API

API for SimpleCloud Controller

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplecloud

import (
	"encoding/json"
)

// checks if the ModelsLogsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsLogsResponse{}

// ModelsLogsResponse struct for ModelsLogsResponse
type ModelsLogsResponse struct {
	Cursor  *string          `json:"cursor,omitempty"`
	HasMore *bool            `json:"has_more,omitempty"`
	Logs    []ModelsLogEntry `json:"logs,omitempty"`
}

// NewModelsLogsResponse instantiates a new ModelsLogsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsLogsResponse() *ModelsLogsResponse {
	this := ModelsLogsResponse{}
	return &this
}

// NewModelsLogsResponseWithDefaults instantiates a new ModelsLogsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsLogsResponseWithDefaults() *ModelsLogsResponse {
	this := ModelsLogsResponse{}
	return &this
}

// GetCursor returns the Cursor field value if set, zero value otherwise.
func (o *ModelsLogsResponse) GetCursor() string {
	if o == nil || IsNil(o.Cursor) {
		var ret string
		return ret
	}
	return *o.Cursor
}

// GetCursorOk returns a tuple with the Cursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsLogsResponse) GetCursorOk() (*string, bool) {
	if o == nil || IsNil(o.Cursor) {
		return nil, false
	}
	return o.Cursor, true
}

// HasCursor returns a boolean if a field has been set.
func (o *ModelsLogsResponse) HasCursor() bool {
	if o != nil && !IsNil(o.Cursor) {
		return true
	}

	return false
}

// SetCursor gets a reference to the given string and assigns it to the Cursor field.
func (o *ModelsLogsResponse) SetCursor(v string) {
	o.Cursor = &v
}

// GetHasMore returns the HasMore field value if set, zero value otherwise.
func (o *ModelsLogsResponse) GetHasMore() bool {
	if o == nil || IsNil(o.HasMore) {
		var ret bool
		return ret
	}
	return *o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsLogsResponse) GetHasMoreOk() (*bool, bool) {
	if o == nil || IsNil(o.HasMore) {
		return nil, false
	}
	return o.HasMore, true
}

// HasHasMore returns a boolean if a field has been set.
func (o *ModelsLogsResponse) HasHasMore() bool {
	if o != nil && !IsNil(o.HasMore) {
		return true
	}

	return false
}

// SetHasMore gets a reference to the given bool and assigns it to the HasMore field.
func (o *ModelsLogsResponse) SetHasMore(v bool) {
	o.HasMore = &v
}

// GetLogs returns the Logs field value if set, zero value otherwise.
func (o *ModelsLogsResponse) GetLogs() []ModelsLogEntry {
	if o == nil || IsNil(o.Logs) {
		var ret []ModelsLogEntry
		return ret
	}
	return o.Logs
}

// GetLogsOk returns a tuple with the Logs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsLogsResponse) GetLogsOk() ([]ModelsLogEntry, bool) {
	if o == nil || IsNil(o.Logs) {
		return nil, false
	}
	return o.Logs, true
}

// HasLogs returns a boolean if a field has been set.
func (o *ModelsLogsResponse) HasLogs() bool {
	if o != nil && !IsNil(o.Logs) {
		return true
	}

	return false
}

// SetLogs gets a reference to the given []ModelsLogEntry and assigns it to the Logs field.
func (o *ModelsLogsResponse) SetLogs(v []ModelsLogEntry) {
	o.Logs = v
}

func (o ModelsLogsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsLogsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Cursor) {
		toSerialize["cursor"] = o.Cursor
	}
	if !IsNil(o.HasMore) {
		toSerialize["has_more"] = o.HasMore
	}
	if !IsNil(o.Logs) {
		toSerialize["logs"] = o.Logs
	}
	return toSerialize, nil
}

type NullableModelsLogsResponse struct {
	value *ModelsLogsResponse
	isSet bool
}

func (v NullableModelsLogsResponse) Get() *ModelsLogsResponse {
	return v.value
}

func (v *NullableModelsLogsResponse) Set(val *ModelsLogsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsLogsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsLogsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsLogsResponse(val *ModelsLogsResponse) *NullableModelsLogsResponse {
	return &NullableModelsLogsResponse{value: val, isSet: true}
}

func (v NullableModelsLogsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsLogsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
