/*
SimpleCloud Controller API

API for SimpleCloud Controller

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplecloud

import (
	"encoding/json"
)

// checks if the ModelsClearServerGroupStartQueueResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsClearServerGroupStartQueueResponse{}

// ModelsClearServerGroupStartQueueResponse Response for clearing queued starts for a server group
type ModelsClearServerGroupStartQueueResponse struct {
	Message         *string `json:"message,omitempty"`
	ServerGroupId   *string `json:"server_group_id,omitempty"`
	ServerGroupName *string `json:"server_group_name,omitempty"`
}

// NewModelsClearServerGroupStartQueueResponse instantiates a new ModelsClearServerGroupStartQueueResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsClearServerGroupStartQueueResponse() *ModelsClearServerGroupStartQueueResponse {
	this := ModelsClearServerGroupStartQueueResponse{}
	return &this
}

// NewModelsClearServerGroupStartQueueResponseWithDefaults instantiates a new ModelsClearServerGroupStartQueueResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsClearServerGroupStartQueueResponseWithDefaults() *ModelsClearServerGroupStartQueueResponse {
	this := ModelsClearServerGroupStartQueueResponse{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ModelsClearServerGroupStartQueueResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsClearServerGroupStartQueueResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ModelsClearServerGroupStartQueueResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ModelsClearServerGroupStartQueueResponse) SetMessage(v string) {
	o.Message = &v
}

// GetServerGroupId returns the ServerGroupId field value if set, zero value otherwise.
func (o *ModelsClearServerGroupStartQueueResponse) GetServerGroupId() string {
	if o == nil || IsNil(o.ServerGroupId) {
		var ret string
		return ret
	}
	return *o.ServerGroupId
}

// GetServerGroupIdOk returns a tuple with the ServerGroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsClearServerGroupStartQueueResponse) GetServerGroupIdOk() (*string, bool) {
	if o == nil || IsNil(o.ServerGroupId) {
		return nil, false
	}
	return o.ServerGroupId, true
}

// HasServerGroupId returns a boolean if a field has been set.
func (o *ModelsClearServerGroupStartQueueResponse) HasServerGroupId() bool {
	if o != nil && !IsNil(o.ServerGroupId) {
		return true
	}

	return false
}

// SetServerGroupId gets a reference to the given string and assigns it to the ServerGroupId field.
func (o *ModelsClearServerGroupStartQueueResponse) SetServerGroupId(v string) {
	o.ServerGroupId = &v
}

// GetServerGroupName returns the ServerGroupName field value if set, zero value otherwise.
func (o *ModelsClearServerGroupStartQueueResponse) GetServerGroupName() string {
	if o == nil || IsNil(o.ServerGroupName) {
		var ret string
		return ret
	}
	return *o.ServerGroupName
}

// GetServerGroupNameOk returns a tuple with the ServerGroupName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsClearServerGroupStartQueueResponse) GetServerGroupNameOk() (*string, bool) {
	if o == nil || IsNil(o.ServerGroupName) {
		return nil, false
	}
	return o.ServerGroupName, true
}

// HasServerGroupName returns a boolean if a field has been set.
func (o *ModelsClearServerGroupStartQueueResponse) HasServerGroupName() bool {
	if o != nil && !IsNil(o.ServerGroupName) {
		return true
	}

	return false
}

// SetServerGroupName gets a reference to the given string and assigns it to the ServerGroupName field.
func (o *ModelsClearServerGroupStartQueueResponse) SetServerGroupName(v string) {
	o.ServerGroupName = &v
}

func (o ModelsClearServerGroupStartQueueResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsClearServerGroupStartQueueResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.ServerGroupId) {
		toSerialize["server_group_id"] = o.ServerGroupId
	}
	if !IsNil(o.ServerGroupName) {
		toSerialize["server_group_name"] = o.ServerGroupName
	}
	return toSerialize, nil
}

type NullableModelsClearServerGroupStartQueueResponse struct {
	value *ModelsClearServerGroupStartQueueResponse
	isSet bool
}

func (v NullableModelsClearServerGroupStartQueueResponse) Get() *ModelsClearServerGroupStartQueueResponse {
	return v.value
}

func (v *NullableModelsClearServerGroupStartQueueResponse) Set(val *ModelsClearServerGroupStartQueueResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsClearServerGroupStartQueueResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsClearServerGroupStartQueueResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsClearServerGroupStartQueueResponse(val *ModelsClearServerGroupStartQueueResponse) *NullableModelsClearServerGroupStartQueueResponse {
	return &NullableModelsClearServerGroupStartQueueResponse{value: val, isSet: true}
}

func (v NullableModelsClearServerGroupStartQueueResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsClearServerGroupStartQueueResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
