/*
SimpleCloud Controller API

API for SimpleCloud Controller

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplecloud

import (
	"encoding/json"
)

// checks if the ModelsDeletePlayerPropertiesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsDeletePlayerPropertiesResponse{}

// ModelsDeletePlayerPropertiesResponse Response for deleting player properties
type ModelsDeletePlayerPropertiesResponse struct {
	Message  *string `json:"message,omitempty"`
	PlayerId *string `json:"player_id,omitempty"`
}

// NewModelsDeletePlayerPropertiesResponse instantiates a new ModelsDeletePlayerPropertiesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsDeletePlayerPropertiesResponse() *ModelsDeletePlayerPropertiesResponse {
	this := ModelsDeletePlayerPropertiesResponse{}
	return &this
}

// NewModelsDeletePlayerPropertiesResponseWithDefaults instantiates a new ModelsDeletePlayerPropertiesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsDeletePlayerPropertiesResponseWithDefaults() *ModelsDeletePlayerPropertiesResponse {
	this := ModelsDeletePlayerPropertiesResponse{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ModelsDeletePlayerPropertiesResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsDeletePlayerPropertiesResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ModelsDeletePlayerPropertiesResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ModelsDeletePlayerPropertiesResponse) SetMessage(v string) {
	o.Message = &v
}

// GetPlayerId returns the PlayerId field value if set, zero value otherwise.
func (o *ModelsDeletePlayerPropertiesResponse) GetPlayerId() string {
	if o == nil || IsNil(o.PlayerId) {
		var ret string
		return ret
	}
	return *o.PlayerId
}

// GetPlayerIdOk returns a tuple with the PlayerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsDeletePlayerPropertiesResponse) GetPlayerIdOk() (*string, bool) {
	if o == nil || IsNil(o.PlayerId) {
		return nil, false
	}
	return o.PlayerId, true
}

// HasPlayerId returns a boolean if a field has been set.
func (o *ModelsDeletePlayerPropertiesResponse) HasPlayerId() bool {
	if o != nil && !IsNil(o.PlayerId) {
		return true
	}

	return false
}

// SetPlayerId gets a reference to the given string and assigns it to the PlayerId field.
func (o *ModelsDeletePlayerPropertiesResponse) SetPlayerId(v string) {
	o.PlayerId = &v
}

func (o ModelsDeletePlayerPropertiesResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsDeletePlayerPropertiesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.PlayerId) {
		toSerialize["player_id"] = o.PlayerId
	}
	return toSerialize, nil
}

type NullableModelsDeletePlayerPropertiesResponse struct {
	value *ModelsDeletePlayerPropertiesResponse
	isSet bool
}

func (v NullableModelsDeletePlayerPropertiesResponse) Get() *ModelsDeletePlayerPropertiesResponse {
	return v.value
}

func (v *NullableModelsDeletePlayerPropertiesResponse) Set(val *ModelsDeletePlayerPropertiesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsDeletePlayerPropertiesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsDeletePlayerPropertiesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsDeletePlayerPropertiesResponse(val *ModelsDeletePlayerPropertiesResponse) *NullableModelsDeletePlayerPropertiesResponse {
	return &NullableModelsDeletePlayerPropertiesResponse{value: val, isSet: true}
}

func (v NullableModelsDeletePlayerPropertiesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsDeletePlayerPropertiesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
