/*
SimpleCloud Controller API

API for SimpleCloud Controller

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplecloud

import (
	"encoding/json"
)

// checks if the ModelsPluginCollectionAssignmentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsPluginCollectionAssignmentResponse{}

// ModelsPluginCollectionAssignmentResponse struct for ModelsPluginCollectionAssignmentResponse
type ModelsPluginCollectionAssignmentResponse struct {
	CreatedAt            *string `json:"created_at,omitempty"`
	Id                   *string `json:"id,omitempty"`
	McNetworkId          *string `json:"mc_network_id,omitempty"`
	PersistentServerId   *string `json:"persistent_server_id,omitempty"`
	PluginCollectionId   *string `json:"plugin_collection_id,omitempty"`
	PluginCollectionName *string `json:"plugin_collection_name,omitempty"`
	ServerGroupId        *string `json:"server_group_id,omitempty"`
	UpdatedAt            *string `json:"updated_at,omitempty"`
}

// NewModelsPluginCollectionAssignmentResponse instantiates a new ModelsPluginCollectionAssignmentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsPluginCollectionAssignmentResponse() *ModelsPluginCollectionAssignmentResponse {
	this := ModelsPluginCollectionAssignmentResponse{}
	return &this
}

// NewModelsPluginCollectionAssignmentResponseWithDefaults instantiates a new ModelsPluginCollectionAssignmentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsPluginCollectionAssignmentResponseWithDefaults() *ModelsPluginCollectionAssignmentResponse {
	this := ModelsPluginCollectionAssignmentResponse{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ModelsPluginCollectionAssignmentResponse) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsPluginCollectionAssignmentResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ModelsPluginCollectionAssignmentResponse) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *ModelsPluginCollectionAssignmentResponse) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ModelsPluginCollectionAssignmentResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsPluginCollectionAssignmentResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ModelsPluginCollectionAssignmentResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ModelsPluginCollectionAssignmentResponse) SetId(v string) {
	o.Id = &v
}

// GetMcNetworkId returns the McNetworkId field value if set, zero value otherwise.
func (o *ModelsPluginCollectionAssignmentResponse) GetMcNetworkId() string {
	if o == nil || IsNil(o.McNetworkId) {
		var ret string
		return ret
	}
	return *o.McNetworkId
}

// GetMcNetworkIdOk returns a tuple with the McNetworkId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsPluginCollectionAssignmentResponse) GetMcNetworkIdOk() (*string, bool) {
	if o == nil || IsNil(o.McNetworkId) {
		return nil, false
	}
	return o.McNetworkId, true
}

// HasMcNetworkId returns a boolean if a field has been set.
func (o *ModelsPluginCollectionAssignmentResponse) HasMcNetworkId() bool {
	if o != nil && !IsNil(o.McNetworkId) {
		return true
	}

	return false
}

// SetMcNetworkId gets a reference to the given string and assigns it to the McNetworkId field.
func (o *ModelsPluginCollectionAssignmentResponse) SetMcNetworkId(v string) {
	o.McNetworkId = &v
}

// GetPersistentServerId returns the PersistentServerId field value if set, zero value otherwise.
func (o *ModelsPluginCollectionAssignmentResponse) GetPersistentServerId() string {
	if o == nil || IsNil(o.PersistentServerId) {
		var ret string
		return ret
	}
	return *o.PersistentServerId
}

// GetPersistentServerIdOk returns a tuple with the PersistentServerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsPluginCollectionAssignmentResponse) GetPersistentServerIdOk() (*string, bool) {
	if o == nil || IsNil(o.PersistentServerId) {
		return nil, false
	}
	return o.PersistentServerId, true
}

// HasPersistentServerId returns a boolean if a field has been set.
func (o *ModelsPluginCollectionAssignmentResponse) HasPersistentServerId() bool {
	if o != nil && !IsNil(o.PersistentServerId) {
		return true
	}

	return false
}

// SetPersistentServerId gets a reference to the given string and assigns it to the PersistentServerId field.
func (o *ModelsPluginCollectionAssignmentResponse) SetPersistentServerId(v string) {
	o.PersistentServerId = &v
}

// GetPluginCollectionId returns the PluginCollectionId field value if set, zero value otherwise.
func (o *ModelsPluginCollectionAssignmentResponse) GetPluginCollectionId() string {
	if o == nil || IsNil(o.PluginCollectionId) {
		var ret string
		return ret
	}
	return *o.PluginCollectionId
}

// GetPluginCollectionIdOk returns a tuple with the PluginCollectionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsPluginCollectionAssignmentResponse) GetPluginCollectionIdOk() (*string, bool) {
	if o == nil || IsNil(o.PluginCollectionId) {
		return nil, false
	}
	return o.PluginCollectionId, true
}

// HasPluginCollectionId returns a boolean if a field has been set.
func (o *ModelsPluginCollectionAssignmentResponse) HasPluginCollectionId() bool {
	if o != nil && !IsNil(o.PluginCollectionId) {
		return true
	}

	return false
}

// SetPluginCollectionId gets a reference to the given string and assigns it to the PluginCollectionId field.
func (o *ModelsPluginCollectionAssignmentResponse) SetPluginCollectionId(v string) {
	o.PluginCollectionId = &v
}

// GetPluginCollectionName returns the PluginCollectionName field value if set, zero value otherwise.
func (o *ModelsPluginCollectionAssignmentResponse) GetPluginCollectionName() string {
	if o == nil || IsNil(o.PluginCollectionName) {
		var ret string
		return ret
	}
	return *o.PluginCollectionName
}

// GetPluginCollectionNameOk returns a tuple with the PluginCollectionName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsPluginCollectionAssignmentResponse) GetPluginCollectionNameOk() (*string, bool) {
	if o == nil || IsNil(o.PluginCollectionName) {
		return nil, false
	}
	return o.PluginCollectionName, true
}

// HasPluginCollectionName returns a boolean if a field has been set.
func (o *ModelsPluginCollectionAssignmentResponse) HasPluginCollectionName() bool {
	if o != nil && !IsNil(o.PluginCollectionName) {
		return true
	}

	return false
}

// SetPluginCollectionName gets a reference to the given string and assigns it to the PluginCollectionName field.
func (o *ModelsPluginCollectionAssignmentResponse) SetPluginCollectionName(v string) {
	o.PluginCollectionName = &v
}

// GetServerGroupId returns the ServerGroupId field value if set, zero value otherwise.
func (o *ModelsPluginCollectionAssignmentResponse) GetServerGroupId() string {
	if o == nil || IsNil(o.ServerGroupId) {
		var ret string
		return ret
	}
	return *o.ServerGroupId
}

// GetServerGroupIdOk returns a tuple with the ServerGroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsPluginCollectionAssignmentResponse) GetServerGroupIdOk() (*string, bool) {
	if o == nil || IsNil(o.ServerGroupId) {
		return nil, false
	}
	return o.ServerGroupId, true
}

// HasServerGroupId returns a boolean if a field has been set.
func (o *ModelsPluginCollectionAssignmentResponse) HasServerGroupId() bool {
	if o != nil && !IsNil(o.ServerGroupId) {
		return true
	}

	return false
}

// SetServerGroupId gets a reference to the given string and assigns it to the ServerGroupId field.
func (o *ModelsPluginCollectionAssignmentResponse) SetServerGroupId(v string) {
	o.ServerGroupId = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *ModelsPluginCollectionAssignmentResponse) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsPluginCollectionAssignmentResponse) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *ModelsPluginCollectionAssignmentResponse) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *ModelsPluginCollectionAssignmentResponse) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

func (o ModelsPluginCollectionAssignmentResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsPluginCollectionAssignmentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.McNetworkId) {
		toSerialize["mc_network_id"] = o.McNetworkId
	}
	if !IsNil(o.PersistentServerId) {
		toSerialize["persistent_server_id"] = o.PersistentServerId
	}
	if !IsNil(o.PluginCollectionId) {
		toSerialize["plugin_collection_id"] = o.PluginCollectionId
	}
	if !IsNil(o.PluginCollectionName) {
		toSerialize["plugin_collection_name"] = o.PluginCollectionName
	}
	if !IsNil(o.ServerGroupId) {
		toSerialize["server_group_id"] = o.ServerGroupId
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableModelsPluginCollectionAssignmentResponse struct {
	value *ModelsPluginCollectionAssignmentResponse
	isSet bool
}

func (v NullableModelsPluginCollectionAssignmentResponse) Get() *ModelsPluginCollectionAssignmentResponse {
	return v.value
}

func (v *NullableModelsPluginCollectionAssignmentResponse) Set(val *ModelsPluginCollectionAssignmentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsPluginCollectionAssignmentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsPluginCollectionAssignmentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsPluginCollectionAssignmentResponse(val *ModelsPluginCollectionAssignmentResponse) *NullableModelsPluginCollectionAssignmentResponse {
	return &NullableModelsPluginCollectionAssignmentResponse{value: val, isSet: true}
}

func (v NullableModelsPluginCollectionAssignmentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsPluginCollectionAssignmentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
