/*
SimpleCloud Controller API

API for SimpleCloud Controller

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplecloud

import (
	"encoding/json"
)

// checks if the ModelsResourceStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsResourceStats{}

// ModelsResourceStats struct for ModelsResourceStats
type ModelsResourceStats struct {
	AverageCpuPercent *float32 `json:"average_cpu_percent,omitempty"`
	MemoryAllocatedMb *int32   `json:"memory_allocated_mb,omitempty"`
	MemoryUsedMb      *float32 `json:"memory_used_mb,omitempty"`
}

// NewModelsResourceStats instantiates a new ModelsResourceStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsResourceStats() *ModelsResourceStats {
	this := ModelsResourceStats{}
	return &this
}

// NewModelsResourceStatsWithDefaults instantiates a new ModelsResourceStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsResourceStatsWithDefaults() *ModelsResourceStats {
	this := ModelsResourceStats{}
	return &this
}

// GetAverageCpuPercent returns the AverageCpuPercent field value if set, zero value otherwise.
func (o *ModelsResourceStats) GetAverageCpuPercent() float32 {
	if o == nil || IsNil(o.AverageCpuPercent) {
		var ret float32
		return ret
	}
	return *o.AverageCpuPercent
}

// GetAverageCpuPercentOk returns a tuple with the AverageCpuPercent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsResourceStats) GetAverageCpuPercentOk() (*float32, bool) {
	if o == nil || IsNil(o.AverageCpuPercent) {
		return nil, false
	}
	return o.AverageCpuPercent, true
}

// HasAverageCpuPercent returns a boolean if a field has been set.
func (o *ModelsResourceStats) HasAverageCpuPercent() bool {
	if o != nil && !IsNil(o.AverageCpuPercent) {
		return true
	}

	return false
}

// SetAverageCpuPercent gets a reference to the given float32 and assigns it to the AverageCpuPercent field.
func (o *ModelsResourceStats) SetAverageCpuPercent(v float32) {
	o.AverageCpuPercent = &v
}

// GetMemoryAllocatedMb returns the MemoryAllocatedMb field value if set, zero value otherwise.
func (o *ModelsResourceStats) GetMemoryAllocatedMb() int32 {
	if o == nil || IsNil(o.MemoryAllocatedMb) {
		var ret int32
		return ret
	}
	return *o.MemoryAllocatedMb
}

// GetMemoryAllocatedMbOk returns a tuple with the MemoryAllocatedMb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsResourceStats) GetMemoryAllocatedMbOk() (*int32, bool) {
	if o == nil || IsNil(o.MemoryAllocatedMb) {
		return nil, false
	}
	return o.MemoryAllocatedMb, true
}

// HasMemoryAllocatedMb returns a boolean if a field has been set.
func (o *ModelsResourceStats) HasMemoryAllocatedMb() bool {
	if o != nil && !IsNil(o.MemoryAllocatedMb) {
		return true
	}

	return false
}

// SetMemoryAllocatedMb gets a reference to the given int32 and assigns it to the MemoryAllocatedMb field.
func (o *ModelsResourceStats) SetMemoryAllocatedMb(v int32) {
	o.MemoryAllocatedMb = &v
}

// GetMemoryUsedMb returns the MemoryUsedMb field value if set, zero value otherwise.
func (o *ModelsResourceStats) GetMemoryUsedMb() float32 {
	if o == nil || IsNil(o.MemoryUsedMb) {
		var ret float32
		return ret
	}
	return *o.MemoryUsedMb
}

// GetMemoryUsedMbOk returns a tuple with the MemoryUsedMb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsResourceStats) GetMemoryUsedMbOk() (*float32, bool) {
	if o == nil || IsNil(o.MemoryUsedMb) {
		return nil, false
	}
	return o.MemoryUsedMb, true
}

// HasMemoryUsedMb returns a boolean if a field has been set.
func (o *ModelsResourceStats) HasMemoryUsedMb() bool {
	if o != nil && !IsNil(o.MemoryUsedMb) {
		return true
	}

	return false
}

// SetMemoryUsedMb gets a reference to the given float32 and assigns it to the MemoryUsedMb field.
func (o *ModelsResourceStats) SetMemoryUsedMb(v float32) {
	o.MemoryUsedMb = &v
}

func (o ModelsResourceStats) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsResourceStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AverageCpuPercent) {
		toSerialize["average_cpu_percent"] = o.AverageCpuPercent
	}
	if !IsNil(o.MemoryAllocatedMb) {
		toSerialize["memory_allocated_mb"] = o.MemoryAllocatedMb
	}
	if !IsNil(o.MemoryUsedMb) {
		toSerialize["memory_used_mb"] = o.MemoryUsedMb
	}
	return toSerialize, nil
}

type NullableModelsResourceStats struct {
	value *ModelsResourceStats
	isSet bool
}

func (v NullableModelsResourceStats) Get() *ModelsResourceStats {
	return v.value
}

func (v *NullableModelsResourceStats) Set(val *ModelsResourceStats) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsResourceStats) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsResourceStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsResourceStats(val *ModelsResourceStats) *NullableModelsResourceStats {
	return &NullableModelsResourceStats{value: val, isSet: true}
}

func (v NullableModelsResourceStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsResourceStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
