/*
SimpleCloud Controller API

API for SimpleCloud Controller

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplecloud

import (
	"encoding/json"
)

// checks if the ModelsDeleteBlueprintResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsDeleteBlueprintResponse{}

// ModelsDeleteBlueprintResponse Response for deleting a blueprint
type ModelsDeleteBlueprintResponse struct {
	BlueprintId *string `json:"blueprint_id,omitempty"`
	Message     *string `json:"message,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// NewModelsDeleteBlueprintResponse instantiates a new ModelsDeleteBlueprintResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsDeleteBlueprintResponse() *ModelsDeleteBlueprintResponse {
	this := ModelsDeleteBlueprintResponse{}
	return &this
}

// NewModelsDeleteBlueprintResponseWithDefaults instantiates a new ModelsDeleteBlueprintResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsDeleteBlueprintResponseWithDefaults() *ModelsDeleteBlueprintResponse {
	this := ModelsDeleteBlueprintResponse{}
	return &this
}

// GetBlueprintId returns the BlueprintId field value if set, zero value otherwise.
func (o *ModelsDeleteBlueprintResponse) GetBlueprintId() string {
	if o == nil || IsNil(o.BlueprintId) {
		var ret string
		return ret
	}
	return *o.BlueprintId
}

// GetBlueprintIdOk returns a tuple with the BlueprintId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsDeleteBlueprintResponse) GetBlueprintIdOk() (*string, bool) {
	if o == nil || IsNil(o.BlueprintId) {
		return nil, false
	}
	return o.BlueprintId, true
}

// HasBlueprintId returns a boolean if a field has been set.
func (o *ModelsDeleteBlueprintResponse) HasBlueprintId() bool {
	if o != nil && !IsNil(o.BlueprintId) {
		return true
	}

	return false
}

// SetBlueprintId gets a reference to the given string and assigns it to the BlueprintId field.
func (o *ModelsDeleteBlueprintResponse) SetBlueprintId(v string) {
	o.BlueprintId = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ModelsDeleteBlueprintResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsDeleteBlueprintResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ModelsDeleteBlueprintResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ModelsDeleteBlueprintResponse) SetMessage(v string) {
	o.Message = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ModelsDeleteBlueprintResponse) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsDeleteBlueprintResponse) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ModelsDeleteBlueprintResponse) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ModelsDeleteBlueprintResponse) SetName(v string) {
	o.Name = &v
}

func (o ModelsDeleteBlueprintResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsDeleteBlueprintResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BlueprintId) {
		toSerialize["blueprint_id"] = o.BlueprintId
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableModelsDeleteBlueprintResponse struct {
	value *ModelsDeleteBlueprintResponse
	isSet bool
}

func (v NullableModelsDeleteBlueprintResponse) Get() *ModelsDeleteBlueprintResponse {
	return v.value
}

func (v *NullableModelsDeleteBlueprintResponse) Set(val *ModelsDeleteBlueprintResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsDeleteBlueprintResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsDeleteBlueprintResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsDeleteBlueprintResponse(val *ModelsDeleteBlueprintResponse) *NullableModelsDeleteBlueprintResponse {
	return &NullableModelsDeleteBlueprintResponse{value: val, isSet: true}
}

func (v NullableModelsDeleteBlueprintResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsDeleteBlueprintResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
