/*
SimpleCloud Controller API

API for SimpleCloud Controller

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplecloud

import (
	"encoding/json"
)

// checks if the ModelsRegisterNetworkRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsRegisterNetworkRequest{}

// ModelsRegisterNetworkRequest Request for network registration
type ModelsRegisterNetworkRequest struct {
	Name *string `json:"name,omitempty"`
}

// NewModelsRegisterNetworkRequest instantiates a new ModelsRegisterNetworkRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsRegisterNetworkRequest() *ModelsRegisterNetworkRequest {
	this := ModelsRegisterNetworkRequest{}
	return &this
}

// NewModelsRegisterNetworkRequestWithDefaults instantiates a new ModelsRegisterNetworkRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsRegisterNetworkRequestWithDefaults() *ModelsRegisterNetworkRequest {
	this := ModelsRegisterNetworkRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ModelsRegisterNetworkRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsRegisterNetworkRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ModelsRegisterNetworkRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ModelsRegisterNetworkRequest) SetName(v string) {
	o.Name = &v
}

func (o ModelsRegisterNetworkRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsRegisterNetworkRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableModelsRegisterNetworkRequest struct {
	value *ModelsRegisterNetworkRequest
	isSet bool
}

func (v NullableModelsRegisterNetworkRequest) Get() *ModelsRegisterNetworkRequest {
	return v.value
}

func (v *NullableModelsRegisterNetworkRequest) Set(val *ModelsRegisterNetworkRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsRegisterNetworkRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsRegisterNetworkRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsRegisterNetworkRequest(val *ModelsRegisterNetworkRequest) *NullableModelsRegisterNetworkRequest {
	return &NullableModelsRegisterNetworkRequest{value: val, isSet: true}
}

func (v NullableModelsRegisterNetworkRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsRegisterNetworkRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
