/*
SimpleCloud Controller API

API for SimpleCloud Controller

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplecloud

import (
	"encoding/json"
)

// checks if the ModelsListPluginCollectionPluginsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsListPluginCollectionPluginsResponse{}

// ModelsListPluginCollectionPluginsResponse struct for ModelsListPluginCollectionPluginsResponse
type ModelsListPluginCollectionPluginsResponse struct {
	Count                   *int32                                 `json:"count,omitempty"`
	PluginCollectionPlugins []ModelsPluginCollectionPluginResponse `json:"plugin_collection_plugins,omitempty"`
}

// NewModelsListPluginCollectionPluginsResponse instantiates a new ModelsListPluginCollectionPluginsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsListPluginCollectionPluginsResponse() *ModelsListPluginCollectionPluginsResponse {
	this := ModelsListPluginCollectionPluginsResponse{}
	return &this
}

// NewModelsListPluginCollectionPluginsResponseWithDefaults instantiates a new ModelsListPluginCollectionPluginsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsListPluginCollectionPluginsResponseWithDefaults() *ModelsListPluginCollectionPluginsResponse {
	this := ModelsListPluginCollectionPluginsResponse{}
	return &this
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *ModelsListPluginCollectionPluginsResponse) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsListPluginCollectionPluginsResponse) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *ModelsListPluginCollectionPluginsResponse) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *ModelsListPluginCollectionPluginsResponse) SetCount(v int32) {
	o.Count = &v
}

// GetPluginCollectionPlugins returns the PluginCollectionPlugins field value if set, zero value otherwise.
func (o *ModelsListPluginCollectionPluginsResponse) GetPluginCollectionPlugins() []ModelsPluginCollectionPluginResponse {
	if o == nil || IsNil(o.PluginCollectionPlugins) {
		var ret []ModelsPluginCollectionPluginResponse
		return ret
	}
	return o.PluginCollectionPlugins
}

// GetPluginCollectionPluginsOk returns a tuple with the PluginCollectionPlugins field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsListPluginCollectionPluginsResponse) GetPluginCollectionPluginsOk() ([]ModelsPluginCollectionPluginResponse, bool) {
	if o == nil || IsNil(o.PluginCollectionPlugins) {
		return nil, false
	}
	return o.PluginCollectionPlugins, true
}

// HasPluginCollectionPlugins returns a boolean if a field has been set.
func (o *ModelsListPluginCollectionPluginsResponse) HasPluginCollectionPlugins() bool {
	if o != nil && !IsNil(o.PluginCollectionPlugins) {
		return true
	}

	return false
}

// SetPluginCollectionPlugins gets a reference to the given []ModelsPluginCollectionPluginResponse and assigns it to the PluginCollectionPlugins field.
func (o *ModelsListPluginCollectionPluginsResponse) SetPluginCollectionPlugins(v []ModelsPluginCollectionPluginResponse) {
	o.PluginCollectionPlugins = v
}

func (o ModelsListPluginCollectionPluginsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsListPluginCollectionPluginsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !IsNil(o.PluginCollectionPlugins) {
		toSerialize["plugin_collection_plugins"] = o.PluginCollectionPlugins
	}
	return toSerialize, nil
}

type NullableModelsListPluginCollectionPluginsResponse struct {
	value *ModelsListPluginCollectionPluginsResponse
	isSet bool
}

func (v NullableModelsListPluginCollectionPluginsResponse) Get() *ModelsListPluginCollectionPluginsResponse {
	return v.value
}

func (v *NullableModelsListPluginCollectionPluginsResponse) Set(val *ModelsListPluginCollectionPluginsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsListPluginCollectionPluginsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsListPluginCollectionPluginsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsListPluginCollectionPluginsResponse(val *ModelsListPluginCollectionPluginsResponse) *NullableModelsListPluginCollectionPluginsResponse {
	return &NullableModelsListPluginCollectionPluginsResponse{value: val, isSet: true}
}

func (v NullableModelsListPluginCollectionPluginsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsListPluginCollectionPluginsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
