/*
SimpleCloud Controller API

API for SimpleCloud Controller

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplecloud

import (
	"encoding/json"
)

// checks if the ModelsServerGroupStartQueueEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsServerGroupStartQueueEntry{}

// ModelsServerGroupStartQueueEntry Detailed queued start state for one server group
type ModelsServerGroupStartQueueEntry struct {
	FailedStarts    *int32                             `json:"failed_starts,omitempty"`
	QueuedStarts    *int32                             `json:"queued_starts,omitempty"`
	ServerGroupId   *string                            `json:"server_group_id,omitempty"`
	ServerGroupName *string                            `json:"server_group_name,omitempty"`
	Starts          []ModelsManualServerStartQueueItem `json:"starts,omitempty"`
	TotalStarts     *int32                             `json:"total_starts,omitempty"`
}

// NewModelsServerGroupStartQueueEntry instantiates a new ModelsServerGroupStartQueueEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsServerGroupStartQueueEntry() *ModelsServerGroupStartQueueEntry {
	this := ModelsServerGroupStartQueueEntry{}
	return &this
}

// NewModelsServerGroupStartQueueEntryWithDefaults instantiates a new ModelsServerGroupStartQueueEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsServerGroupStartQueueEntryWithDefaults() *ModelsServerGroupStartQueueEntry {
	this := ModelsServerGroupStartQueueEntry{}
	return &this
}

// GetFailedStarts returns the FailedStarts field value if set, zero value otherwise.
func (o *ModelsServerGroupStartQueueEntry) GetFailedStarts() int32 {
	if o == nil || IsNil(o.FailedStarts) {
		var ret int32
		return ret
	}
	return *o.FailedStarts
}

// GetFailedStartsOk returns a tuple with the FailedStarts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsServerGroupStartQueueEntry) GetFailedStartsOk() (*int32, bool) {
	if o == nil || IsNil(o.FailedStarts) {
		return nil, false
	}
	return o.FailedStarts, true
}

// HasFailedStarts returns a boolean if a field has been set.
func (o *ModelsServerGroupStartQueueEntry) HasFailedStarts() bool {
	if o != nil && !IsNil(o.FailedStarts) {
		return true
	}

	return false
}

// SetFailedStarts gets a reference to the given int32 and assigns it to the FailedStarts field.
func (o *ModelsServerGroupStartQueueEntry) SetFailedStarts(v int32) {
	o.FailedStarts = &v
}

// GetQueuedStarts returns the QueuedStarts field value if set, zero value otherwise.
func (o *ModelsServerGroupStartQueueEntry) GetQueuedStarts() int32 {
	if o == nil || IsNil(o.QueuedStarts) {
		var ret int32
		return ret
	}
	return *o.QueuedStarts
}

// GetQueuedStartsOk returns a tuple with the QueuedStarts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsServerGroupStartQueueEntry) GetQueuedStartsOk() (*int32, bool) {
	if o == nil || IsNil(o.QueuedStarts) {
		return nil, false
	}
	return o.QueuedStarts, true
}

// HasQueuedStarts returns a boolean if a field has been set.
func (o *ModelsServerGroupStartQueueEntry) HasQueuedStarts() bool {
	if o != nil && !IsNil(o.QueuedStarts) {
		return true
	}

	return false
}

// SetQueuedStarts gets a reference to the given int32 and assigns it to the QueuedStarts field.
func (o *ModelsServerGroupStartQueueEntry) SetQueuedStarts(v int32) {
	o.QueuedStarts = &v
}

// GetServerGroupId returns the ServerGroupId field value if set, zero value otherwise.
func (o *ModelsServerGroupStartQueueEntry) GetServerGroupId() string {
	if o == nil || IsNil(o.ServerGroupId) {
		var ret string
		return ret
	}
	return *o.ServerGroupId
}

// GetServerGroupIdOk returns a tuple with the ServerGroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsServerGroupStartQueueEntry) GetServerGroupIdOk() (*string, bool) {
	if o == nil || IsNil(o.ServerGroupId) {
		return nil, false
	}
	return o.ServerGroupId, true
}

// HasServerGroupId returns a boolean if a field has been set.
func (o *ModelsServerGroupStartQueueEntry) HasServerGroupId() bool {
	if o != nil && !IsNil(o.ServerGroupId) {
		return true
	}

	return false
}

// SetServerGroupId gets a reference to the given string and assigns it to the ServerGroupId field.
func (o *ModelsServerGroupStartQueueEntry) SetServerGroupId(v string) {
	o.ServerGroupId = &v
}

// GetServerGroupName returns the ServerGroupName field value if set, zero value otherwise.
func (o *ModelsServerGroupStartQueueEntry) GetServerGroupName() string {
	if o == nil || IsNil(o.ServerGroupName) {
		var ret string
		return ret
	}
	return *o.ServerGroupName
}

// GetServerGroupNameOk returns a tuple with the ServerGroupName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsServerGroupStartQueueEntry) GetServerGroupNameOk() (*string, bool) {
	if o == nil || IsNil(o.ServerGroupName) {
		return nil, false
	}
	return o.ServerGroupName, true
}

// HasServerGroupName returns a boolean if a field has been set.
func (o *ModelsServerGroupStartQueueEntry) HasServerGroupName() bool {
	if o != nil && !IsNil(o.ServerGroupName) {
		return true
	}

	return false
}

// SetServerGroupName gets a reference to the given string and assigns it to the ServerGroupName field.
func (o *ModelsServerGroupStartQueueEntry) SetServerGroupName(v string) {
	o.ServerGroupName = &v
}

// GetStarts returns the Starts field value if set, zero value otherwise.
func (o *ModelsServerGroupStartQueueEntry) GetStarts() []ModelsManualServerStartQueueItem {
	if o == nil || IsNil(o.Starts) {
		var ret []ModelsManualServerStartQueueItem
		return ret
	}
	return o.Starts
}

// GetStartsOk returns a tuple with the Starts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsServerGroupStartQueueEntry) GetStartsOk() ([]ModelsManualServerStartQueueItem, bool) {
	if o == nil || IsNil(o.Starts) {
		return nil, false
	}
	return o.Starts, true
}

// HasStarts returns a boolean if a field has been set.
func (o *ModelsServerGroupStartQueueEntry) HasStarts() bool {
	if o != nil && !IsNil(o.Starts) {
		return true
	}

	return false
}

// SetStarts gets a reference to the given []ModelsManualServerStartQueueItem and assigns it to the Starts field.
func (o *ModelsServerGroupStartQueueEntry) SetStarts(v []ModelsManualServerStartQueueItem) {
	o.Starts = v
}

// GetTotalStarts returns the TotalStarts field value if set, zero value otherwise.
func (o *ModelsServerGroupStartQueueEntry) GetTotalStarts() int32 {
	if o == nil || IsNil(o.TotalStarts) {
		var ret int32
		return ret
	}
	return *o.TotalStarts
}

// GetTotalStartsOk returns a tuple with the TotalStarts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsServerGroupStartQueueEntry) GetTotalStartsOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalStarts) {
		return nil, false
	}
	return o.TotalStarts, true
}

// HasTotalStarts returns a boolean if a field has been set.
func (o *ModelsServerGroupStartQueueEntry) HasTotalStarts() bool {
	if o != nil && !IsNil(o.TotalStarts) {
		return true
	}

	return false
}

// SetTotalStarts gets a reference to the given int32 and assigns it to the TotalStarts field.
func (o *ModelsServerGroupStartQueueEntry) SetTotalStarts(v int32) {
	o.TotalStarts = &v
}

func (o ModelsServerGroupStartQueueEntry) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsServerGroupStartQueueEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FailedStarts) {
		toSerialize["failed_starts"] = o.FailedStarts
	}
	if !IsNil(o.QueuedStarts) {
		toSerialize["queued_starts"] = o.QueuedStarts
	}
	if !IsNil(o.ServerGroupId) {
		toSerialize["server_group_id"] = o.ServerGroupId
	}
	if !IsNil(o.ServerGroupName) {
		toSerialize["server_group_name"] = o.ServerGroupName
	}
	if !IsNil(o.Starts) {
		toSerialize["starts"] = o.Starts
	}
	if !IsNil(o.TotalStarts) {
		toSerialize["total_starts"] = o.TotalStarts
	}
	return toSerialize, nil
}

type NullableModelsServerGroupStartQueueEntry struct {
	value *ModelsServerGroupStartQueueEntry
	isSet bool
}

func (v NullableModelsServerGroupStartQueueEntry) Get() *ModelsServerGroupStartQueueEntry {
	return v.value
}

func (v *NullableModelsServerGroupStartQueueEntry) Set(val *ModelsServerGroupStartQueueEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsServerGroupStartQueueEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsServerGroupStartQueueEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsServerGroupStartQueueEntry(val *ModelsServerGroupStartQueueEntry) *NullableModelsServerGroupStartQueueEntry {
	return &NullableModelsServerGroupStartQueueEntry{value: val, isSet: true}
}

func (v NullableModelsServerGroupStartQueueEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsServerGroupStartQueueEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
