/*
SimpleCloud Controller API

API for SimpleCloud Controller

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplecloud

import (
	"encoding/json"
)

// checks if the ModelsPluginAssignmentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsPluginAssignmentResponse{}

// ModelsPluginAssignmentResponse struct for ModelsPluginAssignmentResponse
type ModelsPluginAssignmentResponse struct {
	CreatedAt          *string `json:"created_at,omitempty"`
	Id                 *string `json:"id,omitempty"`
	McNetworkId        *string `json:"mc_network_id,omitempty"`
	PersistentServerId *string `json:"persistent_server_id,omitempty"`
	PluginId           *string `json:"plugin_id,omitempty"`
	PluginName         *string `json:"plugin_name,omitempty"`
	Required           *bool   `json:"required,omitempty"`
	ServerGroupId      *string `json:"server_group_id,omitempty"`
	SourceType         *string `json:"source_type,omitempty"`
	SourceValue        *string `json:"source_value,omitempty"`
	UpdatedAt          *string `json:"updated_at,omitempty"`
	Version            *string `json:"version,omitempty"`
}

// NewModelsPluginAssignmentResponse instantiates a new ModelsPluginAssignmentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsPluginAssignmentResponse() *ModelsPluginAssignmentResponse {
	this := ModelsPluginAssignmentResponse{}
	return &this
}

// NewModelsPluginAssignmentResponseWithDefaults instantiates a new ModelsPluginAssignmentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsPluginAssignmentResponseWithDefaults() *ModelsPluginAssignmentResponse {
	this := ModelsPluginAssignmentResponse{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ModelsPluginAssignmentResponse) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsPluginAssignmentResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ModelsPluginAssignmentResponse) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *ModelsPluginAssignmentResponse) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ModelsPluginAssignmentResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsPluginAssignmentResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ModelsPluginAssignmentResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ModelsPluginAssignmentResponse) SetId(v string) {
	o.Id = &v
}

// GetMcNetworkId returns the McNetworkId field value if set, zero value otherwise.
func (o *ModelsPluginAssignmentResponse) GetMcNetworkId() string {
	if o == nil || IsNil(o.McNetworkId) {
		var ret string
		return ret
	}
	return *o.McNetworkId
}

// GetMcNetworkIdOk returns a tuple with the McNetworkId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsPluginAssignmentResponse) GetMcNetworkIdOk() (*string, bool) {
	if o == nil || IsNil(o.McNetworkId) {
		return nil, false
	}
	return o.McNetworkId, true
}

// HasMcNetworkId returns a boolean if a field has been set.
func (o *ModelsPluginAssignmentResponse) HasMcNetworkId() bool {
	if o != nil && !IsNil(o.McNetworkId) {
		return true
	}

	return false
}

// SetMcNetworkId gets a reference to the given string and assigns it to the McNetworkId field.
func (o *ModelsPluginAssignmentResponse) SetMcNetworkId(v string) {
	o.McNetworkId = &v
}

// GetPersistentServerId returns the PersistentServerId field value if set, zero value otherwise.
func (o *ModelsPluginAssignmentResponse) GetPersistentServerId() string {
	if o == nil || IsNil(o.PersistentServerId) {
		var ret string
		return ret
	}
	return *o.PersistentServerId
}

// GetPersistentServerIdOk returns a tuple with the PersistentServerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsPluginAssignmentResponse) GetPersistentServerIdOk() (*string, bool) {
	if o == nil || IsNil(o.PersistentServerId) {
		return nil, false
	}
	return o.PersistentServerId, true
}

// HasPersistentServerId returns a boolean if a field has been set.
func (o *ModelsPluginAssignmentResponse) HasPersistentServerId() bool {
	if o != nil && !IsNil(o.PersistentServerId) {
		return true
	}

	return false
}

// SetPersistentServerId gets a reference to the given string and assigns it to the PersistentServerId field.
func (o *ModelsPluginAssignmentResponse) SetPersistentServerId(v string) {
	o.PersistentServerId = &v
}

// GetPluginId returns the PluginId field value if set, zero value otherwise.
func (o *ModelsPluginAssignmentResponse) GetPluginId() string {
	if o == nil || IsNil(o.PluginId) {
		var ret string
		return ret
	}
	return *o.PluginId
}

// GetPluginIdOk returns a tuple with the PluginId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsPluginAssignmentResponse) GetPluginIdOk() (*string, bool) {
	if o == nil || IsNil(o.PluginId) {
		return nil, false
	}
	return o.PluginId, true
}

// HasPluginId returns a boolean if a field has been set.
func (o *ModelsPluginAssignmentResponse) HasPluginId() bool {
	if o != nil && !IsNil(o.PluginId) {
		return true
	}

	return false
}

// SetPluginId gets a reference to the given string and assigns it to the PluginId field.
func (o *ModelsPluginAssignmentResponse) SetPluginId(v string) {
	o.PluginId = &v
}

// GetPluginName returns the PluginName field value if set, zero value otherwise.
func (o *ModelsPluginAssignmentResponse) GetPluginName() string {
	if o == nil || IsNil(o.PluginName) {
		var ret string
		return ret
	}
	return *o.PluginName
}

// GetPluginNameOk returns a tuple with the PluginName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsPluginAssignmentResponse) GetPluginNameOk() (*string, bool) {
	if o == nil || IsNil(o.PluginName) {
		return nil, false
	}
	return o.PluginName, true
}

// HasPluginName returns a boolean if a field has been set.
func (o *ModelsPluginAssignmentResponse) HasPluginName() bool {
	if o != nil && !IsNil(o.PluginName) {
		return true
	}

	return false
}

// SetPluginName gets a reference to the given string and assigns it to the PluginName field.
func (o *ModelsPluginAssignmentResponse) SetPluginName(v string) {
	o.PluginName = &v
}

// GetRequired returns the Required field value if set, zero value otherwise.
func (o *ModelsPluginAssignmentResponse) GetRequired() bool {
	if o == nil || IsNil(o.Required) {
		var ret bool
		return ret
	}
	return *o.Required
}

// GetRequiredOk returns a tuple with the Required field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsPluginAssignmentResponse) GetRequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.Required) {
		return nil, false
	}
	return o.Required, true
}

// HasRequired returns a boolean if a field has been set.
func (o *ModelsPluginAssignmentResponse) HasRequired() bool {
	if o != nil && !IsNil(o.Required) {
		return true
	}

	return false
}

// SetRequired gets a reference to the given bool and assigns it to the Required field.
func (o *ModelsPluginAssignmentResponse) SetRequired(v bool) {
	o.Required = &v
}

// GetServerGroupId returns the ServerGroupId field value if set, zero value otherwise.
func (o *ModelsPluginAssignmentResponse) GetServerGroupId() string {
	if o == nil || IsNil(o.ServerGroupId) {
		var ret string
		return ret
	}
	return *o.ServerGroupId
}

// GetServerGroupIdOk returns a tuple with the ServerGroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsPluginAssignmentResponse) GetServerGroupIdOk() (*string, bool) {
	if o == nil || IsNil(o.ServerGroupId) {
		return nil, false
	}
	return o.ServerGroupId, true
}

// HasServerGroupId returns a boolean if a field has been set.
func (o *ModelsPluginAssignmentResponse) HasServerGroupId() bool {
	if o != nil && !IsNil(o.ServerGroupId) {
		return true
	}

	return false
}

// SetServerGroupId gets a reference to the given string and assigns it to the ServerGroupId field.
func (o *ModelsPluginAssignmentResponse) SetServerGroupId(v string) {
	o.ServerGroupId = &v
}

// GetSourceType returns the SourceType field value if set, zero value otherwise.
func (o *ModelsPluginAssignmentResponse) GetSourceType() string {
	if o == nil || IsNil(o.SourceType) {
		var ret string
		return ret
	}
	return *o.SourceType
}

// GetSourceTypeOk returns a tuple with the SourceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsPluginAssignmentResponse) GetSourceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.SourceType) {
		return nil, false
	}
	return o.SourceType, true
}

// HasSourceType returns a boolean if a field has been set.
func (o *ModelsPluginAssignmentResponse) HasSourceType() bool {
	if o != nil && !IsNil(o.SourceType) {
		return true
	}

	return false
}

// SetSourceType gets a reference to the given string and assigns it to the SourceType field.
func (o *ModelsPluginAssignmentResponse) SetSourceType(v string) {
	o.SourceType = &v
}

// GetSourceValue returns the SourceValue field value if set, zero value otherwise.
func (o *ModelsPluginAssignmentResponse) GetSourceValue() string {
	if o == nil || IsNil(o.SourceValue) {
		var ret string
		return ret
	}
	return *o.SourceValue
}

// GetSourceValueOk returns a tuple with the SourceValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsPluginAssignmentResponse) GetSourceValueOk() (*string, bool) {
	if o == nil || IsNil(o.SourceValue) {
		return nil, false
	}
	return o.SourceValue, true
}

// HasSourceValue returns a boolean if a field has been set.
func (o *ModelsPluginAssignmentResponse) HasSourceValue() bool {
	if o != nil && !IsNil(o.SourceValue) {
		return true
	}

	return false
}

// SetSourceValue gets a reference to the given string and assigns it to the SourceValue field.
func (o *ModelsPluginAssignmentResponse) SetSourceValue(v string) {
	o.SourceValue = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *ModelsPluginAssignmentResponse) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsPluginAssignmentResponse) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *ModelsPluginAssignmentResponse) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *ModelsPluginAssignmentResponse) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *ModelsPluginAssignmentResponse) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsPluginAssignmentResponse) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *ModelsPluginAssignmentResponse) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *ModelsPluginAssignmentResponse) SetVersion(v string) {
	o.Version = &v
}

func (o ModelsPluginAssignmentResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsPluginAssignmentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.McNetworkId) {
		toSerialize["mc_network_id"] = o.McNetworkId
	}
	if !IsNil(o.PersistentServerId) {
		toSerialize["persistent_server_id"] = o.PersistentServerId
	}
	if !IsNil(o.PluginId) {
		toSerialize["plugin_id"] = o.PluginId
	}
	if !IsNil(o.PluginName) {
		toSerialize["plugin_name"] = o.PluginName
	}
	if !IsNil(o.Required) {
		toSerialize["required"] = o.Required
	}
	if !IsNil(o.ServerGroupId) {
		toSerialize["server_group_id"] = o.ServerGroupId
	}
	if !IsNil(o.SourceType) {
		toSerialize["source_type"] = o.SourceType
	}
	if !IsNil(o.SourceValue) {
		toSerialize["source_value"] = o.SourceValue
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

type NullableModelsPluginAssignmentResponse struct {
	value *ModelsPluginAssignmentResponse
	isSet bool
}

func (v NullableModelsPluginAssignmentResponse) Get() *ModelsPluginAssignmentResponse {
	return v.value
}

func (v *NullableModelsPluginAssignmentResponse) Set(val *ModelsPluginAssignmentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsPluginAssignmentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsPluginAssignmentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsPluginAssignmentResponse(val *ModelsPluginAssignmentResponse) *NullableModelsPluginAssignmentResponse {
	return &NullableModelsPluginAssignmentResponse{value: val, isSet: true}
}

func (v NullableModelsPluginAssignmentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsPluginAssignmentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
