/*
SimpleCloud Controller API

API for SimpleCloud Controller

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplecloud

import (
	"encoding/json"
)

// checks if the ModelsSendCommandResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsSendCommandResponse{}

// ModelsSendCommandResponse Response for sending a command to a server
type ModelsSendCommandResponse struct {
	Command  *string `json:"command,omitempty"`
	Message  *string `json:"message,omitempty"`
	ServerId *string `json:"server_id,omitempty"`
}

// NewModelsSendCommandResponse instantiates a new ModelsSendCommandResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsSendCommandResponse() *ModelsSendCommandResponse {
	this := ModelsSendCommandResponse{}
	return &this
}

// NewModelsSendCommandResponseWithDefaults instantiates a new ModelsSendCommandResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsSendCommandResponseWithDefaults() *ModelsSendCommandResponse {
	this := ModelsSendCommandResponse{}
	return &this
}

// GetCommand returns the Command field value if set, zero value otherwise.
func (o *ModelsSendCommandResponse) GetCommand() string {
	if o == nil || IsNil(o.Command) {
		var ret string
		return ret
	}
	return *o.Command
}

// GetCommandOk returns a tuple with the Command field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsSendCommandResponse) GetCommandOk() (*string, bool) {
	if o == nil || IsNil(o.Command) {
		return nil, false
	}
	return o.Command, true
}

// HasCommand returns a boolean if a field has been set.
func (o *ModelsSendCommandResponse) HasCommand() bool {
	if o != nil && !IsNil(o.Command) {
		return true
	}

	return false
}

// SetCommand gets a reference to the given string and assigns it to the Command field.
func (o *ModelsSendCommandResponse) SetCommand(v string) {
	o.Command = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ModelsSendCommandResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsSendCommandResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ModelsSendCommandResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ModelsSendCommandResponse) SetMessage(v string) {
	o.Message = &v
}

// GetServerId returns the ServerId field value if set, zero value otherwise.
func (o *ModelsSendCommandResponse) GetServerId() string {
	if o == nil || IsNil(o.ServerId) {
		var ret string
		return ret
	}
	return *o.ServerId
}

// GetServerIdOk returns a tuple with the ServerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsSendCommandResponse) GetServerIdOk() (*string, bool) {
	if o == nil || IsNil(o.ServerId) {
		return nil, false
	}
	return o.ServerId, true
}

// HasServerId returns a boolean if a field has been set.
func (o *ModelsSendCommandResponse) HasServerId() bool {
	if o != nil && !IsNil(o.ServerId) {
		return true
	}

	return false
}

// SetServerId gets a reference to the given string and assigns it to the ServerId field.
func (o *ModelsSendCommandResponse) SetServerId(v string) {
	o.ServerId = &v
}

func (o ModelsSendCommandResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsSendCommandResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Command) {
		toSerialize["command"] = o.Command
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.ServerId) {
		toSerialize["server_id"] = o.ServerId
	}
	return toSerialize, nil
}

type NullableModelsSendCommandResponse struct {
	value *ModelsSendCommandResponse
	isSet bool
}

func (v NullableModelsSendCommandResponse) Get() *ModelsSendCommandResponse {
	return v.value
}

func (v *NullableModelsSendCommandResponse) Set(val *ModelsSendCommandResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsSendCommandResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsSendCommandResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsSendCommandResponse(val *ModelsSendCommandResponse) *NullableModelsSendCommandResponse {
	return &NullableModelsSendCommandResponse{value: val, isSet: true}
}

func (v NullableModelsSendCommandResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsSendCommandResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
