/*
SimpleCloud Controller API

API for SimpleCloud Controller

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplecloud

import (
	"encoding/json"
)

// checks if the ModelsHealthStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsHealthStatus{}

// ModelsHealthStatus struct for ModelsHealthStatus
type ModelsHealthStatus struct {
	HealthyServerPercent *float32 `json:"healthy_server_percent,omitempty"`
	Status               *string  `json:"status,omitempty"`
}

// NewModelsHealthStatus instantiates a new ModelsHealthStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsHealthStatus() *ModelsHealthStatus {
	this := ModelsHealthStatus{}
	return &this
}

// NewModelsHealthStatusWithDefaults instantiates a new ModelsHealthStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsHealthStatusWithDefaults() *ModelsHealthStatus {
	this := ModelsHealthStatus{}
	return &this
}

// GetHealthyServerPercent returns the HealthyServerPercent field value if set, zero value otherwise.
func (o *ModelsHealthStatus) GetHealthyServerPercent() float32 {
	if o == nil || IsNil(o.HealthyServerPercent) {
		var ret float32
		return ret
	}
	return *o.HealthyServerPercent
}

// GetHealthyServerPercentOk returns a tuple with the HealthyServerPercent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsHealthStatus) GetHealthyServerPercentOk() (*float32, bool) {
	if o == nil || IsNil(o.HealthyServerPercent) {
		return nil, false
	}
	return o.HealthyServerPercent, true
}

// HasHealthyServerPercent returns a boolean if a field has been set.
func (o *ModelsHealthStatus) HasHealthyServerPercent() bool {
	if o != nil && !IsNil(o.HealthyServerPercent) {
		return true
	}

	return false
}

// SetHealthyServerPercent gets a reference to the given float32 and assigns it to the HealthyServerPercent field.
func (o *ModelsHealthStatus) SetHealthyServerPercent(v float32) {
	o.HealthyServerPercent = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ModelsHealthStatus) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsHealthStatus) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ModelsHealthStatus) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ModelsHealthStatus) SetStatus(v string) {
	o.Status = &v
}

func (o ModelsHealthStatus) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsHealthStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.HealthyServerPercent) {
		toSerialize["healthy_server_percent"] = o.HealthyServerPercent
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableModelsHealthStatus struct {
	value *ModelsHealthStatus
	isSet bool
}

func (v NullableModelsHealthStatus) Get() *ModelsHealthStatus {
	return v.value
}

func (v *NullableModelsHealthStatus) Set(val *ModelsHealthStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsHealthStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsHealthStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsHealthStatus(val *ModelsHealthStatus) *NullableModelsHealthStatus {
	return &NullableModelsHealthStatus{value: val, isSet: true}
}

func (v NullableModelsHealthStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsHealthStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
