/*
SimpleCloud Controller API

API for SimpleCloud Controller

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplecloud

import (
	"encoding/json"
)

// checks if the ModelsConnectPlayerRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsConnectPlayerRequest{}

// ModelsConnectPlayerRequest Request to connect a player to a server
type ModelsConnectPlayerRequest struct {
	PersistentServerId *string `json:"persistent_server_id,omitempty"`
	SelectionMode      *string `json:"selection_mode,omitempty"`
	ServerGroupId      *string `json:"server_group_id,omitempty"`
	ServerId           *string `json:"server_id,omitempty"`
}

// NewModelsConnectPlayerRequest instantiates a new ModelsConnectPlayerRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsConnectPlayerRequest() *ModelsConnectPlayerRequest {
	this := ModelsConnectPlayerRequest{}
	return &this
}

// NewModelsConnectPlayerRequestWithDefaults instantiates a new ModelsConnectPlayerRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsConnectPlayerRequestWithDefaults() *ModelsConnectPlayerRequest {
	this := ModelsConnectPlayerRequest{}
	return &this
}

// GetPersistentServerId returns the PersistentServerId field value if set, zero value otherwise.
func (o *ModelsConnectPlayerRequest) GetPersistentServerId() string {
	if o == nil || IsNil(o.PersistentServerId) {
		var ret string
		return ret
	}
	return *o.PersistentServerId
}

// GetPersistentServerIdOk returns a tuple with the PersistentServerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsConnectPlayerRequest) GetPersistentServerIdOk() (*string, bool) {
	if o == nil || IsNil(o.PersistentServerId) {
		return nil, false
	}
	return o.PersistentServerId, true
}

// HasPersistentServerId returns a boolean if a field has been set.
func (o *ModelsConnectPlayerRequest) HasPersistentServerId() bool {
	if o != nil && !IsNil(o.PersistentServerId) {
		return true
	}

	return false
}

// SetPersistentServerId gets a reference to the given string and assigns it to the PersistentServerId field.
func (o *ModelsConnectPlayerRequest) SetPersistentServerId(v string) {
	o.PersistentServerId = &v
}

// GetSelectionMode returns the SelectionMode field value if set, zero value otherwise.
func (o *ModelsConnectPlayerRequest) GetSelectionMode() string {
	if o == nil || IsNil(o.SelectionMode) {
		var ret string
		return ret
	}
	return *o.SelectionMode
}

// GetSelectionModeOk returns a tuple with the SelectionMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsConnectPlayerRequest) GetSelectionModeOk() (*string, bool) {
	if o == nil || IsNil(o.SelectionMode) {
		return nil, false
	}
	return o.SelectionMode, true
}

// HasSelectionMode returns a boolean if a field has been set.
func (o *ModelsConnectPlayerRequest) HasSelectionMode() bool {
	if o != nil && !IsNil(o.SelectionMode) {
		return true
	}

	return false
}

// SetSelectionMode gets a reference to the given string and assigns it to the SelectionMode field.
func (o *ModelsConnectPlayerRequest) SetSelectionMode(v string) {
	o.SelectionMode = &v
}

// GetServerGroupId returns the ServerGroupId field value if set, zero value otherwise.
func (o *ModelsConnectPlayerRequest) GetServerGroupId() string {
	if o == nil || IsNil(o.ServerGroupId) {
		var ret string
		return ret
	}
	return *o.ServerGroupId
}

// GetServerGroupIdOk returns a tuple with the ServerGroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsConnectPlayerRequest) GetServerGroupIdOk() (*string, bool) {
	if o == nil || IsNil(o.ServerGroupId) {
		return nil, false
	}
	return o.ServerGroupId, true
}

// HasServerGroupId returns a boolean if a field has been set.
func (o *ModelsConnectPlayerRequest) HasServerGroupId() bool {
	if o != nil && !IsNil(o.ServerGroupId) {
		return true
	}

	return false
}

// SetServerGroupId gets a reference to the given string and assigns it to the ServerGroupId field.
func (o *ModelsConnectPlayerRequest) SetServerGroupId(v string) {
	o.ServerGroupId = &v
}

// GetServerId returns the ServerId field value if set, zero value otherwise.
func (o *ModelsConnectPlayerRequest) GetServerId() string {
	if o == nil || IsNil(o.ServerId) {
		var ret string
		return ret
	}
	return *o.ServerId
}

// GetServerIdOk returns a tuple with the ServerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsConnectPlayerRequest) GetServerIdOk() (*string, bool) {
	if o == nil || IsNil(o.ServerId) {
		return nil, false
	}
	return o.ServerId, true
}

// HasServerId returns a boolean if a field has been set.
func (o *ModelsConnectPlayerRequest) HasServerId() bool {
	if o != nil && !IsNil(o.ServerId) {
		return true
	}

	return false
}

// SetServerId gets a reference to the given string and assigns it to the ServerId field.
func (o *ModelsConnectPlayerRequest) SetServerId(v string) {
	o.ServerId = &v
}

func (o ModelsConnectPlayerRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsConnectPlayerRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PersistentServerId) {
		toSerialize["persistent_server_id"] = o.PersistentServerId
	}
	if !IsNil(o.SelectionMode) {
		toSerialize["selection_mode"] = o.SelectionMode
	}
	if !IsNil(o.ServerGroupId) {
		toSerialize["server_group_id"] = o.ServerGroupId
	}
	if !IsNil(o.ServerId) {
		toSerialize["server_id"] = o.ServerId
	}
	return toSerialize, nil
}

type NullableModelsConnectPlayerRequest struct {
	value *ModelsConnectPlayerRequest
	isSet bool
}

func (v NullableModelsConnectPlayerRequest) Get() *ModelsConnectPlayerRequest {
	return v.value
}

func (v *NullableModelsConnectPlayerRequest) Set(val *ModelsConnectPlayerRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsConnectPlayerRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsConnectPlayerRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsConnectPlayerRequest(val *ModelsConnectPlayerRequest) *NullableModelsConnectPlayerRequest {
	return &NullableModelsConnectPlayerRequest{value: val, isSet: true}
}

func (v NullableModelsConnectPlayerRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsConnectPlayerRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
