/*
SimpleCloud Controller API

API for SimpleCloud Controller

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplecloud

import (
	"encoding/json"
)

// checks if the ModelsBulkDeletePluginAssignmentsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsBulkDeletePluginAssignmentsRequest{}

// ModelsBulkDeletePluginAssignmentsRequest struct for ModelsBulkDeletePluginAssignmentsRequest
type ModelsBulkDeletePluginAssignmentsRequest struct {
	AssignmentIds []string `json:"assignment_ids,omitempty"`
}

// NewModelsBulkDeletePluginAssignmentsRequest instantiates a new ModelsBulkDeletePluginAssignmentsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsBulkDeletePluginAssignmentsRequest() *ModelsBulkDeletePluginAssignmentsRequest {
	this := ModelsBulkDeletePluginAssignmentsRequest{}
	return &this
}

// NewModelsBulkDeletePluginAssignmentsRequestWithDefaults instantiates a new ModelsBulkDeletePluginAssignmentsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsBulkDeletePluginAssignmentsRequestWithDefaults() *ModelsBulkDeletePluginAssignmentsRequest {
	this := ModelsBulkDeletePluginAssignmentsRequest{}
	return &this
}

// GetAssignmentIds returns the AssignmentIds field value if set, zero value otherwise.
func (o *ModelsBulkDeletePluginAssignmentsRequest) GetAssignmentIds() []string {
	if o == nil || IsNil(o.AssignmentIds) {
		var ret []string
		return ret
	}
	return o.AssignmentIds
}

// GetAssignmentIdsOk returns a tuple with the AssignmentIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsBulkDeletePluginAssignmentsRequest) GetAssignmentIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.AssignmentIds) {
		return nil, false
	}
	return o.AssignmentIds, true
}

// HasAssignmentIds returns a boolean if a field has been set.
func (o *ModelsBulkDeletePluginAssignmentsRequest) HasAssignmentIds() bool {
	if o != nil && !IsNil(o.AssignmentIds) {
		return true
	}

	return false
}

// SetAssignmentIds gets a reference to the given []string and assigns it to the AssignmentIds field.
func (o *ModelsBulkDeletePluginAssignmentsRequest) SetAssignmentIds(v []string) {
	o.AssignmentIds = v
}

func (o ModelsBulkDeletePluginAssignmentsRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsBulkDeletePluginAssignmentsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AssignmentIds) {
		toSerialize["assignment_ids"] = o.AssignmentIds
	}
	return toSerialize, nil
}

type NullableModelsBulkDeletePluginAssignmentsRequest struct {
	value *ModelsBulkDeletePluginAssignmentsRequest
	isSet bool
}

func (v NullableModelsBulkDeletePluginAssignmentsRequest) Get() *ModelsBulkDeletePluginAssignmentsRequest {
	return v.value
}

func (v *NullableModelsBulkDeletePluginAssignmentsRequest) Set(val *ModelsBulkDeletePluginAssignmentsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsBulkDeletePluginAssignmentsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsBulkDeletePluginAssignmentsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsBulkDeletePluginAssignmentsRequest(val *ModelsBulkDeletePluginAssignmentsRequest) *NullableModelsBulkDeletePluginAssignmentsRequest {
	return &NullableModelsBulkDeletePluginAssignmentsRequest{value: val, isSet: true}
}

func (v NullableModelsBulkDeletePluginAssignmentsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsBulkDeletePluginAssignmentsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
