/*
SimpleCloud Controller API

API for SimpleCloud Controller

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplecloud

import (
	"encoding/json"
)

// checks if the ModelsKickPlayerRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsKickPlayerRequest{}

// ModelsKickPlayerRequest Request to kick a player
type ModelsKickPlayerRequest struct {
	Reason *string `json:"reason,omitempty"`
}

// NewModelsKickPlayerRequest instantiates a new ModelsKickPlayerRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsKickPlayerRequest() *ModelsKickPlayerRequest {
	this := ModelsKickPlayerRequest{}
	return &this
}

// NewModelsKickPlayerRequestWithDefaults instantiates a new ModelsKickPlayerRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsKickPlayerRequestWithDefaults() *ModelsKickPlayerRequest {
	this := ModelsKickPlayerRequest{}
	return &this
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *ModelsKickPlayerRequest) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsKickPlayerRequest) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *ModelsKickPlayerRequest) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *ModelsKickPlayerRequest) SetReason(v string) {
	o.Reason = &v
}

func (o ModelsKickPlayerRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsKickPlayerRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	return toSerialize, nil
}

type NullableModelsKickPlayerRequest struct {
	value *ModelsKickPlayerRequest
	isSet bool
}

func (v NullableModelsKickPlayerRequest) Get() *ModelsKickPlayerRequest {
	return v.value
}

func (v *NullableModelsKickPlayerRequest) Set(val *ModelsKickPlayerRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsKickPlayerRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsKickPlayerRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsKickPlayerRequest(val *ModelsKickPlayerRequest) *NullableModelsKickPlayerRequest {
	return &NullableModelsKickPlayerRequest{value: val, isSet: true}
}

func (v NullableModelsKickPlayerRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsKickPlayerRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
