/*
SimpleCloud Controller API

API for SimpleCloud Controller

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplecloud

import (
	"encoding/json"
)

// checks if the ModelsConnectPlayerResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsConnectPlayerResponse{}

// ModelsConnectPlayerResponse Response for connecting a player
type ModelsConnectPlayerResponse struct {
	Message    *string `json:"message,omitempty"`
	PlayerId   *string `json:"player_id,omitempty"`
	ServerName *string `json:"server_name,omitempty"`
	Success    *bool   `json:"success,omitempty"`
}

// NewModelsConnectPlayerResponse instantiates a new ModelsConnectPlayerResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsConnectPlayerResponse() *ModelsConnectPlayerResponse {
	this := ModelsConnectPlayerResponse{}
	return &this
}

// NewModelsConnectPlayerResponseWithDefaults instantiates a new ModelsConnectPlayerResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsConnectPlayerResponseWithDefaults() *ModelsConnectPlayerResponse {
	this := ModelsConnectPlayerResponse{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ModelsConnectPlayerResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsConnectPlayerResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ModelsConnectPlayerResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ModelsConnectPlayerResponse) SetMessage(v string) {
	o.Message = &v
}

// GetPlayerId returns the PlayerId field value if set, zero value otherwise.
func (o *ModelsConnectPlayerResponse) GetPlayerId() string {
	if o == nil || IsNil(o.PlayerId) {
		var ret string
		return ret
	}
	return *o.PlayerId
}

// GetPlayerIdOk returns a tuple with the PlayerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsConnectPlayerResponse) GetPlayerIdOk() (*string, bool) {
	if o == nil || IsNil(o.PlayerId) {
		return nil, false
	}
	return o.PlayerId, true
}

// HasPlayerId returns a boolean if a field has been set.
func (o *ModelsConnectPlayerResponse) HasPlayerId() bool {
	if o != nil && !IsNil(o.PlayerId) {
		return true
	}

	return false
}

// SetPlayerId gets a reference to the given string and assigns it to the PlayerId field.
func (o *ModelsConnectPlayerResponse) SetPlayerId(v string) {
	o.PlayerId = &v
}

// GetServerName returns the ServerName field value if set, zero value otherwise.
func (o *ModelsConnectPlayerResponse) GetServerName() string {
	if o == nil || IsNil(o.ServerName) {
		var ret string
		return ret
	}
	return *o.ServerName
}

// GetServerNameOk returns a tuple with the ServerName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsConnectPlayerResponse) GetServerNameOk() (*string, bool) {
	if o == nil || IsNil(o.ServerName) {
		return nil, false
	}
	return o.ServerName, true
}

// HasServerName returns a boolean if a field has been set.
func (o *ModelsConnectPlayerResponse) HasServerName() bool {
	if o != nil && !IsNil(o.ServerName) {
		return true
	}

	return false
}

// SetServerName gets a reference to the given string and assigns it to the ServerName field.
func (o *ModelsConnectPlayerResponse) SetServerName(v string) {
	o.ServerName = &v
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *ModelsConnectPlayerResponse) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsConnectPlayerResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *ModelsConnectPlayerResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *ModelsConnectPlayerResponse) SetSuccess(v bool) {
	o.Success = &v
}

func (o ModelsConnectPlayerResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsConnectPlayerResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.PlayerId) {
		toSerialize["player_id"] = o.PlayerId
	}
	if !IsNil(o.ServerName) {
		toSerialize["server_name"] = o.ServerName
	}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	return toSerialize, nil
}

type NullableModelsConnectPlayerResponse struct {
	value *ModelsConnectPlayerResponse
	isSet bool
}

func (v NullableModelsConnectPlayerResponse) Get() *ModelsConnectPlayerResponse {
	return v.value
}

func (v *NullableModelsConnectPlayerResponse) Set(val *ModelsConnectPlayerResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsConnectPlayerResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsConnectPlayerResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsConnectPlayerResponse(val *ModelsConnectPlayerResponse) *NullableModelsConnectPlayerResponse {
	return &NullableModelsConnectPlayerResponse{value: val, isSet: true}
}

func (v NullableModelsConnectPlayerResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsConnectPlayerResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
