/*
SimpleCloud Controller API

API for SimpleCloud Controller

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplecloud

import (
	"encoding/json"
)

// checks if the ModelsUpdatePluginAssignmentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsUpdatePluginAssignmentRequest{}

// ModelsUpdatePluginAssignmentRequest struct for ModelsUpdatePluginAssignmentRequest
type ModelsUpdatePluginAssignmentRequest struct {
	PluginId    *string `json:"plugin_id,omitempty"`
	PluginName  *string `json:"plugin_name,omitempty"`
	Required    *bool   `json:"required,omitempty"`
	SourceType  *string `json:"source_type,omitempty"`
	SourceValue *string `json:"source_value,omitempty"`
	Version     *string `json:"version,omitempty"`
}

// NewModelsUpdatePluginAssignmentRequest instantiates a new ModelsUpdatePluginAssignmentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsUpdatePluginAssignmentRequest() *ModelsUpdatePluginAssignmentRequest {
	this := ModelsUpdatePluginAssignmentRequest{}
	return &this
}

// NewModelsUpdatePluginAssignmentRequestWithDefaults instantiates a new ModelsUpdatePluginAssignmentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsUpdatePluginAssignmentRequestWithDefaults() *ModelsUpdatePluginAssignmentRequest {
	this := ModelsUpdatePluginAssignmentRequest{}
	return &this
}

// GetPluginId returns the PluginId field value if set, zero value otherwise.
func (o *ModelsUpdatePluginAssignmentRequest) GetPluginId() string {
	if o == nil || IsNil(o.PluginId) {
		var ret string
		return ret
	}
	return *o.PluginId
}

// GetPluginIdOk returns a tuple with the PluginId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsUpdatePluginAssignmentRequest) GetPluginIdOk() (*string, bool) {
	if o == nil || IsNil(o.PluginId) {
		return nil, false
	}
	return o.PluginId, true
}

// HasPluginId returns a boolean if a field has been set.
func (o *ModelsUpdatePluginAssignmentRequest) HasPluginId() bool {
	if o != nil && !IsNil(o.PluginId) {
		return true
	}

	return false
}

// SetPluginId gets a reference to the given string and assigns it to the PluginId field.
func (o *ModelsUpdatePluginAssignmentRequest) SetPluginId(v string) {
	o.PluginId = &v
}

// GetPluginName returns the PluginName field value if set, zero value otherwise.
func (o *ModelsUpdatePluginAssignmentRequest) GetPluginName() string {
	if o == nil || IsNil(o.PluginName) {
		var ret string
		return ret
	}
	return *o.PluginName
}

// GetPluginNameOk returns a tuple with the PluginName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsUpdatePluginAssignmentRequest) GetPluginNameOk() (*string, bool) {
	if o == nil || IsNil(o.PluginName) {
		return nil, false
	}
	return o.PluginName, true
}

// HasPluginName returns a boolean if a field has been set.
func (o *ModelsUpdatePluginAssignmentRequest) HasPluginName() bool {
	if o != nil && !IsNil(o.PluginName) {
		return true
	}

	return false
}

// SetPluginName gets a reference to the given string and assigns it to the PluginName field.
func (o *ModelsUpdatePluginAssignmentRequest) SetPluginName(v string) {
	o.PluginName = &v
}

// GetRequired returns the Required field value if set, zero value otherwise.
func (o *ModelsUpdatePluginAssignmentRequest) GetRequired() bool {
	if o == nil || IsNil(o.Required) {
		var ret bool
		return ret
	}
	return *o.Required
}

// GetRequiredOk returns a tuple with the Required field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsUpdatePluginAssignmentRequest) GetRequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.Required) {
		return nil, false
	}
	return o.Required, true
}

// HasRequired returns a boolean if a field has been set.
func (o *ModelsUpdatePluginAssignmentRequest) HasRequired() bool {
	if o != nil && !IsNil(o.Required) {
		return true
	}

	return false
}

// SetRequired gets a reference to the given bool and assigns it to the Required field.
func (o *ModelsUpdatePluginAssignmentRequest) SetRequired(v bool) {
	o.Required = &v
}

// GetSourceType returns the SourceType field value if set, zero value otherwise.
func (o *ModelsUpdatePluginAssignmentRequest) GetSourceType() string {
	if o == nil || IsNil(o.SourceType) {
		var ret string
		return ret
	}
	return *o.SourceType
}

// GetSourceTypeOk returns a tuple with the SourceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsUpdatePluginAssignmentRequest) GetSourceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.SourceType) {
		return nil, false
	}
	return o.SourceType, true
}

// HasSourceType returns a boolean if a field has been set.
func (o *ModelsUpdatePluginAssignmentRequest) HasSourceType() bool {
	if o != nil && !IsNil(o.SourceType) {
		return true
	}

	return false
}

// SetSourceType gets a reference to the given string and assigns it to the SourceType field.
func (o *ModelsUpdatePluginAssignmentRequest) SetSourceType(v string) {
	o.SourceType = &v
}

// GetSourceValue returns the SourceValue field value if set, zero value otherwise.
func (o *ModelsUpdatePluginAssignmentRequest) GetSourceValue() string {
	if o == nil || IsNil(o.SourceValue) {
		var ret string
		return ret
	}
	return *o.SourceValue
}

// GetSourceValueOk returns a tuple with the SourceValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsUpdatePluginAssignmentRequest) GetSourceValueOk() (*string, bool) {
	if o == nil || IsNil(o.SourceValue) {
		return nil, false
	}
	return o.SourceValue, true
}

// HasSourceValue returns a boolean if a field has been set.
func (o *ModelsUpdatePluginAssignmentRequest) HasSourceValue() bool {
	if o != nil && !IsNil(o.SourceValue) {
		return true
	}

	return false
}

// SetSourceValue gets a reference to the given string and assigns it to the SourceValue field.
func (o *ModelsUpdatePluginAssignmentRequest) SetSourceValue(v string) {
	o.SourceValue = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *ModelsUpdatePluginAssignmentRequest) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsUpdatePluginAssignmentRequest) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *ModelsUpdatePluginAssignmentRequest) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *ModelsUpdatePluginAssignmentRequest) SetVersion(v string) {
	o.Version = &v
}

func (o ModelsUpdatePluginAssignmentRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsUpdatePluginAssignmentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PluginId) {
		toSerialize["plugin_id"] = o.PluginId
	}
	if !IsNil(o.PluginName) {
		toSerialize["plugin_name"] = o.PluginName
	}
	if !IsNil(o.Required) {
		toSerialize["required"] = o.Required
	}
	if !IsNil(o.SourceType) {
		toSerialize["source_type"] = o.SourceType
	}
	if !IsNil(o.SourceValue) {
		toSerialize["source_value"] = o.SourceValue
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

type NullableModelsUpdatePluginAssignmentRequest struct {
	value *ModelsUpdatePluginAssignmentRequest
	isSet bool
}

func (v NullableModelsUpdatePluginAssignmentRequest) Get() *ModelsUpdatePluginAssignmentRequest {
	return v.value
}

func (v *NullableModelsUpdatePluginAssignmentRequest) Set(val *ModelsUpdatePluginAssignmentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsUpdatePluginAssignmentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsUpdatePluginAssignmentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsUpdatePluginAssignmentRequest(val *ModelsUpdatePluginAssignmentRequest) *NullableModelsUpdatePluginAssignmentRequest {
	return &NullableModelsUpdatePluginAssignmentRequest{value: val, isSet: true}
}

func (v NullableModelsUpdatePluginAssignmentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsUpdatePluginAssignmentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
