/*
SimpleCloud Controller API

API for SimpleCloud Controller

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplecloud

import (
	"encoding/json"
)

// checks if the ModelsDeletePersistentServerResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsDeletePersistentServerResponse{}

// ModelsDeletePersistentServerResponse Response for deleting a persistent server
type ModelsDeletePersistentServerResponse struct {
	Message            *string `json:"message,omitempty"`
	Name               *string `json:"name,omitempty"`
	PersistentServerId *string `json:"persistent_server_id,omitempty"`
}

// NewModelsDeletePersistentServerResponse instantiates a new ModelsDeletePersistentServerResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsDeletePersistentServerResponse() *ModelsDeletePersistentServerResponse {
	this := ModelsDeletePersistentServerResponse{}
	return &this
}

// NewModelsDeletePersistentServerResponseWithDefaults instantiates a new ModelsDeletePersistentServerResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsDeletePersistentServerResponseWithDefaults() *ModelsDeletePersistentServerResponse {
	this := ModelsDeletePersistentServerResponse{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ModelsDeletePersistentServerResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsDeletePersistentServerResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ModelsDeletePersistentServerResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ModelsDeletePersistentServerResponse) SetMessage(v string) {
	o.Message = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ModelsDeletePersistentServerResponse) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsDeletePersistentServerResponse) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ModelsDeletePersistentServerResponse) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ModelsDeletePersistentServerResponse) SetName(v string) {
	o.Name = &v
}

// GetPersistentServerId returns the PersistentServerId field value if set, zero value otherwise.
func (o *ModelsDeletePersistentServerResponse) GetPersistentServerId() string {
	if o == nil || IsNil(o.PersistentServerId) {
		var ret string
		return ret
	}
	return *o.PersistentServerId
}

// GetPersistentServerIdOk returns a tuple with the PersistentServerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsDeletePersistentServerResponse) GetPersistentServerIdOk() (*string, bool) {
	if o == nil || IsNil(o.PersistentServerId) {
		return nil, false
	}
	return o.PersistentServerId, true
}

// HasPersistentServerId returns a boolean if a field has been set.
func (o *ModelsDeletePersistentServerResponse) HasPersistentServerId() bool {
	if o != nil && !IsNil(o.PersistentServerId) {
		return true
	}

	return false
}

// SetPersistentServerId gets a reference to the given string and assigns it to the PersistentServerId field.
func (o *ModelsDeletePersistentServerResponse) SetPersistentServerId(v string) {
	o.PersistentServerId = &v
}

func (o ModelsDeletePersistentServerResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsDeletePersistentServerResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.PersistentServerId) {
		toSerialize["persistent_server_id"] = o.PersistentServerId
	}
	return toSerialize, nil
}

type NullableModelsDeletePersistentServerResponse struct {
	value *ModelsDeletePersistentServerResponse
	isSet bool
}

func (v NullableModelsDeletePersistentServerResponse) Get() *ModelsDeletePersistentServerResponse {
	return v.value
}

func (v *NullableModelsDeletePersistentServerResponse) Set(val *ModelsDeletePersistentServerResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsDeletePersistentServerResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsDeletePersistentServerResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsDeletePersistentServerResponse(val *ModelsDeletePersistentServerResponse) *NullableModelsDeletePersistentServerResponse {
	return &NullableModelsDeletePersistentServerResponse{value: val, isSet: true}
}

func (v NullableModelsDeletePersistentServerResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsDeletePersistentServerResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
