/*
SimpleCloud Controller API

API for SimpleCloud Controller

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplecloud

import (
	"encoding/json"
)

// checks if the ModelsLogEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsLogEntry{}

// ModelsLogEntry struct for ModelsLogEntry
type ModelsLogEntry struct {
	Message              *string  `json:"message,omitempty"`
	NumericalId          *int32   `json:"numerical_id,omitempty"`
	PersistentServerId   *string  `json:"persistent_server_id,omitempty"`
	PersistentServerName *string  `json:"persistent_server_name,omitempty"`
	Sequence             *int32   `json:"sequence,omitempty"`
	ServerGroupId        *string  `json:"server_group_id,omitempty"`
	ServerGroupName      *string  `json:"server_group_name,omitempty"`
	ServerId             *string  `json:"server_id,omitempty"`
	ServerName           *string  `json:"server_name,omitempty"`
	ServerType           *string  `json:"server_type,omitempty"`
	ServerhostId         *string  `json:"serverhost_id,omitempty"`
	ServerhostName       *string  `json:"serverhost_name,omitempty"`
	Severity             *string  `json:"severity,omitempty"`
	Tags                 []string `json:"tags,omitempty"`
	Timestamp            *string  `json:"timestamp,omitempty"`
	TraceId              *string  `json:"trace_id,omitempty"`
}

// NewModelsLogEntry instantiates a new ModelsLogEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsLogEntry() *ModelsLogEntry {
	this := ModelsLogEntry{}
	return &this
}

// NewModelsLogEntryWithDefaults instantiates a new ModelsLogEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsLogEntryWithDefaults() *ModelsLogEntry {
	this := ModelsLogEntry{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ModelsLogEntry) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsLogEntry) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ModelsLogEntry) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ModelsLogEntry) SetMessage(v string) {
	o.Message = &v
}

// GetNumericalId returns the NumericalId field value if set, zero value otherwise.
func (o *ModelsLogEntry) GetNumericalId() int32 {
	if o == nil || IsNil(o.NumericalId) {
		var ret int32
		return ret
	}
	return *o.NumericalId
}

// GetNumericalIdOk returns a tuple with the NumericalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsLogEntry) GetNumericalIdOk() (*int32, bool) {
	if o == nil || IsNil(o.NumericalId) {
		return nil, false
	}
	return o.NumericalId, true
}

// HasNumericalId returns a boolean if a field has been set.
func (o *ModelsLogEntry) HasNumericalId() bool {
	if o != nil && !IsNil(o.NumericalId) {
		return true
	}

	return false
}

// SetNumericalId gets a reference to the given int32 and assigns it to the NumericalId field.
func (o *ModelsLogEntry) SetNumericalId(v int32) {
	o.NumericalId = &v
}

// GetPersistentServerId returns the PersistentServerId field value if set, zero value otherwise.
func (o *ModelsLogEntry) GetPersistentServerId() string {
	if o == nil || IsNil(o.PersistentServerId) {
		var ret string
		return ret
	}
	return *o.PersistentServerId
}

// GetPersistentServerIdOk returns a tuple with the PersistentServerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsLogEntry) GetPersistentServerIdOk() (*string, bool) {
	if o == nil || IsNil(o.PersistentServerId) {
		return nil, false
	}
	return o.PersistentServerId, true
}

// HasPersistentServerId returns a boolean if a field has been set.
func (o *ModelsLogEntry) HasPersistentServerId() bool {
	if o != nil && !IsNil(o.PersistentServerId) {
		return true
	}

	return false
}

// SetPersistentServerId gets a reference to the given string and assigns it to the PersistentServerId field.
func (o *ModelsLogEntry) SetPersistentServerId(v string) {
	o.PersistentServerId = &v
}

// GetPersistentServerName returns the PersistentServerName field value if set, zero value otherwise.
func (o *ModelsLogEntry) GetPersistentServerName() string {
	if o == nil || IsNil(o.PersistentServerName) {
		var ret string
		return ret
	}
	return *o.PersistentServerName
}

// GetPersistentServerNameOk returns a tuple with the PersistentServerName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsLogEntry) GetPersistentServerNameOk() (*string, bool) {
	if o == nil || IsNil(o.PersistentServerName) {
		return nil, false
	}
	return o.PersistentServerName, true
}

// HasPersistentServerName returns a boolean if a field has been set.
func (o *ModelsLogEntry) HasPersistentServerName() bool {
	if o != nil && !IsNil(o.PersistentServerName) {
		return true
	}

	return false
}

// SetPersistentServerName gets a reference to the given string and assigns it to the PersistentServerName field.
func (o *ModelsLogEntry) SetPersistentServerName(v string) {
	o.PersistentServerName = &v
}

// GetSequence returns the Sequence field value if set, zero value otherwise.
func (o *ModelsLogEntry) GetSequence() int32 {
	if o == nil || IsNil(o.Sequence) {
		var ret int32
		return ret
	}
	return *o.Sequence
}

// GetSequenceOk returns a tuple with the Sequence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsLogEntry) GetSequenceOk() (*int32, bool) {
	if o == nil || IsNil(o.Sequence) {
		return nil, false
	}
	return o.Sequence, true
}

// HasSequence returns a boolean if a field has been set.
func (o *ModelsLogEntry) HasSequence() bool {
	if o != nil && !IsNil(o.Sequence) {
		return true
	}

	return false
}

// SetSequence gets a reference to the given int32 and assigns it to the Sequence field.
func (o *ModelsLogEntry) SetSequence(v int32) {
	o.Sequence = &v
}

// GetServerGroupId returns the ServerGroupId field value if set, zero value otherwise.
func (o *ModelsLogEntry) GetServerGroupId() string {
	if o == nil || IsNil(o.ServerGroupId) {
		var ret string
		return ret
	}
	return *o.ServerGroupId
}

// GetServerGroupIdOk returns a tuple with the ServerGroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsLogEntry) GetServerGroupIdOk() (*string, bool) {
	if o == nil || IsNil(o.ServerGroupId) {
		return nil, false
	}
	return o.ServerGroupId, true
}

// HasServerGroupId returns a boolean if a field has been set.
func (o *ModelsLogEntry) HasServerGroupId() bool {
	if o != nil && !IsNil(o.ServerGroupId) {
		return true
	}

	return false
}

// SetServerGroupId gets a reference to the given string and assigns it to the ServerGroupId field.
func (o *ModelsLogEntry) SetServerGroupId(v string) {
	o.ServerGroupId = &v
}

// GetServerGroupName returns the ServerGroupName field value if set, zero value otherwise.
func (o *ModelsLogEntry) GetServerGroupName() string {
	if o == nil || IsNil(o.ServerGroupName) {
		var ret string
		return ret
	}
	return *o.ServerGroupName
}

// GetServerGroupNameOk returns a tuple with the ServerGroupName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsLogEntry) GetServerGroupNameOk() (*string, bool) {
	if o == nil || IsNil(o.ServerGroupName) {
		return nil, false
	}
	return o.ServerGroupName, true
}

// HasServerGroupName returns a boolean if a field has been set.
func (o *ModelsLogEntry) HasServerGroupName() bool {
	if o != nil && !IsNil(o.ServerGroupName) {
		return true
	}

	return false
}

// SetServerGroupName gets a reference to the given string and assigns it to the ServerGroupName field.
func (o *ModelsLogEntry) SetServerGroupName(v string) {
	o.ServerGroupName = &v
}

// GetServerId returns the ServerId field value if set, zero value otherwise.
func (o *ModelsLogEntry) GetServerId() string {
	if o == nil || IsNil(o.ServerId) {
		var ret string
		return ret
	}
	return *o.ServerId
}

// GetServerIdOk returns a tuple with the ServerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsLogEntry) GetServerIdOk() (*string, bool) {
	if o == nil || IsNil(o.ServerId) {
		return nil, false
	}
	return o.ServerId, true
}

// HasServerId returns a boolean if a field has been set.
func (o *ModelsLogEntry) HasServerId() bool {
	if o != nil && !IsNil(o.ServerId) {
		return true
	}

	return false
}

// SetServerId gets a reference to the given string and assigns it to the ServerId field.
func (o *ModelsLogEntry) SetServerId(v string) {
	o.ServerId = &v
}

// GetServerName returns the ServerName field value if set, zero value otherwise.
func (o *ModelsLogEntry) GetServerName() string {
	if o == nil || IsNil(o.ServerName) {
		var ret string
		return ret
	}
	return *o.ServerName
}

// GetServerNameOk returns a tuple with the ServerName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsLogEntry) GetServerNameOk() (*string, bool) {
	if o == nil || IsNil(o.ServerName) {
		return nil, false
	}
	return o.ServerName, true
}

// HasServerName returns a boolean if a field has been set.
func (o *ModelsLogEntry) HasServerName() bool {
	if o != nil && !IsNil(o.ServerName) {
		return true
	}

	return false
}

// SetServerName gets a reference to the given string and assigns it to the ServerName field.
func (o *ModelsLogEntry) SetServerName(v string) {
	o.ServerName = &v
}

// GetServerType returns the ServerType field value if set, zero value otherwise.
func (o *ModelsLogEntry) GetServerType() string {
	if o == nil || IsNil(o.ServerType) {
		var ret string
		return ret
	}
	return *o.ServerType
}

// GetServerTypeOk returns a tuple with the ServerType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsLogEntry) GetServerTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ServerType) {
		return nil, false
	}
	return o.ServerType, true
}

// HasServerType returns a boolean if a field has been set.
func (o *ModelsLogEntry) HasServerType() bool {
	if o != nil && !IsNil(o.ServerType) {
		return true
	}

	return false
}

// SetServerType gets a reference to the given string and assigns it to the ServerType field.
func (o *ModelsLogEntry) SetServerType(v string) {
	o.ServerType = &v
}

// GetServerhostId returns the ServerhostId field value if set, zero value otherwise.
func (o *ModelsLogEntry) GetServerhostId() string {
	if o == nil || IsNil(o.ServerhostId) {
		var ret string
		return ret
	}
	return *o.ServerhostId
}

// GetServerhostIdOk returns a tuple with the ServerhostId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsLogEntry) GetServerhostIdOk() (*string, bool) {
	if o == nil || IsNil(o.ServerhostId) {
		return nil, false
	}
	return o.ServerhostId, true
}

// HasServerhostId returns a boolean if a field has been set.
func (o *ModelsLogEntry) HasServerhostId() bool {
	if o != nil && !IsNil(o.ServerhostId) {
		return true
	}

	return false
}

// SetServerhostId gets a reference to the given string and assigns it to the ServerhostId field.
func (o *ModelsLogEntry) SetServerhostId(v string) {
	o.ServerhostId = &v
}

// GetServerhostName returns the ServerhostName field value if set, zero value otherwise.
func (o *ModelsLogEntry) GetServerhostName() string {
	if o == nil || IsNil(o.ServerhostName) {
		var ret string
		return ret
	}
	return *o.ServerhostName
}

// GetServerhostNameOk returns a tuple with the ServerhostName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsLogEntry) GetServerhostNameOk() (*string, bool) {
	if o == nil || IsNil(o.ServerhostName) {
		return nil, false
	}
	return o.ServerhostName, true
}

// HasServerhostName returns a boolean if a field has been set.
func (o *ModelsLogEntry) HasServerhostName() bool {
	if o != nil && !IsNil(o.ServerhostName) {
		return true
	}

	return false
}

// SetServerhostName gets a reference to the given string and assigns it to the ServerhostName field.
func (o *ModelsLogEntry) SetServerhostName(v string) {
	o.ServerhostName = &v
}

// GetSeverity returns the Severity field value if set, zero value otherwise.
func (o *ModelsLogEntry) GetSeverity() string {
	if o == nil || IsNil(o.Severity) {
		var ret string
		return ret
	}
	return *o.Severity
}

// GetSeverityOk returns a tuple with the Severity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsLogEntry) GetSeverityOk() (*string, bool) {
	if o == nil || IsNil(o.Severity) {
		return nil, false
	}
	return o.Severity, true
}

// HasSeverity returns a boolean if a field has been set.
func (o *ModelsLogEntry) HasSeverity() bool {
	if o != nil && !IsNil(o.Severity) {
		return true
	}

	return false
}

// SetSeverity gets a reference to the given string and assigns it to the Severity field.
func (o *ModelsLogEntry) SetSeverity(v string) {
	o.Severity = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *ModelsLogEntry) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsLogEntry) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *ModelsLogEntry) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *ModelsLogEntry) SetTags(v []string) {
	o.Tags = v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *ModelsLogEntry) GetTimestamp() string {
	if o == nil || IsNil(o.Timestamp) {
		var ret string
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsLogEntry) GetTimestampOk() (*string, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *ModelsLogEntry) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given string and assigns it to the Timestamp field.
func (o *ModelsLogEntry) SetTimestamp(v string) {
	o.Timestamp = &v
}

// GetTraceId returns the TraceId field value if set, zero value otherwise.
func (o *ModelsLogEntry) GetTraceId() string {
	if o == nil || IsNil(o.TraceId) {
		var ret string
		return ret
	}
	return *o.TraceId
}

// GetTraceIdOk returns a tuple with the TraceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsLogEntry) GetTraceIdOk() (*string, bool) {
	if o == nil || IsNil(o.TraceId) {
		return nil, false
	}
	return o.TraceId, true
}

// HasTraceId returns a boolean if a field has been set.
func (o *ModelsLogEntry) HasTraceId() bool {
	if o != nil && !IsNil(o.TraceId) {
		return true
	}

	return false
}

// SetTraceId gets a reference to the given string and assigns it to the TraceId field.
func (o *ModelsLogEntry) SetTraceId(v string) {
	o.TraceId = &v
}

func (o ModelsLogEntry) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsLogEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.NumericalId) {
		toSerialize["numerical_id"] = o.NumericalId
	}
	if !IsNil(o.PersistentServerId) {
		toSerialize["persistent_server_id"] = o.PersistentServerId
	}
	if !IsNil(o.PersistentServerName) {
		toSerialize["persistent_server_name"] = o.PersistentServerName
	}
	if !IsNil(o.Sequence) {
		toSerialize["sequence"] = o.Sequence
	}
	if !IsNil(o.ServerGroupId) {
		toSerialize["server_group_id"] = o.ServerGroupId
	}
	if !IsNil(o.ServerGroupName) {
		toSerialize["server_group_name"] = o.ServerGroupName
	}
	if !IsNil(o.ServerId) {
		toSerialize["server_id"] = o.ServerId
	}
	if !IsNil(o.ServerName) {
		toSerialize["server_name"] = o.ServerName
	}
	if !IsNil(o.ServerType) {
		toSerialize["server_type"] = o.ServerType
	}
	if !IsNil(o.ServerhostId) {
		toSerialize["serverhost_id"] = o.ServerhostId
	}
	if !IsNil(o.ServerhostName) {
		toSerialize["serverhost_name"] = o.ServerhostName
	}
	if !IsNil(o.Severity) {
		toSerialize["severity"] = o.Severity
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	if !IsNil(o.TraceId) {
		toSerialize["trace_id"] = o.TraceId
	}
	return toSerialize, nil
}

type NullableModelsLogEntry struct {
	value *ModelsLogEntry
	isSet bool
}

func (v NullableModelsLogEntry) Get() *ModelsLogEntry {
	return v.value
}

func (v *NullableModelsLogEntry) Set(val *ModelsLogEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsLogEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsLogEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsLogEntry(val *ModelsLogEntry) *NullableModelsLogEntry {
	return &NullableModelsLogEntry{value: val, isSet: true}
}

func (v NullableModelsLogEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsLogEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
