/*
SimpleCloud Controller API

API for SimpleCloud Controller

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplecloud

import (
	"encoding/json"
)

// checks if the ModelsDeactivateServerhostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsDeactivateServerhostRequest{}

// ModelsDeactivateServerhostRequest Request to deactivate or reactivate a serverhost
type ModelsDeactivateServerhostRequest struct {
	Deactivated *bool `json:"deactivated,omitempty"`
}

// NewModelsDeactivateServerhostRequest instantiates a new ModelsDeactivateServerhostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsDeactivateServerhostRequest() *ModelsDeactivateServerhostRequest {
	this := ModelsDeactivateServerhostRequest{}
	return &this
}

// NewModelsDeactivateServerhostRequestWithDefaults instantiates a new ModelsDeactivateServerhostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsDeactivateServerhostRequestWithDefaults() *ModelsDeactivateServerhostRequest {
	this := ModelsDeactivateServerhostRequest{}
	return &this
}

// GetDeactivated returns the Deactivated field value if set, zero value otherwise.
func (o *ModelsDeactivateServerhostRequest) GetDeactivated() bool {
	if o == nil || IsNil(o.Deactivated) {
		var ret bool
		return ret
	}
	return *o.Deactivated
}

// GetDeactivatedOk returns a tuple with the Deactivated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsDeactivateServerhostRequest) GetDeactivatedOk() (*bool, bool) {
	if o == nil || IsNil(o.Deactivated) {
		return nil, false
	}
	return o.Deactivated, true
}

// HasDeactivated returns a boolean if a field has been set.
func (o *ModelsDeactivateServerhostRequest) HasDeactivated() bool {
	if o != nil && !IsNil(o.Deactivated) {
		return true
	}

	return false
}

// SetDeactivated gets a reference to the given bool and assigns it to the Deactivated field.
func (o *ModelsDeactivateServerhostRequest) SetDeactivated(v bool) {
	o.Deactivated = &v
}

func (o ModelsDeactivateServerhostRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsDeactivateServerhostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Deactivated) {
		toSerialize["deactivated"] = o.Deactivated
	}
	return toSerialize, nil
}

type NullableModelsDeactivateServerhostRequest struct {
	value *ModelsDeactivateServerhostRequest
	isSet bool
}

func (v NullableModelsDeactivateServerhostRequest) Get() *ModelsDeactivateServerhostRequest {
	return v.value
}

func (v *NullableModelsDeactivateServerhostRequest) Set(val *ModelsDeactivateServerhostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsDeactivateServerhostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsDeactivateServerhostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsDeactivateServerhostRequest(val *ModelsDeactivateServerhostRequest) *NullableModelsDeactivateServerhostRequest {
	return &NullableModelsDeactivateServerhostRequest{value: val, isSet: true}
}

func (v NullableModelsDeactivateServerhostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsDeactivateServerhostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
