/*
SimpleCloud Controller API

API for SimpleCloud Controller

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplecloud

import (
	"encoding/json"
)

// checks if the ModelsServerGroupStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsServerGroupStats{}

// ModelsServerGroupStats Runtime statistics for a server group
type ModelsServerGroupStats struct {
	OnlinePlayers  *int32           `json:"online_players,omitempty"`
	ServersByState map[string]int32 `json:"servers_by_state,omitempty"`
	TotalServers   *int32           `json:"total_servers,omitempty"`
}

// NewModelsServerGroupStats instantiates a new ModelsServerGroupStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsServerGroupStats() *ModelsServerGroupStats {
	this := ModelsServerGroupStats{}
	return &this
}

// NewModelsServerGroupStatsWithDefaults instantiates a new ModelsServerGroupStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsServerGroupStatsWithDefaults() *ModelsServerGroupStats {
	this := ModelsServerGroupStats{}
	return &this
}

// GetOnlinePlayers returns the OnlinePlayers field value if set, zero value otherwise.
func (o *ModelsServerGroupStats) GetOnlinePlayers() int32 {
	if o == nil || IsNil(o.OnlinePlayers) {
		var ret int32
		return ret
	}
	return *o.OnlinePlayers
}

// GetOnlinePlayersOk returns a tuple with the OnlinePlayers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsServerGroupStats) GetOnlinePlayersOk() (*int32, bool) {
	if o == nil || IsNil(o.OnlinePlayers) {
		return nil, false
	}
	return o.OnlinePlayers, true
}

// HasOnlinePlayers returns a boolean if a field has been set.
func (o *ModelsServerGroupStats) HasOnlinePlayers() bool {
	if o != nil && !IsNil(o.OnlinePlayers) {
		return true
	}

	return false
}

// SetOnlinePlayers gets a reference to the given int32 and assigns it to the OnlinePlayers field.
func (o *ModelsServerGroupStats) SetOnlinePlayers(v int32) {
	o.OnlinePlayers = &v
}

// GetServersByState returns the ServersByState field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelsServerGroupStats) GetServersByState() map[string]int32 {
	if o == nil {
		var ret map[string]int32
		return ret
	}
	return o.ServersByState
}

// GetServersByStateOk returns a tuple with the ServersByState field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelsServerGroupStats) GetServersByStateOk() (*map[string]int32, bool) {
	if o == nil || IsNil(o.ServersByState) {
		return nil, false
	}
	return &o.ServersByState, true
}

// HasServersByState returns a boolean if a field has been set.
func (o *ModelsServerGroupStats) HasServersByState() bool {
	if o != nil && !IsNil(o.ServersByState) {
		return true
	}

	return false
}

// SetServersByState gets a reference to the given map[string]int32 and assigns it to the ServersByState field.
func (o *ModelsServerGroupStats) SetServersByState(v map[string]int32) {
	o.ServersByState = v
}

// GetTotalServers returns the TotalServers field value if set, zero value otherwise.
func (o *ModelsServerGroupStats) GetTotalServers() int32 {
	if o == nil || IsNil(o.TotalServers) {
		var ret int32
		return ret
	}
	return *o.TotalServers
}

// GetTotalServersOk returns a tuple with the TotalServers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsServerGroupStats) GetTotalServersOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalServers) {
		return nil, false
	}
	return o.TotalServers, true
}

// HasTotalServers returns a boolean if a field has been set.
func (o *ModelsServerGroupStats) HasTotalServers() bool {
	if o != nil && !IsNil(o.TotalServers) {
		return true
	}

	return false
}

// SetTotalServers gets a reference to the given int32 and assigns it to the TotalServers field.
func (o *ModelsServerGroupStats) SetTotalServers(v int32) {
	o.TotalServers = &v
}

func (o ModelsServerGroupStats) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsServerGroupStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OnlinePlayers) {
		toSerialize["online_players"] = o.OnlinePlayers
	}
	if o.ServersByState != nil {
		toSerialize["servers_by_state"] = o.ServersByState
	}
	if !IsNil(o.TotalServers) {
		toSerialize["total_servers"] = o.TotalServers
	}
	return toSerialize, nil
}

type NullableModelsServerGroupStats struct {
	value *ModelsServerGroupStats
	isSet bool
}

func (v NullableModelsServerGroupStats) Get() *ModelsServerGroupStats {
	return v.value
}

func (v *NullableModelsServerGroupStats) Set(val *ModelsServerGroupStats) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsServerGroupStats) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsServerGroupStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsServerGroupStats(val *ModelsServerGroupStats) *NullableModelsServerGroupStats {
	return &NullableModelsServerGroupStats{value: val, isSet: true}
}

func (v NullableModelsServerGroupStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsServerGroupStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
