/*
SimpleCloud Controller API

API for SimpleCloud Controller

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplecloud

import (
	"encoding/json"
)

// checks if the ModelsUpdatePersistentServerRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsUpdatePersistentServerRequest{}

// ModelsUpdatePersistentServerRequest Request to update an existing persistent server
type ModelsUpdatePersistentServerRequest struct {
	Active       *bool                  `json:"active,omitempty"`
	MaxMemory    *int32                 `json:"max_memory,omitempty"`
	MaxPlayers   *int32                 `json:"max_players,omitempty"`
	MinMemory    *int32                 `json:"min_memory,omitempty"`
	Name         *string                `json:"name,omitempty"`
	Priority     *int32                 `json:"priority,omitempty"`
	Properties   map[string]interface{} `json:"properties,omitempty"`
	ServerhostId *string                `json:"serverhost_id,omitempty"`
	Source       *ModelsSourceConfig    `json:"source,omitempty"`
	Tags         []string               `json:"tags,omitempty"`
	Type         *string                `json:"type,omitempty"`
	Workflows    *ModelsWorkflowsConfig `json:"workflows,omitempty"`
}

// NewModelsUpdatePersistentServerRequest instantiates a new ModelsUpdatePersistentServerRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsUpdatePersistentServerRequest() *ModelsUpdatePersistentServerRequest {
	this := ModelsUpdatePersistentServerRequest{}
	return &this
}

// NewModelsUpdatePersistentServerRequestWithDefaults instantiates a new ModelsUpdatePersistentServerRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsUpdatePersistentServerRequestWithDefaults() *ModelsUpdatePersistentServerRequest {
	this := ModelsUpdatePersistentServerRequest{}
	return &this
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *ModelsUpdatePersistentServerRequest) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsUpdatePersistentServerRequest) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *ModelsUpdatePersistentServerRequest) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *ModelsUpdatePersistentServerRequest) SetActive(v bool) {
	o.Active = &v
}

// GetMaxMemory returns the MaxMemory field value if set, zero value otherwise.
func (o *ModelsUpdatePersistentServerRequest) GetMaxMemory() int32 {
	if o == nil || IsNil(o.MaxMemory) {
		var ret int32
		return ret
	}
	return *o.MaxMemory
}

// GetMaxMemoryOk returns a tuple with the MaxMemory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsUpdatePersistentServerRequest) GetMaxMemoryOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxMemory) {
		return nil, false
	}
	return o.MaxMemory, true
}

// HasMaxMemory returns a boolean if a field has been set.
func (o *ModelsUpdatePersistentServerRequest) HasMaxMemory() bool {
	if o != nil && !IsNil(o.MaxMemory) {
		return true
	}

	return false
}

// SetMaxMemory gets a reference to the given int32 and assigns it to the MaxMemory field.
func (o *ModelsUpdatePersistentServerRequest) SetMaxMemory(v int32) {
	o.MaxMemory = &v
}

// GetMaxPlayers returns the MaxPlayers field value if set, zero value otherwise.
func (o *ModelsUpdatePersistentServerRequest) GetMaxPlayers() int32 {
	if o == nil || IsNil(o.MaxPlayers) {
		var ret int32
		return ret
	}
	return *o.MaxPlayers
}

// GetMaxPlayersOk returns a tuple with the MaxPlayers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsUpdatePersistentServerRequest) GetMaxPlayersOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxPlayers) {
		return nil, false
	}
	return o.MaxPlayers, true
}

// HasMaxPlayers returns a boolean if a field has been set.
func (o *ModelsUpdatePersistentServerRequest) HasMaxPlayers() bool {
	if o != nil && !IsNil(o.MaxPlayers) {
		return true
	}

	return false
}

// SetMaxPlayers gets a reference to the given int32 and assigns it to the MaxPlayers field.
func (o *ModelsUpdatePersistentServerRequest) SetMaxPlayers(v int32) {
	o.MaxPlayers = &v
}

// GetMinMemory returns the MinMemory field value if set, zero value otherwise.
func (o *ModelsUpdatePersistentServerRequest) GetMinMemory() int32 {
	if o == nil || IsNil(o.MinMemory) {
		var ret int32
		return ret
	}
	return *o.MinMemory
}

// GetMinMemoryOk returns a tuple with the MinMemory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsUpdatePersistentServerRequest) GetMinMemoryOk() (*int32, bool) {
	if o == nil || IsNil(o.MinMemory) {
		return nil, false
	}
	return o.MinMemory, true
}

// HasMinMemory returns a boolean if a field has been set.
func (o *ModelsUpdatePersistentServerRequest) HasMinMemory() bool {
	if o != nil && !IsNil(o.MinMemory) {
		return true
	}

	return false
}

// SetMinMemory gets a reference to the given int32 and assigns it to the MinMemory field.
func (o *ModelsUpdatePersistentServerRequest) SetMinMemory(v int32) {
	o.MinMemory = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ModelsUpdatePersistentServerRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsUpdatePersistentServerRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ModelsUpdatePersistentServerRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ModelsUpdatePersistentServerRequest) SetName(v string) {
	o.Name = &v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *ModelsUpdatePersistentServerRequest) GetPriority() int32 {
	if o == nil || IsNil(o.Priority) {
		var ret int32
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsUpdatePersistentServerRequest) GetPriorityOk() (*int32, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *ModelsUpdatePersistentServerRequest) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given int32 and assigns it to the Priority field.
func (o *ModelsUpdatePersistentServerRequest) SetPriority(v int32) {
	o.Priority = &v
}

// GetProperties returns the Properties field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelsUpdatePersistentServerRequest) GetProperties() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelsUpdatePersistentServerRequest) GetPropertiesOk() (*map[string]interface{}, bool) {
	if o == nil || IsNil(o.Properties) {
		return nil, false
	}
	return &o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *ModelsUpdatePersistentServerRequest) HasProperties() bool {
	if o != nil && !IsNil(o.Properties) {
		return true
	}

	return false
}

// SetProperties gets a reference to the given map[string]interface{} and assigns it to the Properties field.
func (o *ModelsUpdatePersistentServerRequest) SetProperties(v map[string]interface{}) {
	o.Properties = v
}

// GetServerhostId returns the ServerhostId field value if set, zero value otherwise.
func (o *ModelsUpdatePersistentServerRequest) GetServerhostId() string {
	if o == nil || IsNil(o.ServerhostId) {
		var ret string
		return ret
	}
	return *o.ServerhostId
}

// GetServerhostIdOk returns a tuple with the ServerhostId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsUpdatePersistentServerRequest) GetServerhostIdOk() (*string, bool) {
	if o == nil || IsNil(o.ServerhostId) {
		return nil, false
	}
	return o.ServerhostId, true
}

// HasServerhostId returns a boolean if a field has been set.
func (o *ModelsUpdatePersistentServerRequest) HasServerhostId() bool {
	if o != nil && !IsNil(o.ServerhostId) {
		return true
	}

	return false
}

// SetServerhostId gets a reference to the given string and assigns it to the ServerhostId field.
func (o *ModelsUpdatePersistentServerRequest) SetServerhostId(v string) {
	o.ServerhostId = &v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *ModelsUpdatePersistentServerRequest) GetSource() ModelsSourceConfig {
	if o == nil || IsNil(o.Source) {
		var ret ModelsSourceConfig
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsUpdatePersistentServerRequest) GetSourceOk() (*ModelsSourceConfig, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *ModelsUpdatePersistentServerRequest) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given ModelsSourceConfig and assigns it to the Source field.
func (o *ModelsUpdatePersistentServerRequest) SetSource(v ModelsSourceConfig) {
	o.Source = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *ModelsUpdatePersistentServerRequest) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsUpdatePersistentServerRequest) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *ModelsUpdatePersistentServerRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *ModelsUpdatePersistentServerRequest) SetTags(v []string) {
	o.Tags = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ModelsUpdatePersistentServerRequest) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsUpdatePersistentServerRequest) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ModelsUpdatePersistentServerRequest) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ModelsUpdatePersistentServerRequest) SetType(v string) {
	o.Type = &v
}

// GetWorkflows returns the Workflows field value if set, zero value otherwise.
func (o *ModelsUpdatePersistentServerRequest) GetWorkflows() ModelsWorkflowsConfig {
	if o == nil || IsNil(o.Workflows) {
		var ret ModelsWorkflowsConfig
		return ret
	}
	return *o.Workflows
}

// GetWorkflowsOk returns a tuple with the Workflows field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsUpdatePersistentServerRequest) GetWorkflowsOk() (*ModelsWorkflowsConfig, bool) {
	if o == nil || IsNil(o.Workflows) {
		return nil, false
	}
	return o.Workflows, true
}

// HasWorkflows returns a boolean if a field has been set.
func (o *ModelsUpdatePersistentServerRequest) HasWorkflows() bool {
	if o != nil && !IsNil(o.Workflows) {
		return true
	}

	return false
}

// SetWorkflows gets a reference to the given ModelsWorkflowsConfig and assigns it to the Workflows field.
func (o *ModelsUpdatePersistentServerRequest) SetWorkflows(v ModelsWorkflowsConfig) {
	o.Workflows = &v
}

func (o ModelsUpdatePersistentServerRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsUpdatePersistentServerRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	if !IsNil(o.MaxMemory) {
		toSerialize["max_memory"] = o.MaxMemory
	}
	if !IsNil(o.MaxPlayers) {
		toSerialize["max_players"] = o.MaxPlayers
	}
	if !IsNil(o.MinMemory) {
		toSerialize["min_memory"] = o.MinMemory
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}
	if o.Properties != nil {
		toSerialize["properties"] = o.Properties
	}
	if !IsNil(o.ServerhostId) {
		toSerialize["serverhost_id"] = o.ServerhostId
	}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Workflows) {
		toSerialize["workflows"] = o.Workflows
	}
	return toSerialize, nil
}

type NullableModelsUpdatePersistentServerRequest struct {
	value *ModelsUpdatePersistentServerRequest
	isSet bool
}

func (v NullableModelsUpdatePersistentServerRequest) Get() *ModelsUpdatePersistentServerRequest {
	return v.value
}

func (v *NullableModelsUpdatePersistentServerRequest) Set(val *ModelsUpdatePersistentServerRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsUpdatePersistentServerRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsUpdatePersistentServerRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsUpdatePersistentServerRequest(val *ModelsUpdatePersistentServerRequest) *NullableModelsUpdatePersistentServerRequest {
	return &NullableModelsUpdatePersistentServerRequest{value: val, isSet: true}
}

func (v NullableModelsUpdatePersistentServerRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsUpdatePersistentServerRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
