/*
SimpleCloud Controller API

API for SimpleCloud Controller

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplecloud

import (
	"encoding/json"
)

// checks if the ModelsDeletePluginCollectionAssignmentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsDeletePluginCollectionAssignmentResponse{}

// ModelsDeletePluginCollectionAssignmentResponse struct for ModelsDeletePluginCollectionAssignmentResponse
type ModelsDeletePluginCollectionAssignmentResponse struct {
	AssignmentId *string `json:"assignment_id,omitempty"`
	Message      *string `json:"message,omitempty"`
}

// NewModelsDeletePluginCollectionAssignmentResponse instantiates a new ModelsDeletePluginCollectionAssignmentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsDeletePluginCollectionAssignmentResponse() *ModelsDeletePluginCollectionAssignmentResponse {
	this := ModelsDeletePluginCollectionAssignmentResponse{}
	return &this
}

// NewModelsDeletePluginCollectionAssignmentResponseWithDefaults instantiates a new ModelsDeletePluginCollectionAssignmentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsDeletePluginCollectionAssignmentResponseWithDefaults() *ModelsDeletePluginCollectionAssignmentResponse {
	this := ModelsDeletePluginCollectionAssignmentResponse{}
	return &this
}

// GetAssignmentId returns the AssignmentId field value if set, zero value otherwise.
func (o *ModelsDeletePluginCollectionAssignmentResponse) GetAssignmentId() string {
	if o == nil || IsNil(o.AssignmentId) {
		var ret string
		return ret
	}
	return *o.AssignmentId
}

// GetAssignmentIdOk returns a tuple with the AssignmentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsDeletePluginCollectionAssignmentResponse) GetAssignmentIdOk() (*string, bool) {
	if o == nil || IsNil(o.AssignmentId) {
		return nil, false
	}
	return o.AssignmentId, true
}

// HasAssignmentId returns a boolean if a field has been set.
func (o *ModelsDeletePluginCollectionAssignmentResponse) HasAssignmentId() bool {
	if o != nil && !IsNil(o.AssignmentId) {
		return true
	}

	return false
}

// SetAssignmentId gets a reference to the given string and assigns it to the AssignmentId field.
func (o *ModelsDeletePluginCollectionAssignmentResponse) SetAssignmentId(v string) {
	o.AssignmentId = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ModelsDeletePluginCollectionAssignmentResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsDeletePluginCollectionAssignmentResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ModelsDeletePluginCollectionAssignmentResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ModelsDeletePluginCollectionAssignmentResponse) SetMessage(v string) {
	o.Message = &v
}

func (o ModelsDeletePluginCollectionAssignmentResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsDeletePluginCollectionAssignmentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AssignmentId) {
		toSerialize["assignment_id"] = o.AssignmentId
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableModelsDeletePluginCollectionAssignmentResponse struct {
	value *ModelsDeletePluginCollectionAssignmentResponse
	isSet bool
}

func (v NullableModelsDeletePluginCollectionAssignmentResponse) Get() *ModelsDeletePluginCollectionAssignmentResponse {
	return v.value
}

func (v *NullableModelsDeletePluginCollectionAssignmentResponse) Set(val *ModelsDeletePluginCollectionAssignmentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsDeletePluginCollectionAssignmentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsDeletePluginCollectionAssignmentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsDeletePluginCollectionAssignmentResponse(val *ModelsDeletePluginCollectionAssignmentResponse) *NullableModelsDeletePluginCollectionAssignmentResponse {
	return &NullableModelsDeletePluginCollectionAssignmentResponse{value: val, isSet: true}
}

func (v NullableModelsDeletePluginCollectionAssignmentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsDeletePluginCollectionAssignmentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
