/*
SimpleCloud Controller API

API for SimpleCloud Controller

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplecloud

import (
	"encoding/json"
)

// checks if the ModelsRegisterEncryptionKeyResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsRegisterEncryptionKeyResponse{}

// ModelsRegisterEncryptionKeyResponse Response for registering the network shared public key
type ModelsRegisterEncryptionKeyResponse struct {
	Accepted       *bool   `json:"accepted,omitempty"`
	KeyFingerprint *string `json:"key_fingerprint,omitempty"`
	Message        *string `json:"message,omitempty"`
	PublicKeyPem   *string `json:"public_key_pem,omitempty"`
}

// NewModelsRegisterEncryptionKeyResponse instantiates a new ModelsRegisterEncryptionKeyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsRegisterEncryptionKeyResponse() *ModelsRegisterEncryptionKeyResponse {
	this := ModelsRegisterEncryptionKeyResponse{}
	return &this
}

// NewModelsRegisterEncryptionKeyResponseWithDefaults instantiates a new ModelsRegisterEncryptionKeyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsRegisterEncryptionKeyResponseWithDefaults() *ModelsRegisterEncryptionKeyResponse {
	this := ModelsRegisterEncryptionKeyResponse{}
	return &this
}

// GetAccepted returns the Accepted field value if set, zero value otherwise.
func (o *ModelsRegisterEncryptionKeyResponse) GetAccepted() bool {
	if o == nil || IsNil(o.Accepted) {
		var ret bool
		return ret
	}
	return *o.Accepted
}

// GetAcceptedOk returns a tuple with the Accepted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsRegisterEncryptionKeyResponse) GetAcceptedOk() (*bool, bool) {
	if o == nil || IsNil(o.Accepted) {
		return nil, false
	}
	return o.Accepted, true
}

// HasAccepted returns a boolean if a field has been set.
func (o *ModelsRegisterEncryptionKeyResponse) HasAccepted() bool {
	if o != nil && !IsNil(o.Accepted) {
		return true
	}

	return false
}

// SetAccepted gets a reference to the given bool and assigns it to the Accepted field.
func (o *ModelsRegisterEncryptionKeyResponse) SetAccepted(v bool) {
	o.Accepted = &v
}

// GetKeyFingerprint returns the KeyFingerprint field value if set, zero value otherwise.
func (o *ModelsRegisterEncryptionKeyResponse) GetKeyFingerprint() string {
	if o == nil || IsNil(o.KeyFingerprint) {
		var ret string
		return ret
	}
	return *o.KeyFingerprint
}

// GetKeyFingerprintOk returns a tuple with the KeyFingerprint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsRegisterEncryptionKeyResponse) GetKeyFingerprintOk() (*string, bool) {
	if o == nil || IsNil(o.KeyFingerprint) {
		return nil, false
	}
	return o.KeyFingerprint, true
}

// HasKeyFingerprint returns a boolean if a field has been set.
func (o *ModelsRegisterEncryptionKeyResponse) HasKeyFingerprint() bool {
	if o != nil && !IsNil(o.KeyFingerprint) {
		return true
	}

	return false
}

// SetKeyFingerprint gets a reference to the given string and assigns it to the KeyFingerprint field.
func (o *ModelsRegisterEncryptionKeyResponse) SetKeyFingerprint(v string) {
	o.KeyFingerprint = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ModelsRegisterEncryptionKeyResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsRegisterEncryptionKeyResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ModelsRegisterEncryptionKeyResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ModelsRegisterEncryptionKeyResponse) SetMessage(v string) {
	o.Message = &v
}

// GetPublicKeyPem returns the PublicKeyPem field value if set, zero value otherwise.
func (o *ModelsRegisterEncryptionKeyResponse) GetPublicKeyPem() string {
	if o == nil || IsNil(o.PublicKeyPem) {
		var ret string
		return ret
	}
	return *o.PublicKeyPem
}

// GetPublicKeyPemOk returns a tuple with the PublicKeyPem field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsRegisterEncryptionKeyResponse) GetPublicKeyPemOk() (*string, bool) {
	if o == nil || IsNil(o.PublicKeyPem) {
		return nil, false
	}
	return o.PublicKeyPem, true
}

// HasPublicKeyPem returns a boolean if a field has been set.
func (o *ModelsRegisterEncryptionKeyResponse) HasPublicKeyPem() bool {
	if o != nil && !IsNil(o.PublicKeyPem) {
		return true
	}

	return false
}

// SetPublicKeyPem gets a reference to the given string and assigns it to the PublicKeyPem field.
func (o *ModelsRegisterEncryptionKeyResponse) SetPublicKeyPem(v string) {
	o.PublicKeyPem = &v
}

func (o ModelsRegisterEncryptionKeyResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsRegisterEncryptionKeyResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Accepted) {
		toSerialize["accepted"] = o.Accepted
	}
	if !IsNil(o.KeyFingerprint) {
		toSerialize["key_fingerprint"] = o.KeyFingerprint
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.PublicKeyPem) {
		toSerialize["public_key_pem"] = o.PublicKeyPem
	}
	return toSerialize, nil
}

type NullableModelsRegisterEncryptionKeyResponse struct {
	value *ModelsRegisterEncryptionKeyResponse
	isSet bool
}

func (v NullableModelsRegisterEncryptionKeyResponse) Get() *ModelsRegisterEncryptionKeyResponse {
	return v.value
}

func (v *NullableModelsRegisterEncryptionKeyResponse) Set(val *ModelsRegisterEncryptionKeyResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsRegisterEncryptionKeyResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsRegisterEncryptionKeyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsRegisterEncryptionKeyResponse(val *ModelsRegisterEncryptionKeyResponse) *NullableModelsRegisterEncryptionKeyResponse {
	return &NullableModelsRegisterEncryptionKeyResponse{value: val, isSet: true}
}

func (v NullableModelsRegisterEncryptionKeyResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsRegisterEncryptionKeyResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
