/*
SimpleCloud Controller API

API for SimpleCloud Controller

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplecloud

import (
	"encoding/json"
)

// checks if the ModelsManualServerStartQueueItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsManualServerStartQueueItem{}

// ModelsManualServerStartQueueItem Detailed information for one persisted manual server start entry
type ModelsManualServerStartQueueItem struct {
	CreatedAt     *string `json:"created_at,omitempty"`
	FailureReason *string `json:"failure_reason,omitempty"`
	Id            *string `json:"id,omitempty"`
	Status        *string `json:"status,omitempty"`
}

// NewModelsManualServerStartQueueItem instantiates a new ModelsManualServerStartQueueItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsManualServerStartQueueItem() *ModelsManualServerStartQueueItem {
	this := ModelsManualServerStartQueueItem{}
	return &this
}

// NewModelsManualServerStartQueueItemWithDefaults instantiates a new ModelsManualServerStartQueueItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsManualServerStartQueueItemWithDefaults() *ModelsManualServerStartQueueItem {
	this := ModelsManualServerStartQueueItem{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ModelsManualServerStartQueueItem) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsManualServerStartQueueItem) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ModelsManualServerStartQueueItem) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *ModelsManualServerStartQueueItem) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetFailureReason returns the FailureReason field value if set, zero value otherwise.
func (o *ModelsManualServerStartQueueItem) GetFailureReason() string {
	if o == nil || IsNil(o.FailureReason) {
		var ret string
		return ret
	}
	return *o.FailureReason
}

// GetFailureReasonOk returns a tuple with the FailureReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsManualServerStartQueueItem) GetFailureReasonOk() (*string, bool) {
	if o == nil || IsNil(o.FailureReason) {
		return nil, false
	}
	return o.FailureReason, true
}

// HasFailureReason returns a boolean if a field has been set.
func (o *ModelsManualServerStartQueueItem) HasFailureReason() bool {
	if o != nil && !IsNil(o.FailureReason) {
		return true
	}

	return false
}

// SetFailureReason gets a reference to the given string and assigns it to the FailureReason field.
func (o *ModelsManualServerStartQueueItem) SetFailureReason(v string) {
	o.FailureReason = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ModelsManualServerStartQueueItem) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsManualServerStartQueueItem) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ModelsManualServerStartQueueItem) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ModelsManualServerStartQueueItem) SetId(v string) {
	o.Id = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ModelsManualServerStartQueueItem) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsManualServerStartQueueItem) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ModelsManualServerStartQueueItem) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ModelsManualServerStartQueueItem) SetStatus(v string) {
	o.Status = &v
}

func (o ModelsManualServerStartQueueItem) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsManualServerStartQueueItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.FailureReason) {
		toSerialize["failure_reason"] = o.FailureReason
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableModelsManualServerStartQueueItem struct {
	value *ModelsManualServerStartQueueItem
	isSet bool
}

func (v NullableModelsManualServerStartQueueItem) Get() *ModelsManualServerStartQueueItem {
	return v.value
}

func (v *NullableModelsManualServerStartQueueItem) Set(val *ModelsManualServerStartQueueItem) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsManualServerStartQueueItem) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsManualServerStartQueueItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsManualServerStartQueueItem(val *ModelsManualServerStartQueueItem) *NullableModelsManualServerStartQueueItem {
	return &NullableModelsManualServerStartQueueItem{value: val, isSet: true}
}

func (v NullableModelsManualServerStartQueueItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsManualServerStartQueueItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
