/*
SimpleCloud Controller API

API for SimpleCloud Controller

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplecloud

import (
	"encoding/json"
)

// checks if the ModelsPatchServerRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsPatchServerRequest{}

// ModelsPatchServerRequest Request to partially update an existing server
type ModelsPatchServerRequest struct {
	MaxMemory   *int32                 `json:"max_memory,omitempty"`
	MaxPlayers  *int32                 `json:"max_players,omitempty"`
	MinMemory   *int32                 `json:"min_memory,omitempty"`
	PlayerCount *int32                 `json:"player_count,omitempty"`
	Properties  map[string]interface{} `json:"properties,omitempty"`
	State       *string                `json:"state,omitempty"`
}

// NewModelsPatchServerRequest instantiates a new ModelsPatchServerRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsPatchServerRequest() *ModelsPatchServerRequest {
	this := ModelsPatchServerRequest{}
	return &this
}

// NewModelsPatchServerRequestWithDefaults instantiates a new ModelsPatchServerRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsPatchServerRequestWithDefaults() *ModelsPatchServerRequest {
	this := ModelsPatchServerRequest{}
	return &this
}

// GetMaxMemory returns the MaxMemory field value if set, zero value otherwise.
func (o *ModelsPatchServerRequest) GetMaxMemory() int32 {
	if o == nil || IsNil(o.MaxMemory) {
		var ret int32
		return ret
	}
	return *o.MaxMemory
}

// GetMaxMemoryOk returns a tuple with the MaxMemory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsPatchServerRequest) GetMaxMemoryOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxMemory) {
		return nil, false
	}
	return o.MaxMemory, true
}

// HasMaxMemory returns a boolean if a field has been set.
func (o *ModelsPatchServerRequest) HasMaxMemory() bool {
	if o != nil && !IsNil(o.MaxMemory) {
		return true
	}

	return false
}

// SetMaxMemory gets a reference to the given int32 and assigns it to the MaxMemory field.
func (o *ModelsPatchServerRequest) SetMaxMemory(v int32) {
	o.MaxMemory = &v
}

// GetMaxPlayers returns the MaxPlayers field value if set, zero value otherwise.
func (o *ModelsPatchServerRequest) GetMaxPlayers() int32 {
	if o == nil || IsNil(o.MaxPlayers) {
		var ret int32
		return ret
	}
	return *o.MaxPlayers
}

// GetMaxPlayersOk returns a tuple with the MaxPlayers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsPatchServerRequest) GetMaxPlayersOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxPlayers) {
		return nil, false
	}
	return o.MaxPlayers, true
}

// HasMaxPlayers returns a boolean if a field has been set.
func (o *ModelsPatchServerRequest) HasMaxPlayers() bool {
	if o != nil && !IsNil(o.MaxPlayers) {
		return true
	}

	return false
}

// SetMaxPlayers gets a reference to the given int32 and assigns it to the MaxPlayers field.
func (o *ModelsPatchServerRequest) SetMaxPlayers(v int32) {
	o.MaxPlayers = &v
}

// GetMinMemory returns the MinMemory field value if set, zero value otherwise.
func (o *ModelsPatchServerRequest) GetMinMemory() int32 {
	if o == nil || IsNil(o.MinMemory) {
		var ret int32
		return ret
	}
	return *o.MinMemory
}

// GetMinMemoryOk returns a tuple with the MinMemory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsPatchServerRequest) GetMinMemoryOk() (*int32, bool) {
	if o == nil || IsNil(o.MinMemory) {
		return nil, false
	}
	return o.MinMemory, true
}

// HasMinMemory returns a boolean if a field has been set.
func (o *ModelsPatchServerRequest) HasMinMemory() bool {
	if o != nil && !IsNil(o.MinMemory) {
		return true
	}

	return false
}

// SetMinMemory gets a reference to the given int32 and assigns it to the MinMemory field.
func (o *ModelsPatchServerRequest) SetMinMemory(v int32) {
	o.MinMemory = &v
}

// GetPlayerCount returns the PlayerCount field value if set, zero value otherwise.
func (o *ModelsPatchServerRequest) GetPlayerCount() int32 {
	if o == nil || IsNil(o.PlayerCount) {
		var ret int32
		return ret
	}
	return *o.PlayerCount
}

// GetPlayerCountOk returns a tuple with the PlayerCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsPatchServerRequest) GetPlayerCountOk() (*int32, bool) {
	if o == nil || IsNil(o.PlayerCount) {
		return nil, false
	}
	return o.PlayerCount, true
}

// HasPlayerCount returns a boolean if a field has been set.
func (o *ModelsPatchServerRequest) HasPlayerCount() bool {
	if o != nil && !IsNil(o.PlayerCount) {
		return true
	}

	return false
}

// SetPlayerCount gets a reference to the given int32 and assigns it to the PlayerCount field.
func (o *ModelsPatchServerRequest) SetPlayerCount(v int32) {
	o.PlayerCount = &v
}

// GetProperties returns the Properties field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelsPatchServerRequest) GetProperties() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelsPatchServerRequest) GetPropertiesOk() (*map[string]interface{}, bool) {
	if o == nil || IsNil(o.Properties) {
		return nil, false
	}
	return &o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *ModelsPatchServerRequest) HasProperties() bool {
	if o != nil && !IsNil(o.Properties) {
		return true
	}

	return false
}

// SetProperties gets a reference to the given map[string]interface{} and assigns it to the Properties field.
func (o *ModelsPatchServerRequest) SetProperties(v map[string]interface{}) {
	o.Properties = v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *ModelsPatchServerRequest) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsPatchServerRequest) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *ModelsPatchServerRequest) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *ModelsPatchServerRequest) SetState(v string) {
	o.State = &v
}

func (o ModelsPatchServerRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsPatchServerRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MaxMemory) {
		toSerialize["max_memory"] = o.MaxMemory
	}
	if !IsNil(o.MaxPlayers) {
		toSerialize["max_players"] = o.MaxPlayers
	}
	if !IsNil(o.MinMemory) {
		toSerialize["min_memory"] = o.MinMemory
	}
	if !IsNil(o.PlayerCount) {
		toSerialize["player_count"] = o.PlayerCount
	}
	if o.Properties != nil {
		toSerialize["properties"] = o.Properties
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	return toSerialize, nil
}

type NullableModelsPatchServerRequest struct {
	value *ModelsPatchServerRequest
	isSet bool
}

func (v NullableModelsPatchServerRequest) Get() *ModelsPatchServerRequest {
	return v.value
}

func (v *NullableModelsPatchServerRequest) Set(val *ModelsPatchServerRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsPatchServerRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsPatchServerRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsPatchServerRequest(val *ModelsPatchServerRequest) *NullableModelsPatchServerRequest {
	return &NullableModelsPatchServerRequest{value: val, isSet: true}
}

func (v NullableModelsPatchServerRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsPatchServerRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
