/*
SimpleCloud Controller API

API for SimpleCloud Controller

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplecloud

import (
	"encoding/json"
)

// checks if the ModelsCreateEncryptedSecretResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsCreateEncryptedSecretResponse{}

// ModelsCreateEncryptedSecretResponse Response for creating a client-encrypted network secret
type ModelsCreateEncryptedSecretResponse struct {
	Key      *string `json:"key,omitempty"`
	Message  *string `json:"message,omitempty"`
	SecretId *string `json:"secret_id,omitempty"`
}

// NewModelsCreateEncryptedSecretResponse instantiates a new ModelsCreateEncryptedSecretResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsCreateEncryptedSecretResponse() *ModelsCreateEncryptedSecretResponse {
	this := ModelsCreateEncryptedSecretResponse{}
	return &this
}

// NewModelsCreateEncryptedSecretResponseWithDefaults instantiates a new ModelsCreateEncryptedSecretResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsCreateEncryptedSecretResponseWithDefaults() *ModelsCreateEncryptedSecretResponse {
	this := ModelsCreateEncryptedSecretResponse{}
	return &this
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *ModelsCreateEncryptedSecretResponse) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsCreateEncryptedSecretResponse) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *ModelsCreateEncryptedSecretResponse) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *ModelsCreateEncryptedSecretResponse) SetKey(v string) {
	o.Key = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ModelsCreateEncryptedSecretResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsCreateEncryptedSecretResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ModelsCreateEncryptedSecretResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ModelsCreateEncryptedSecretResponse) SetMessage(v string) {
	o.Message = &v
}

// GetSecretId returns the SecretId field value if set, zero value otherwise.
func (o *ModelsCreateEncryptedSecretResponse) GetSecretId() string {
	if o == nil || IsNil(o.SecretId) {
		var ret string
		return ret
	}
	return *o.SecretId
}

// GetSecretIdOk returns a tuple with the SecretId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsCreateEncryptedSecretResponse) GetSecretIdOk() (*string, bool) {
	if o == nil || IsNil(o.SecretId) {
		return nil, false
	}
	return o.SecretId, true
}

// HasSecretId returns a boolean if a field has been set.
func (o *ModelsCreateEncryptedSecretResponse) HasSecretId() bool {
	if o != nil && !IsNil(o.SecretId) {
		return true
	}

	return false
}

// SetSecretId gets a reference to the given string and assigns it to the SecretId field.
func (o *ModelsCreateEncryptedSecretResponse) SetSecretId(v string) {
	o.SecretId = &v
}

func (o ModelsCreateEncryptedSecretResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsCreateEncryptedSecretResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.SecretId) {
		toSerialize["secret_id"] = o.SecretId
	}
	return toSerialize, nil
}

type NullableModelsCreateEncryptedSecretResponse struct {
	value *ModelsCreateEncryptedSecretResponse
	isSet bool
}

func (v NullableModelsCreateEncryptedSecretResponse) Get() *ModelsCreateEncryptedSecretResponse {
	return v.value
}

func (v *NullableModelsCreateEncryptedSecretResponse) Set(val *ModelsCreateEncryptedSecretResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsCreateEncryptedSecretResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsCreateEncryptedSecretResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsCreateEncryptedSecretResponse(val *ModelsCreateEncryptedSecretResponse) *NullableModelsCreateEncryptedSecretResponse {
	return &NullableModelsCreateEncryptedSecretResponse{value: val, isSet: true}
}

func (v NullableModelsCreateEncryptedSecretResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsCreateEncryptedSecretResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
