/*
SimpleCloud Controller API

API for SimpleCloud Controller

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplecloud

import (
	"encoding/json"
)

// checks if the ModelsBulkCreatePluginAssignmentsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsBulkCreatePluginAssignmentsRequest{}

// ModelsBulkCreatePluginAssignmentsRequest struct for ModelsBulkCreatePluginAssignmentsRequest
type ModelsBulkCreatePluginAssignmentsRequest struct {
	PersistentServerIds []string                     `json:"persistent_server_ids,omitempty"`
	Plugins             []ModelsPluginReferenceInput `json:"plugins,omitempty"`
	ServerGroupIds      []string                     `json:"server_group_ids,omitempty"`
}

// NewModelsBulkCreatePluginAssignmentsRequest instantiates a new ModelsBulkCreatePluginAssignmentsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsBulkCreatePluginAssignmentsRequest() *ModelsBulkCreatePluginAssignmentsRequest {
	this := ModelsBulkCreatePluginAssignmentsRequest{}
	return &this
}

// NewModelsBulkCreatePluginAssignmentsRequestWithDefaults instantiates a new ModelsBulkCreatePluginAssignmentsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsBulkCreatePluginAssignmentsRequestWithDefaults() *ModelsBulkCreatePluginAssignmentsRequest {
	this := ModelsBulkCreatePluginAssignmentsRequest{}
	return &this
}

// GetPersistentServerIds returns the PersistentServerIds field value if set, zero value otherwise.
func (o *ModelsBulkCreatePluginAssignmentsRequest) GetPersistentServerIds() []string {
	if o == nil || IsNil(o.PersistentServerIds) {
		var ret []string
		return ret
	}
	return o.PersistentServerIds
}

// GetPersistentServerIdsOk returns a tuple with the PersistentServerIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsBulkCreatePluginAssignmentsRequest) GetPersistentServerIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.PersistentServerIds) {
		return nil, false
	}
	return o.PersistentServerIds, true
}

// HasPersistentServerIds returns a boolean if a field has been set.
func (o *ModelsBulkCreatePluginAssignmentsRequest) HasPersistentServerIds() bool {
	if o != nil && !IsNil(o.PersistentServerIds) {
		return true
	}

	return false
}

// SetPersistentServerIds gets a reference to the given []string and assigns it to the PersistentServerIds field.
func (o *ModelsBulkCreatePluginAssignmentsRequest) SetPersistentServerIds(v []string) {
	o.PersistentServerIds = v
}

// GetPlugins returns the Plugins field value if set, zero value otherwise.
func (o *ModelsBulkCreatePluginAssignmentsRequest) GetPlugins() []ModelsPluginReferenceInput {
	if o == nil || IsNil(o.Plugins) {
		var ret []ModelsPluginReferenceInput
		return ret
	}
	return o.Plugins
}

// GetPluginsOk returns a tuple with the Plugins field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsBulkCreatePluginAssignmentsRequest) GetPluginsOk() ([]ModelsPluginReferenceInput, bool) {
	if o == nil || IsNil(o.Plugins) {
		return nil, false
	}
	return o.Plugins, true
}

// HasPlugins returns a boolean if a field has been set.
func (o *ModelsBulkCreatePluginAssignmentsRequest) HasPlugins() bool {
	if o != nil && !IsNil(o.Plugins) {
		return true
	}

	return false
}

// SetPlugins gets a reference to the given []ModelsPluginReferenceInput and assigns it to the Plugins field.
func (o *ModelsBulkCreatePluginAssignmentsRequest) SetPlugins(v []ModelsPluginReferenceInput) {
	o.Plugins = v
}

// GetServerGroupIds returns the ServerGroupIds field value if set, zero value otherwise.
func (o *ModelsBulkCreatePluginAssignmentsRequest) GetServerGroupIds() []string {
	if o == nil || IsNil(o.ServerGroupIds) {
		var ret []string
		return ret
	}
	return o.ServerGroupIds
}

// GetServerGroupIdsOk returns a tuple with the ServerGroupIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsBulkCreatePluginAssignmentsRequest) GetServerGroupIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.ServerGroupIds) {
		return nil, false
	}
	return o.ServerGroupIds, true
}

// HasServerGroupIds returns a boolean if a field has been set.
func (o *ModelsBulkCreatePluginAssignmentsRequest) HasServerGroupIds() bool {
	if o != nil && !IsNil(o.ServerGroupIds) {
		return true
	}

	return false
}

// SetServerGroupIds gets a reference to the given []string and assigns it to the ServerGroupIds field.
func (o *ModelsBulkCreatePluginAssignmentsRequest) SetServerGroupIds(v []string) {
	o.ServerGroupIds = v
}

func (o ModelsBulkCreatePluginAssignmentsRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsBulkCreatePluginAssignmentsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PersistentServerIds) {
		toSerialize["persistent_server_ids"] = o.PersistentServerIds
	}
	if !IsNil(o.Plugins) {
		toSerialize["plugins"] = o.Plugins
	}
	if !IsNil(o.ServerGroupIds) {
		toSerialize["server_group_ids"] = o.ServerGroupIds
	}
	return toSerialize, nil
}

type NullableModelsBulkCreatePluginAssignmentsRequest struct {
	value *ModelsBulkCreatePluginAssignmentsRequest
	isSet bool
}

func (v NullableModelsBulkCreatePluginAssignmentsRequest) Get() *ModelsBulkCreatePluginAssignmentsRequest {
	return v.value
}

func (v *NullableModelsBulkCreatePluginAssignmentsRequest) Set(val *ModelsBulkCreatePluginAssignmentsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsBulkCreatePluginAssignmentsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsBulkCreatePluginAssignmentsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsBulkCreatePluginAssignmentsRequest(val *ModelsBulkCreatePluginAssignmentsRequest) *NullableModelsBulkCreatePluginAssignmentsRequest {
	return &NullableModelsBulkCreatePluginAssignmentsRequest{value: val, isSet: true}
}

func (v NullableModelsBulkCreatePluginAssignmentsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsBulkCreatePluginAssignmentsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
