/*
SimpleCloud Controller API

API for SimpleCloud Controller

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplecloud

import (
	"encoding/json"
)

// checks if the ModelsCreatePluginCollectionAssignmentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsCreatePluginCollectionAssignmentRequest{}

// ModelsCreatePluginCollectionAssignmentRequest struct for ModelsCreatePluginCollectionAssignmentRequest
type ModelsCreatePluginCollectionAssignmentRequest struct {
	PersistentServerId *string `json:"persistent_server_id,omitempty"`
	PluginCollectionId *string `json:"plugin_collection_id,omitempty"`
	ServerGroupId      *string `json:"server_group_id,omitempty"`
}

// NewModelsCreatePluginCollectionAssignmentRequest instantiates a new ModelsCreatePluginCollectionAssignmentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsCreatePluginCollectionAssignmentRequest() *ModelsCreatePluginCollectionAssignmentRequest {
	this := ModelsCreatePluginCollectionAssignmentRequest{}
	return &this
}

// NewModelsCreatePluginCollectionAssignmentRequestWithDefaults instantiates a new ModelsCreatePluginCollectionAssignmentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsCreatePluginCollectionAssignmentRequestWithDefaults() *ModelsCreatePluginCollectionAssignmentRequest {
	this := ModelsCreatePluginCollectionAssignmentRequest{}
	return &this
}

// GetPersistentServerId returns the PersistentServerId field value if set, zero value otherwise.
func (o *ModelsCreatePluginCollectionAssignmentRequest) GetPersistentServerId() string {
	if o == nil || IsNil(o.PersistentServerId) {
		var ret string
		return ret
	}
	return *o.PersistentServerId
}

// GetPersistentServerIdOk returns a tuple with the PersistentServerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsCreatePluginCollectionAssignmentRequest) GetPersistentServerIdOk() (*string, bool) {
	if o == nil || IsNil(o.PersistentServerId) {
		return nil, false
	}
	return o.PersistentServerId, true
}

// HasPersistentServerId returns a boolean if a field has been set.
func (o *ModelsCreatePluginCollectionAssignmentRequest) HasPersistentServerId() bool {
	if o != nil && !IsNil(o.PersistentServerId) {
		return true
	}

	return false
}

// SetPersistentServerId gets a reference to the given string and assigns it to the PersistentServerId field.
func (o *ModelsCreatePluginCollectionAssignmentRequest) SetPersistentServerId(v string) {
	o.PersistentServerId = &v
}

// GetPluginCollectionId returns the PluginCollectionId field value if set, zero value otherwise.
func (o *ModelsCreatePluginCollectionAssignmentRequest) GetPluginCollectionId() string {
	if o == nil || IsNil(o.PluginCollectionId) {
		var ret string
		return ret
	}
	return *o.PluginCollectionId
}

// GetPluginCollectionIdOk returns a tuple with the PluginCollectionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsCreatePluginCollectionAssignmentRequest) GetPluginCollectionIdOk() (*string, bool) {
	if o == nil || IsNil(o.PluginCollectionId) {
		return nil, false
	}
	return o.PluginCollectionId, true
}

// HasPluginCollectionId returns a boolean if a field has been set.
func (o *ModelsCreatePluginCollectionAssignmentRequest) HasPluginCollectionId() bool {
	if o != nil && !IsNil(o.PluginCollectionId) {
		return true
	}

	return false
}

// SetPluginCollectionId gets a reference to the given string and assigns it to the PluginCollectionId field.
func (o *ModelsCreatePluginCollectionAssignmentRequest) SetPluginCollectionId(v string) {
	o.PluginCollectionId = &v
}

// GetServerGroupId returns the ServerGroupId field value if set, zero value otherwise.
func (o *ModelsCreatePluginCollectionAssignmentRequest) GetServerGroupId() string {
	if o == nil || IsNil(o.ServerGroupId) {
		var ret string
		return ret
	}
	return *o.ServerGroupId
}

// GetServerGroupIdOk returns a tuple with the ServerGroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsCreatePluginCollectionAssignmentRequest) GetServerGroupIdOk() (*string, bool) {
	if o == nil || IsNil(o.ServerGroupId) {
		return nil, false
	}
	return o.ServerGroupId, true
}

// HasServerGroupId returns a boolean if a field has been set.
func (o *ModelsCreatePluginCollectionAssignmentRequest) HasServerGroupId() bool {
	if o != nil && !IsNil(o.ServerGroupId) {
		return true
	}

	return false
}

// SetServerGroupId gets a reference to the given string and assigns it to the ServerGroupId field.
func (o *ModelsCreatePluginCollectionAssignmentRequest) SetServerGroupId(v string) {
	o.ServerGroupId = &v
}

func (o ModelsCreatePluginCollectionAssignmentRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsCreatePluginCollectionAssignmentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PersistentServerId) {
		toSerialize["persistent_server_id"] = o.PersistentServerId
	}
	if !IsNil(o.PluginCollectionId) {
		toSerialize["plugin_collection_id"] = o.PluginCollectionId
	}
	if !IsNil(o.ServerGroupId) {
		toSerialize["server_group_id"] = o.ServerGroupId
	}
	return toSerialize, nil
}

type NullableModelsCreatePluginCollectionAssignmentRequest struct {
	value *ModelsCreatePluginCollectionAssignmentRequest
	isSet bool
}

func (v NullableModelsCreatePluginCollectionAssignmentRequest) Get() *ModelsCreatePluginCollectionAssignmentRequest {
	return v.value
}

func (v *NullableModelsCreatePluginCollectionAssignmentRequest) Set(val *ModelsCreatePluginCollectionAssignmentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsCreatePluginCollectionAssignmentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsCreatePluginCollectionAssignmentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsCreatePluginCollectionAssignmentRequest(val *ModelsCreatePluginCollectionAssignmentRequest) *NullableModelsCreatePluginCollectionAssignmentRequest {
	return &NullableModelsCreatePluginCollectionAssignmentRequest{value: val, isSet: true}
}

func (v NullableModelsCreatePluginCollectionAssignmentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsCreatePluginCollectionAssignmentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
