/*
SimpleCloud Controller API

API for SimpleCloud Controller

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplecloud

import (
	"encoding/json"
)

// checks if the ModelsUpdateNetworkRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsUpdateNetworkRequest{}

// ModelsUpdateNetworkRequest Request for updating a network
type ModelsUpdateNetworkRequest struct {
	Name *string `json:"name,omitempty"`
}

// NewModelsUpdateNetworkRequest instantiates a new ModelsUpdateNetworkRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsUpdateNetworkRequest() *ModelsUpdateNetworkRequest {
	this := ModelsUpdateNetworkRequest{}
	return &this
}

// NewModelsUpdateNetworkRequestWithDefaults instantiates a new ModelsUpdateNetworkRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsUpdateNetworkRequestWithDefaults() *ModelsUpdateNetworkRequest {
	this := ModelsUpdateNetworkRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ModelsUpdateNetworkRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsUpdateNetworkRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ModelsUpdateNetworkRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ModelsUpdateNetworkRequest) SetName(v string) {
	o.Name = &v
}

func (o ModelsUpdateNetworkRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsUpdateNetworkRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableModelsUpdateNetworkRequest struct {
	value *ModelsUpdateNetworkRequest
	isSet bool
}

func (v NullableModelsUpdateNetworkRequest) Get() *ModelsUpdateNetworkRequest {
	return v.value
}

func (v *NullableModelsUpdateNetworkRequest) Set(val *ModelsUpdateNetworkRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsUpdateNetworkRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsUpdateNetworkRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsUpdateNetworkRequest(val *ModelsUpdateNetworkRequest) *NullableModelsUpdateNetworkRequest {
	return &NullableModelsUpdateNetworkRequest{value: val, isSet: true}
}

func (v NullableModelsUpdateNetworkRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsUpdateNetworkRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
