package simplecloud

import "github.com/simplecloudapp/cloud-api/go/generated"

type ModelsClearServerGroupStartQueueResponse = generated.ModelsClearServerGroupStartQueueResponse
type ModelsConnectPlayerRequest = generated.ModelsConnectPlayerRequest
type ModelsConnectPlayerResponse = generated.ModelsConnectPlayerResponse
type ModelsCreatePersistentServerRequest = generated.ModelsCreatePersistentServerRequest
type ModelsCreateServerGroupRequest = generated.ModelsCreateServerGroupRequest
type ModelsDeletePersistentServerResponse = generated.ModelsDeletePersistentServerResponse
type ModelsDeletePlayerPropertiesRequest = generated.ModelsDeletePlayerPropertiesRequest
type ModelsDeletePropertiesRequest = generated.ModelsDeletePropertiesRequest
type ModelsDeleteServerGroupResponse = generated.ModelsDeleteServerGroupResponse
type ModelsKickPlayerRequest = generated.ModelsKickPlayerRequest
type ModelsKickPlayerResponse = generated.ModelsKickPlayerResponse
type ModelsListServerGroupStartQueueResponse = generated.ModelsListServerGroupStartQueueResponse
type ModelsPatchPersistentServerRequest = generated.ModelsPatchPersistentServerRequest
type ModelsPatchPlayerRequest = generated.ModelsPatchPlayerRequest
type ModelsPatchPropertiesRequest = generated.ModelsPatchPropertiesRequest
type ModelsPatchServerGroupRequest = generated.ModelsPatchServerGroupRequest
type ModelsPatchServerRequest = generated.ModelsPatchServerRequest
type ModelsPersistentServerSummary = generated.ModelsPersistentServerSummary
type ModelsPlayerResponse = generated.ModelsPlayerResponse
type ModelsQueueServerGroupStartRequest = generated.ModelsQueueServerGroupStartRequest
type ModelsQueueServerGroupStartResponse = generated.ModelsQueueServerGroupStartResponse
type ModelsServerGroupSummary = generated.ModelsServerGroupSummary
type ModelsServerSummary = generated.ModelsServerSummary
type ModelsStopServerResponse = generated.ModelsStopServerResponse
type ModelsUpdatePlayerPropertiesRequest = generated.ModelsUpdatePlayerPropertiesRequest
