name: Import secrets and variables to Depot CI
on: push

permissions:
  id-token: write
  contents: read

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: depot/setup-action@v1
      - name: Import secrets
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
          SIMPLECLOUD_PASSWORD: ${{ secrets.SIMPLECLOUD_PASSWORD }}
          SIMPLECLOUD_USERNAME: ${{ secrets.SIMPLECLOUD_USERNAME }}
        run: |
          unset DEPOT_TOKEN
          depot ci secrets add MODRINTH_TOKEN="$MODRINTH_TOKEN" REGISTRY_TOKEN="$REGISTRY_TOKEN" SIMPLECLOUD_PASSWORD="$SIMPLECLOUD_PASSWORD" SIMPLECLOUD_USERNAME="$SIMPLECLOUD_USERNAME" --repo simplecloudapp/cloud-api
